[Tue Jan 28 06:25:02.054734 2020] [wsgi:warn] [pid 11115] mod_wsgi: Compiled for Python/2.7.11.
[Tue Jan 28 06:25:02.054754 2020] [wsgi:warn] [pid 11115] mod_wsgi: Runtime using Python/2.7.12.
[Tue Jan 28 06:25:02.055339 2020] [mpm_prefork:notice] [pid 11115] AH00163: Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g mod_wsgi/4.3.0 Python/2.7.12 configured -- resuming normal operations
[Tue Jan 28 06:25:02.055357 2020] [core:notice] [pid 11115] AH00094: Command line: '/usr/sbin/apache2'
[Tue Jan 28 06:26:45.803469 2020] [wsgi:error] [pid 25330] Loading user configuration
[Tue Jan 28 06:26:45.803921 2020] [wsgi:error] [pid 25330] running configuration {'server': {'maxrecords': '10', 'domaincounts': 'true', 'language': 'el', 'encoding': 'UTF-8', 'url': 'https://geoportal.ermis-f.eu/catalogue/csw', 'home': '.', 'pretty_print': 'true', 'profiles': 'apiso,ebrim', 'domainquerytype': 'range'}, 'metadata:main': {'identification_fees': 'None', 'provider_url': 'https://geoportal.ermis-f.eu/', 'identification_keywords': 'sdi, catalogue, discovery, metadata, GeoNode', 'contact_address': 'Mailing Address', 'identification_accessconstraints': 'None', 'contact_name': 'Lastname, Firstname', 'contact_stateorprovince': 'Administrative Area', 'contact_country': 'Country', 'contact_url': 'Contact URL', 'provider_name': 'Organization Name', 'contact_phone': '+xx-xxx-xxx-xxxx', 'contact_hours': 'Hours of Service', 'contact_role': 'pointOfContact', 'contact_email': 'Email Address', 'identification_title': 'GeoNode Catalogue', 'contact_postalcode': 'Zip or Postal Code', 'contact_city': 'City', 'identification_keywords_type': 'theme', 'identification_abstract': 'GeoNode is an open source platform that facilitates the creation, sharing, and collaborative use of geospatial data', 'contact_fax': '+xx-xxx-xxx-xxxx', 'contact_instructions': 'During hours of service. Off on weekends.', 'contact_position': 'Position Title'}, 'repository': {'filter': 'is_published = true AND id IN (160, 113, 80, 85, 73, 30, 112, 55, 110, 116, 117, 31, 150, 129, 39, 38, 56, 158, 118, 98, 78, 32, 97, 265, 57, 22, 273, 81, 59, 42, 23, 72, 37, 33, 130, 95, 182, 94, 69, 102, 24, 96, 82, 26, 74, 34, 264, 70, 263, 66, 35, 75, 83, 65, 173, 28, 58, 67, 46, 51, 36, 29, 60, 52, 62, 84, 255, 43, 174, 63, 41, 161, 124, 54, 64, 49, 257, 125, 25, 272, 149, 115, 27, 107, 146, 126, 271, 50, 268, 269, 144, 127, 61, 143, 154, 270, 128, 145, 262, 44, 267, 48, 266, 47) AND alternate IS NOT NULL', 'source': 'geonode.catalogue.backends.pycsw_plugin.GeoNodeRepository', 'mappings': '/home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py'}, 'metadata:inspire': {'conformity_service': 'notEvaluated', 'contact_email': 'Email Address', 'languages_supported': 'eng,gre', 'date': 'YYYY-MM-DD', 'default_language': 'eng', 'contact_name': 'Organization Name', 'gemet_keywords': 'Utility and governmental services', 'enabled': 'true', 'temp_extent': 'YYYY-MM-DD/YYYY-MM-DD'}}
[Tue Jan 28 06:26:45.804007 2020] [wsgi:error] [pid 25330] Setting language
[Tue Jan 28 06:26:45.804812 2020] [wsgi:error] [pid 25330] Loading custom repository mappings from /home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py
[Tue Jan 28 06:26:45.804929 2020] [wsgi:error] [pid 25330] Loading outputschemas
[Tue Jan 28 06:26:45.805761 2020] [wsgi:error] [pid 25330] Setting MaxRecordDefault
[Tue Jan 28 06:26:45.888223 2020] [wsgi:error] [pid 25330] Querying repository with ids: bedff5ce-99c7-11e9-a5ca-000c29291400
[Tue Jan 28 06:26:45.906911 2020] [wsgi:error] [pid 25330] Request processed
[Tue Jan 28 06:26:45.906972 2020] [wsgi:error] [pid 25330] Writing response.
[Tue Jan 28 06:41:07.837705 2020] [wsgi:error] [pid 25329] Loading user configuration
[Tue Jan 28 06:41:07.838281 2020] [wsgi:error] [pid 25329] running configuration <ConfigParser.SafeConfigParser instance at 0x7fd81f1b5d40>
[Tue Jan 28 06:41:07.838372 2020] [wsgi:error] [pid 25329] Setting language
[Tue Jan 28 06:41:07.839036 2020] [wsgi:error] [pid 25329] Loading custom repository mappings from /home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py
[Tue Jan 28 06:41:07.839151 2020] [wsgi:error] [pid 25329] Loading outputschemas
[Tue Jan 28 06:41:07.839599 2020] [wsgi:error] [pid 25329] Setting MaxRecordDefault
[Tue Jan 28 06:41:07.995875 2020] [wsgi:error] [pid 25329] Querying repository with ids: ffa48a5e-99c0-11e9-a5ca-000c29291400
[Tue Jan 28 06:41:08.016327 2020] [wsgi:error] [pid 25329] Request processed
[Tue Jan 28 06:41:08.016393 2020] [wsgi:error] [pid 25329] Writing response.
[Tue Jan 28 06:41:08.017932 2020] [wsgi:error] [pid 25329] /home/geo/Envs/geonode/lib/python2.7/site-packages/owslib/iso.py:117: FutureWarning: the .identification and .serviceidentification properties will merge into .identification being a list of properties.  This is currently implemented in .identificationinfo.  Please see https://github.com/geopython/OWSLib/issues/38 for more information
[Tue Jan 28 06:41:08.017943 2020] [wsgi:error] [pid 25329]   FutureWarning)
[Tue Jan 28 06:41:08.018657 2020] [wsgi:error] [pid 25329] /home/geo/Envs/geonode/lib/python2.7/site-packages/owslib/iso.py:482: FutureWarning: The .keywords and .keywords2 properties will merge into the .keywords property in the future, with .keywords becoming a list of MD_Keywords instances. This is currently implemented in .keywords2. Please see https://github.com/geopython/OWSLib/issues/301 for more information
[Tue Jan 28 06:41:08.018662 2020] [wsgi:error] [pid 25329]   FutureWarning)
[Tue Jan 28 07:26:37.412640 2020] [wsgi:error] [pid 25329] Loading user configuration
[Tue Jan 28 07:26:37.413363 2020] [wsgi:error] [pid 25329] running configuration {'server': {'maxrecords': '10', 'domaincounts': 'true', 'language': 'el', 'encoding': 'UTF-8', 'url': 'https://geoportal.ermis-f.eu/catalogue/csw', 'home': '.', 'pretty_print': 'true', 'profiles': 'apiso,ebrim', 'domainquerytype': 'range'}, 'metadata:main': {'identification_fees': 'None', 'provider_url': 'https://geoportal.ermis-f.eu/', 'identification_keywords': 'sdi, catalogue, discovery, metadata, GeoNode', 'contact_address': 'Mailing Address', 'identification_accessconstraints': 'None', 'contact_name': 'Lastname, Firstname', 'contact_stateorprovince': 'Administrative Area', 'contact_country': 'Country', 'contact_url': 'Contact URL', 'provider_name': 'Organization Name', 'contact_phone': '+xx-xxx-xxx-xxxx', 'contact_hours': 'Hours of Service', 'contact_role': 'pointOfContact', 'contact_email': 'Email Address', 'identification_title': 'GeoNode Catalogue', 'contact_postalcode': 'Zip or Postal Code', 'contact_city': 'City', 'identification_keywords_type': 'theme', 'identification_abstract': 'GeoNode is an open source platform that facilitates the creation, sharing, and collaborative use of geospatial data', 'contact_fax': '+xx-xxx-xxx-xxxx', 'contact_instructions': 'During hours of service. Off on weekends.', 'contact_position': 'Position Title'}, 'repository': {'filter': 'is_published = true AND id IN (160, 113, 80, 85, 73, 30, 112, 55, 110, 116, 117, 31, 150, 129, 39, 38, 56, 158, 118, 98, 78, 32, 97, 265, 57, 22, 273, 81, 59, 42, 23, 72, 37, 33, 130, 95, 182, 94, 69, 102, 24, 96, 82, 26, 74, 34, 264, 70, 263, 66, 35, 75, 83, 65, 173, 28, 58, 67, 46, 51, 36, 29, 60, 52, 62, 84, 255, 43, 174, 63, 41, 161, 124, 54, 64, 49, 257, 125, 25, 272, 149, 115, 27, 107, 146, 126, 271, 50, 268, 269, 144, 127, 61, 143, 154, 270, 128, 145, 262, 44, 267, 48, 266, 47) AND alternate IS NOT NULL', 'source': 'geonode.catalogue.backends.pycsw_plugin.GeoNodeRepository', 'mappings': '/home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py'}, 'metadata:inspire': {'conformity_service': 'notEvaluated', 'contact_email': 'Email Address', 'languages_supported': 'eng,gre', 'date': 'YYYY-MM-DD', 'default_language': 'eng', 'contact_name': 'Organization Name', 'gemet_keywords': 'Utility and governmental services', 'enabled': 'true', 'temp_extent': 'YYYY-MM-DD/YYYY-MM-DD'}}
[Tue Jan 28 07:26:37.413501 2020] [wsgi:error] [pid 25329] Setting language
[Tue Jan 28 07:26:37.414804 2020] [wsgi:error] [pid 25329] Loading custom repository mappings from /home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py
[Tue Jan 28 07:26:37.415008 2020] [wsgi:error] [pid 25329] Loading outputschemas
[Tue Jan 28 07:26:37.415772 2020] [wsgi:error] [pid 25329] Setting MaxRecordDefault
[Tue Jan 28 07:26:37.416583 2020] [wsgi:error] [pid 25329] Querying repository with ids: 1dffda30-99c1-11e9-a5ca-000c29291400
[Tue Jan 28 07:26:37.439743 2020] [wsgi:error] [pid 25329] Request processed
[Tue Jan 28 07:26:37.439818 2020] [wsgi:error] [pid 25329] Writing response.
[Tue Jan 28 09:34:50.687474 2020] [wsgi:error] [pid 25330] Loading user configuration
[Tue Jan 28 09:34:50.687890 2020] [wsgi:error] [pid 25330] running configuration {'server': {'maxrecords': '10', 'domaincounts': 'true', 'language': 'el', 'encoding': 'UTF-8', 'url': 'https://geoportal.ermis-f.eu/catalogue/csw', 'home': '.', 'pretty_print': 'true', 'profiles': 'apiso,ebrim', 'domainquerytype': 'range'}, 'metadata:main': {'identification_fees': 'None', 'provider_url': 'https://geoportal.ermis-f.eu/', 'identification_keywords': 'sdi, catalogue, discovery, metadata, GeoNode', 'contact_address': 'Mailing Address', 'identification_accessconstraints': 'None', 'contact_name': 'Lastname, Firstname', 'contact_stateorprovince': 'Administrative Area', 'contact_country': 'Country', 'contact_url': 'Contact URL', 'provider_name': 'Organization Name', 'contact_phone': '+xx-xxx-xxx-xxxx', 'contact_hours': 'Hours of Service', 'contact_role': 'pointOfContact', 'contact_email': 'Email Address', 'identification_title': 'GeoNode Catalogue', 'contact_postalcode': 'Zip or Postal Code', 'contact_city': 'City', 'identification_keywords_type': 'theme', 'identification_abstract': 'GeoNode is an open source platform that facilitates the creation, sharing, and collaborative use of geospatial data', 'contact_fax': '+xx-xxx-xxx-xxxx', 'contact_instructions': 'During hours of service. Off on weekends.', 'contact_position': 'Position Title'}, 'repository': {'filter': 'is_published = true AND id IN (160, 113, 80, 85, 73, 30, 112, 55, 110, 116, 117, 31, 150, 129, 39, 38, 56, 158, 118, 98, 78, 32, 97, 265, 57, 22, 273, 81, 59, 42, 23, 72, 37, 33, 130, 95, 182, 94, 69, 102, 24, 96, 82, 26, 74, 34, 264, 70, 263, 66, 35, 75, 83, 65, 173, 28, 58, 67, 46, 51, 36, 29, 60, 52, 62, 84, 255, 43, 174, 63, 41, 161, 124, 54, 64, 49, 257, 125, 25, 272, 149, 115, 27, 107, 146, 126, 271, 50, 268, 269, 144, 127, 61, 143, 154, 270, 128, 145, 262, 44, 267, 48, 266, 47) AND alternate IS NOT NULL', 'source': 'geonode.catalogue.backends.pycsw_plugin.GeoNodeRepository', 'mappings': '/home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py'}, 'metadata:inspire': {'conformity_service': 'notEvaluated', 'contact_email': 'Email Address', 'languages_supported': 'eng,gre', 'date': 'YYYY-MM-DD', 'default_language': 'eng', 'contact_name': 'Organization Name', 'gemet_keywords': 'Utility and governmental services', 'enabled': 'true', 'temp_extent': 'YYYY-MM-DD/YYYY-MM-DD'}}
[Tue Jan 28 09:34:50.687976 2020] [wsgi:error] [pid 25330] Setting language
[Tue Jan 28 09:34:50.688826 2020] [wsgi:error] [pid 25330] Loading custom repository mappings from /home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py
[Tue Jan 28 09:34:50.688940 2020] [wsgi:error] [pid 25330] Loading outputschemas
[Tue Jan 28 09:34:50.689154 2020] [wsgi:error] [pid 25330] Setting MaxRecordDefault
[Tue Jan 28 09:34:50.689730 2020] [wsgi:error] [pid 25330] Querying repository with ids: 1738228e-99c1-11e9-a5ca-000c29291400
[Tue Jan 28 09:34:50.694714 2020] [wsgi:error] [pid 25330] Request processed
[Tue Jan 28 09:34:50.694767 2020] [wsgi:error] [pid 25330] Writing response.
[Tue Jan 28 10:38:28.591242 2020] [wsgi:error] [pid 25330] Loading user configuration
[Tue Jan 28 10:38:28.591658 2020] [wsgi:error] [pid 25330] running configuration {'server': {'maxrecords': '10', 'domaincounts': 'true', 'language': 'el', 'encoding': 'UTF-8', 'url': 'https://geoportal.ermis-f.eu/catalogue/csw', 'home': '.', 'pretty_print': 'true', 'profiles': 'apiso,ebrim', 'domainquerytype': 'range'}, 'metadata:main': {'identification_fees': 'None', 'provider_url': 'https://geoportal.ermis-f.eu/', 'identification_keywords': 'sdi, catalogue, discovery, metadata, GeoNode', 'contact_address': 'Mailing Address', 'identification_accessconstraints': 'None', 'contact_name': 'Lastname, Firstname', 'contact_stateorprovince': 'Administrative Area', 'contact_country': 'Country', 'contact_url': 'Contact URL', 'provider_name': 'Organization Name', 'contact_phone': '+xx-xxx-xxx-xxxx', 'contact_hours': 'Hours of Service', 'contact_role': 'pointOfContact', 'contact_email': 'Email Address', 'identification_title': 'GeoNode Catalogue', 'contact_postalcode': 'Zip or Postal Code', 'contact_city': 'City', 'identification_keywords_type': 'theme', 'identification_abstract': 'GeoNode is an open source platform that facilitates the creation, sharing, and collaborative use of geospatial data', 'contact_fax': '+xx-xxx-xxx-xxxx', 'contact_instructions': 'During hours of service. Off on weekends.', 'contact_position': 'Position Title'}, 'repository': {'filter': 'is_published = true AND id IN (160, 113, 80, 85, 73, 30, 112, 55, 110, 116, 31, 117, 150, 129, 39, 38, 56, 158, 118, 98, 78, 32, 97, 265, 57, 22, 273, 81, 59, 42, 23, 72, 37, 33, 130, 95, 182, 94, 69, 102, 24, 96, 82, 26, 74, 34, 264, 70, 66, 35, 75, 83, 65, 173, 28, 58, 67, 46, 51, 36, 29, 60, 52, 62, 84, 255, 43, 174, 63, 41, 161, 124, 54, 64, 49, 257, 125, 25, 149, 272, 115, 27, 107, 263, 146, 126, 271, 50, 268, 269, 144, 127, 61, 143, 154, 270, 128, 145, 262, 44, 267, 48, 266, 47) AND alternate IS NOT NULL', 'source': 'geonode.catalogue.backends.pycsw_plugin.GeoNodeRepository', 'mappings': '/home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py'}, 'metadata:inspire': {'conformity_service': 'notEvaluated', 'contact_email': 'Email Address', 'languages_supported': 'eng,gre', 'date': 'YYYY-MM-DD', 'default_language': 'eng', 'contact_name': 'Organization Name', 'gemet_keywords': 'Utility and governmental services', 'enabled': 'true', 'temp_extent': 'YYYY-MM-DD/YYYY-MM-DD'}}
[Tue Jan 28 10:38:28.591754 2020] [wsgi:error] [pid 25330] Setting language
[Tue Jan 28 10:38:28.592268 2020] [wsgi:error] [pid 25330] Loading custom repository mappings from /home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py
[Tue Jan 28 10:38:28.592379 2020] [wsgi:error] [pid 25330] Loading outputschemas
[Tue Jan 28 10:38:28.592582 2020] [wsgi:error] [pid 25330] Setting MaxRecordDefault
[Tue Jan 28 10:38:28.593179 2020] [wsgi:error] [pid 25330] Querying repository with ids: 56a1138a-99c7-11e9-a5ca-000c29291400
[Tue Jan 28 10:38:28.600681 2020] [wsgi:error] [pid 25330] Request processed
[Tue Jan 28 10:38:28.600732 2020] [wsgi:error] [pid 25330] Writing response.
[Tue Jan 28 10:53:27.230719 2020] [wsgi:error] [pid 25329] Resource metadata;\r
[Tue Jan 28 10:53:27.230749 2020] [wsgi:error] [pid 25329] uuid;88c71ea8-7099-45d8-89ff-d95304301284;\r
[Tue Jan 28 10:53:27.230752 2020] [wsgi:error] [pid 25329] title;\xce\x99\xcf\x83\xcf\x84\xce\xbf\xcf\x81\xce\xb9\xce\xba\xce\xad\xcf\x82 \xce\xa0\xce\xbb\xcf\x85\xce\xbc\xce\xbc\xce\xae\xcf\x81\xce\xb5\xcf\x82;\r
[Tue Jan 28 10:53:27.230755 2020] [wsgi:error] [pid 25329] resource owner;vkopsachilis;\r
[Tue Jan 28 10:53:27.230757 2020] [wsgi:error] [pid 25329] date;2019-12-06 11:45:00+00:00;\r
[Tue Jan 28 10:53:27.230760 2020] [wsgi:error] [pid 25329] date type;publication;\r
[Tue Jan 28 10:53:27.230763 2020] [wsgi:error] [pid 25329] abstract;\xce\x9a\xce\xb1\xcf\x84\xce\xb1\xce\xb3\xce\xb5\xce\xb3\xcf\x81\xce\xb1\xce\xbc\xce\xbc\xce\xad\xce\xbd\xce\xb1 \xce\xb9\xcf\x83\xcf\x84\xce\xbf\xcf\x81\xce\xb9\xce\xba\xce\xac \xcf\x80\xce\xbb\xce\xb7\xce\xbc\xce\xbc\xcf\x85\xcf\x81\xce\xb9\xce\xba\xce\xac \xce\xb3\xce\xb5\xce\xb3\xce\xbf\xce\xbd\xcf\x8c\xcf\x84\xce\xb1;\r
[Tue Jan 28 10:53:27.230766 2020] [wsgi:error] [pid 25329] edition;None;\r
[Tue Jan 28 10:53:27.230768 2020] [wsgi:error] [pid 25329] purpose;;\r
[Tue Jan 28 10:53:27.230770 2020] [wsgi:error] [pid 25329] maintenance frequency;None;\r
[Tue Jan 28 10:53:27.230781 2020] [wsgi:error] [pid 25329] ObjectDoesNotExist;\r
[Tue Jan 28 10:53:27.230783 2020] [wsgi:error] [pid 25329] restriction code type;None;\r
[Tue Jan 28 10:53:27.230785 2020] [wsgi:error] [pid 25329] constraints other ;;\r
[Tue Jan 28 10:53:27.230787 2020] [wsgi:error] [pid 25329] license;\xce\x9c\xce\xb7 \xce\xba\xce\xb1\xce\xb8\xce\xbf\xcf\x81\xce\xb9\xcf\x83\xce\xbc\xce\xad\xce\xbd\xce\xb7;\r
[Tue Jan 28 10:53:27.230790 2020] [wsgi:error] [pid 25329] language;gre;\r
[Tue Jan 28 10:53:27.230792 2020] [wsgi:error] [pid 25329] temporal extent;\r
[Tue Jan 28 10:53:27.230794 2020] [wsgi:error] [pid 25329] temporal extent start;None;\r
[Tue Jan 28 10:53:27.230796 2020] [wsgi:error] [pid 25329] temporal extent end;None;\r
[Tue Jan 28 10:53:27.230798 2020] [wsgi:error] [pid 25329] supplemental information;No information provided;\r
[Tue Jan 28 10:53:27.230800 2020] [wsgi:error] [pid 25329] data quality statement;;\r
[Tue Jan 28 10:53:27.230802 2020] [wsgi:error] [pid 25329] extent ;23.500000000000000,34.000000000000000,34.659999999999997,39.329999999999998;\r
[Tue Jan 28 10:53:27.230805 2020] [wsgi:error] [pid 25329] SRID  ;EPSG:4326;\r
[Tue Jan 28 10:53:27.230807 2020] [wsgi:error] [pid 25329] Thumbnail url;https://geoportal.ermis-f.eu/uploaded/thumbs/layer-88c71ea8-7099-45d8-89ff-d95304301284-thumb.png;\r
[Tue Jan 28 10:53:27.230809 2020] [wsgi:error] [pid 25329] keywords;;category;\xce\x95\xcf\x83\xcf\x89\xcf\x84\xce\xb5\xcf\x81\xce\xb9\xce\xba\xce\xac \xcf\x8d\xce\xb4\xce\xb1\xcf\x84\xce\xb1;\r
[Tue Jan 28 10:53:27.230811 2020] [wsgi:error] [pid 25329] regions;Europe,Greece,Lesvos,Cyprus,Crete;\r
[Tue Jan 28 10:53:27.230814 2020] [wsgi:error] [pid 25329] attribute data;\r
[Tue Jan 28 10:53:27.230816 2020] [wsgi:error] [pid 25329] attribute name;label;description
[Tue Jan 28 10:53:27.230818 2020] [wsgi:error] [pid 25329] Point of Contact;\r
[Tue Jan 28 10:53:27.230820 2020] [wsgi:error] [pid 25329] name;Kopsachilis;\r
[Tue Jan 28 10:53:27.230822 2020] [wsgi:error] [pid 25329] e-mail;;\r
[Tue Jan 28 10:53:27.230824 2020] [wsgi:error] [pid 25329] 
[Tue Jan 28 12:01:19.707351 2020] [wsgi:error] [pid 25330] Loading user configuration
[Tue Jan 28 12:01:19.707766 2020] [wsgi:error] [pid 25330] running configuration {'server': {'maxrecords': '10', 'domaincounts': 'true', 'language': 'el', 'encoding': 'UTF-8', 'url': 'https://geoportal.ermis-f.eu/catalogue/csw', 'home': '.', 'pretty_print': 'true', 'profiles': 'apiso,ebrim', 'domainquerytype': 'range'}, 'metadata:main': {'identification_fees': 'None', 'provider_url': 'https://geoportal.ermis-f.eu/', 'identification_keywords': 'sdi, catalogue, discovery, metadata, GeoNode', 'contact_address': 'Mailing Address', 'identification_accessconstraints': 'None', 'contact_name': 'Lastname, Firstname', 'contact_stateorprovince': 'Administrative Area', 'contact_country': 'Country', 'contact_url': 'Contact URL', 'provider_name': 'Organization Name', 'contact_phone': '+xx-xxx-xxx-xxxx', 'contact_hours': 'Hours of Service', 'contact_role': 'pointOfContact', 'contact_email': 'Email Address', 'identification_title': 'GeoNode Catalogue', 'contact_postalcode': 'Zip or Postal Code', 'contact_city': 'City', 'identification_keywords_type': 'theme', 'identification_abstract': 'GeoNode is an open source platform that facilitates the creation, sharing, and collaborative use of geospatial data', 'contact_fax': '+xx-xxx-xxx-xxxx', 'contact_instructions': 'During hours of service. Off on weekends.', 'contact_position': 'Position Title'}, 'repository': {'filter': 'is_published = true AND id IN (160, 113, 80, 85, 73, 30, 112, 55, 110, 116, 31, 117, 150, 129, 39, 38, 118, 56, 158, 98, 78, 32, 97, 265, 57, 22, 273, 81, 59, 42, 23, 72, 37, 33, 130, 95, 182, 94, 69, 102, 24, 96, 82, 26, 74, 34, 264, 70, 66, 35, 75, 83, 65, 173, 28, 58, 67, 46, 51, 36, 29, 60, 52, 62, 84, 255, 43, 174, 63, 41, 161, 124, 54, 64, 49, 257, 125, 25, 149, 272, 115, 27, 107, 263, 146, 126, 271, 50, 268, 269, 144, 127, 61, 143, 154, 270, 128, 145, 262, 44, 267, 48, 266, 47) AND alternate IS NOT NULL', 'source': 'geonode.catalogue.backends.pycsw_plugin.GeoNodeRepository', 'mappings': '/home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py'}, 'metadata:inspire': {'conformity_service': 'notEvaluated', 'contact_email': 'Email Address', 'languages_supported': 'eng,gre', 'date': 'YYYY-MM-DD', 'default_language': 'eng', 'contact_name': 'Organization Name', 'gemet_keywords': 'Utility and governmental services', 'enabled': 'true', 'temp_extent': 'YYYY-MM-DD/YYYY-MM-DD'}}
[Tue Jan 28 12:01:19.707861 2020] [wsgi:error] [pid 25330] Setting language
[Tue Jan 28 12:01:19.708634 2020] [wsgi:error] [pid 25330] Loading custom repository mappings from /home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py
[Tue Jan 28 12:01:19.708746 2020] [wsgi:error] [pid 25330] Loading outputschemas
[Tue Jan 28 12:01:19.708941 2020] [wsgi:error] [pid 25330] Setting MaxRecordDefault
[Tue Jan 28 12:01:19.709455 2020] [wsgi:error] [pid 25330] Querying repository with ids: bedff5ce-99c7-11e9-a5ca-000c29291400
[Tue Jan 28 12:01:19.714626 2020] [wsgi:error] [pid 25330] Request processed
[Tue Jan 28 12:01:19.714679 2020] [wsgi:error] [pid 25330] Writing response.
[Tue Jan 28 12:01:23.994656 2020] [wsgi:error] [pid 25330] uploaded_files: [<InMemoryUploadedFile: \xce\x99\xcf\x81\xce\xbb\xce\xb1\xce\xbd\xce\xb4\xce\xb9\xce\xba\xce\xad\xcf\x82 \xce\x94\xce\xb9\xce\xb1\xce\xb2\xce\xac\xcf\x83\xce\xb5\xce\xb9\xcf\x82.shp (application/octet-stream)>, <InMemoryUploadedFile: \xce\x99\xcf\x81\xce\xbb\xce\xb1\xce\xbd\xce\xb4\xce\xb9\xce\xba\xce\xad\xcf\x82 \xce\x94\xce\xb9\xce\xb1\xce\xb2\xce\xac\xcf\x83\xce\xb5\xce\xb9\xcf\x82.sbn (application/octet-stream)>, <InMemoryUploadedFile: \xce\x99\xcf\x81\xce\xbb\xce\xb1\xce\xbd\xce\xb4\xce\xb9\xce\xba\xce\xad\xcf\x82 \xce\x94\xce\xb9\xce\xb1\xce\xb2\xce\xac\xcf\x83\xce\xb5\xce\xb9\xcf\x82.prj (application/octet-stream)>, <InMemoryUploadedFile: \xce\x99\xcf\x81\xce\xbb\xce\xb1\xce\xbd\xce\xb4\xce\xb9\xce\xba\xce\xad\xcf\x82 \xce\x94\xce\xb9\xce\xb1\xce\xb2\xce\xac\xcf\x83\xce\xb5\xce\xb9\xcf\x82.cpg (application/octet-stream)>, <InMemoryUploadedFile: \xce\x99\xcf\x81\xce\xbb\xce\xb1\xce\xbd\xce\xb4\xce\xb9\xce\xba\xce\xad\xcf\x82 \xce\x94\xce\xb9\xce\xb1\xce\xb2\xce\xac\xcf\x83\xce\xb5\xce\xb9\xcf\x82.sbx (application/octet-stream)>, <InMemoryUploadedFile: \xce\x99\xcf\x81\xce\xbb\xce\xb1\xce\xbd\xce\xb4\xce\xb9\xce\xba\xce\xad\xcf\x82 \xce\x94\xce\xb9\xce\xb1\xce\xb2\xce\xac\xcf\x83\xce\xb5\xce\xb9\xcf\x82.shx (application/octet-stream)>, <InMemoryUploadedFile: \xce\x99\xcf\x81\xce\xbb\xce\xb1\xce\xbd\xce\xb4\xce\xb9\xce\xba\xce\xad\xcf\x82 \xce\x94\xce\xb9\xce\xb1\xce\xb2\xce\xac\xcf\x83\xce\xb5\xce\xb9\xcf\x82.dbf (application/octet-stream)>]
[Tue Jan 28 12:01:23.996854 2020] [wsgi:error] [pid 25330] valid_extensions: [u'shp', 'dbf', 'shx', 'prj']
[Tue Jan 28 12:01:23.997904 2020] [wsgi:error] [pid 25330] \xce\x99\xcf\x81\xce\xbb\xce\xb1\xce\xbd\xce\xb4\xce\xb9\xce\xba\xce\xad\xcf\x82 \xce\x94\xce\xb9\xce\xb1\xce\xb2\xce\xac\xcf\x83\xce\xb5\xce\xb9\xcf\x82
[Tue Jan 28 12:01:23.999291 2020] [wsgi:error] [pid 25330] Name for layer: u'_'
[Tue Jan 28 12:01:24.102927 2020] [wsgi:error] [pid 25330] files_to_upload: [u'/tmp/tmpACwSFR/_.shp', u'/tmp/tmpACwSFR/_.shx', u'/tmp/tmpACwSFR/_.dbf', u'/tmp/tmpACwSFR/_.prj']
[Tue Jan 28 12:01:24.102988 2020] [wsgi:error] [pid 25330] Uploading featureType
[Tue Jan 28 12:01:24.107872 2020] [wsgi:error] [pid 25330] /home/geo/Envs/geonode/lib/python2.7/site-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
[Tue Jan 28 12:01:24.107885 2020] [wsgi:error] [pid 25330]   InsecureRequestWarning)
[Tue Jan 28 12:01:24.124896 2020] [wsgi:error] [pid 25330] /home/geo/Envs/geonode/lib/python2.7/site-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
[Tue Jan 28 12:01:24.124918 2020] [wsgi:error] [pid 25330]   InsecureRequestWarning)
[Tue Jan 28 12:01:24.142884 2020] [wsgi:error] [pid 25330] /home/geo/Envs/geonode/lib/python2.7/site-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
[Tue Jan 28 12:01:24.142896 2020] [wsgi:error] [pid 25330]   InsecureRequestWarning)
[Tue Jan 28 12:01:24.266542 2020] [wsgi:error] [pid 25330] Internal Server Error: /upload/check
[Tue Jan 28 12:01:24.266558 2020] [wsgi:error] [pid 25330] Traceback (most recent call last):
[Tue Jan 28 12:01:24.266561 2020] [wsgi:error] [pid 25330]   File "/home/geo/Envs/geonode/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
[Tue Jan 28 12:01:24.266565 2020] [wsgi:error] [pid 25330]     response = get_response(request)
[Tue Jan 28 12:01:24.266568 2020] [wsgi:error] [pid 25330]   File "/home/geo/Envs/geonode/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
[Tue Jan 28 12:01:24.266572 2020] [wsgi:error] [pid 25330]     response = self._get_response(request)
[Tue Jan 28 12:01:24.266576 2020] [wsgi:error] [pid 25330]   File "/home/geo/Envs/geonode/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
[Tue Jan 28 12:01:24.266579 2020] [wsgi:error] [pid 25330]     response = self.process_exception_by_middleware(e, request)
[Tue Jan 28 12:01:24.266583 2020] [wsgi:error] [pid 25330]   File "/home/geo/Envs/geonode/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
[Tue Jan 28 12:01:24.266586 2020] [wsgi:error] [pid 25330]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Tue Jan 28 12:01:24.266590 2020] [wsgi:error] [pid 25330]   File "/home/geo/Envs/geonode/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
[Tue Jan 28 12:01:24.266593 2020] [wsgi:error] [pid 25330]     return view_func(request, *args, **kwargs)
[Tue Jan 28 12:01:24.266596 2020] [wsgi:error] [pid 25330]   File "/home/geo/Envs/geonode/src/geonode/geonode/upload/views.py", line 639, in view
[Tue Jan 28 12:01:24.266600 2020] [wsgi:error] [pid 25330]     session = upload_obj.get_session()
[Tue Jan 28 12:01:24.266603 2020] [wsgi:error] [pid 25330]   File "/home/geo/Envs/geonode/src/geonode/geonode/upload/models.py", line 91, in get_session
[Tue Jan 28 12:01:24.266607 2020] [wsgi:error] [pid 25330]     return pickle.loads(str(self.session))
[Tue Jan 28 12:01:24.266610 2020] [wsgi:error] [pid 25330] UnicodeEncodeError: 'ascii' codec can't encode characters in position 1053-1057: ordinal not in range(128)
[Tue Jan 28 12:31:16.561115 2020] [wsgi:error] [pid 25330] Loading user configuration
[Tue Jan 28 12:31:16.561532 2020] [wsgi:error] [pid 25330] running configuration {'server': {'maxrecords': '10', 'domaincounts': 'true', 'language': 'el', 'encoding': 'UTF-8', 'url': 'https://geoportal.ermis-f.eu/catalogue/csw', 'home': '.', 'pretty_print': 'true', 'profiles': 'apiso,ebrim', 'domainquerytype': 'range'}, 'metadata:main': {'identification_fees': 'None', 'provider_url': 'https://geoportal.ermis-f.eu/', 'identification_keywords': 'sdi, catalogue, discovery, metadata, GeoNode', 'contact_address': 'Mailing Address', 'identification_accessconstraints': 'None', 'contact_name': 'Lastname, Firstname', 'contact_stateorprovince': 'Administrative Area', 'contact_country': 'Country', 'contact_url': 'Contact URL', 'provider_name': 'Organization Name', 'contact_phone': '+xx-xxx-xxx-xxxx', 'contact_hours': 'Hours of Service', 'contact_role': 'pointOfContact', 'contact_email': 'Email Address', 'identification_title': 'GeoNode Catalogue', 'contact_postalcode': 'Zip or Postal Code', 'contact_city': 'City', 'identification_keywords_type': 'theme', 'identification_abstract': 'GeoNode is an open source platform that facilitates the creation, sharing, and collaborative use of geospatial data', 'contact_fax': '+xx-xxx-xxx-xxxx', 'contact_instructions': 'During hours of service. Off on weekends.', 'contact_position': 'Position Title'}, 'repository': {'filter': 'is_published = true AND id IN (160, 113, 80, 85, 73, 30, 112, 55, 110, 116, 31, 117, 150, 129, 39, 38, 118, 56, 158, 98, 78, 32, 97, 265, 57, 22, 273, 81, 59, 42, 23, 72, 37, 33, 130, 95, 182, 94, 69, 102, 24, 96, 82, 26, 74, 34, 264, 70, 66, 35, 75, 83, 65, 173, 28, 58, 67, 46, 51, 36, 29, 60, 52, 62, 84, 255, 43, 174, 63, 41, 161, 124, 54, 64, 49, 257, 125, 25, 149, 272, 115, 27, 107, 263, 146, 126, 271, 50, 268, 269, 144, 127, 61, 143, 154, 270, 128, 145, 262, 44, 267, 48, 266, 47) AND alternate IS NOT NULL', 'source': 'geonode.catalogue.backends.pycsw_plugin.GeoNodeRepository', 'mappings': '/home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py'}, 'metadata:inspire': {'conformity_service': 'notEvaluated', 'contact_email': 'Email Address', 'languages_supported': 'eng,gre', 'date': 'YYYY-MM-DD', 'default_language': 'eng', 'contact_name': 'Organization Name', 'gemet_keywords': 'Utility and governmental services', 'enabled': 'true', 'temp_extent': 'YYYY-MM-DD/YYYY-MM-DD'}}
[Tue Jan 28 12:31:16.561634 2020] [wsgi:error] [pid 25330] Setting language
[Tue Jan 28 12:31:16.562115 2020] [wsgi:error] [pid 25330] Loading custom repository mappings from /home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py
[Tue Jan 28 12:31:16.562225 2020] [wsgi:error] [pid 25330] Loading outputschemas
[Tue Jan 28 12:31:16.562431 2020] [wsgi:error] [pid 25330] Setting MaxRecordDefault
[Tue Jan 28 12:31:16.562984 2020] [wsgi:error] [pid 25330] Querying repository with ids: 1738228e-99c1-11e9-a5ca-000c29291400
[Tue Jan 28 12:31:16.576273 2020] [wsgi:error] [pid 25330] Request processed
[Tue Jan 28 12:31:16.576329 2020] [wsgi:error] [pid 25330] Writing response.
[Tue Jan 28 12:31:16.647133 2020] [wsgi:error] [pid 25329] Loading user configuration
[Tue Jan 28 12:31:16.647553 2020] [wsgi:error] [pid 25329] running configuration {'server': {'maxrecords': '10', 'domaincounts': 'true', 'language': 'el', 'encoding': 'UTF-8', 'url': 'https://geoportal.ermis-f.eu/catalogue/csw', 'home': '.', 'pretty_print': 'true', 'profiles': 'apiso,ebrim', 'domainquerytype': 'range'}, 'metadata:main': {'identification_fees': 'None', 'provider_url': 'https://geoportal.ermis-f.eu/', 'identification_keywords': 'sdi, catalogue, discovery, metadata, GeoNode', 'contact_address': 'Mailing Address', 'identification_accessconstraints': 'None', 'contact_name': 'Lastname, Firstname', 'contact_stateorprovince': 'Administrative Area', 'contact_country': 'Country', 'contact_url': 'Contact URL', 'provider_name': 'Organization Name', 'contact_phone': '+xx-xxx-xxx-xxxx', 'contact_hours': 'Hours of Service', 'contact_role': 'pointOfContact', 'contact_email': 'Email Address', 'identification_title': 'GeoNode Catalogue', 'contact_postalcode': 'Zip or Postal Code', 'contact_city': 'City', 'identification_keywords_type': 'theme', 'identification_abstract': 'GeoNode is an open source platform that facilitates the creation, sharing, and collaborative use of geospatial data', 'contact_fax': '+xx-xxx-xxx-xxxx', 'contact_instructions': 'During hours of service. Off on weekends.', 'contact_position': 'Position Title'}, 'repository': {'filter': 'is_published = true AND id IN (160, 113, 80, 85, 73, 30, 112, 55, 110, 116, 31, 117, 150, 129, 39, 38, 118, 56, 158, 98, 78, 32, 97, 265, 57, 22, 273, 81, 59, 42, 23, 72, 37, 33, 130, 95, 182, 94, 69, 102, 24, 96, 82, 26, 74, 34, 264, 70, 66, 35, 75, 83, 65, 173, 28, 58, 67, 46, 51, 36, 29, 60, 52, 62, 84, 255, 43, 174, 63, 41, 161, 124, 54, 64, 49, 257, 125, 25, 149, 272, 115, 27, 107, 263, 146, 126, 271, 50, 268, 269, 144, 127, 61, 143, 154, 270, 128, 145, 262, 44, 267, 48, 266, 47) AND alternate IS NOT NULL', 'source': 'geonode.catalogue.backends.pycsw_plugin.GeoNodeRepository', 'mappings': '/home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py'}, 'metadata:inspire': {'conformity_service': 'notEvaluated', 'contact_email': 'Email Address', 'languages_supported': 'eng,gre', 'date': 'YYYY-MM-DD', 'default_language': 'eng', 'contact_name': 'Organization Name', 'gemet_keywords': 'Utility and governmental services', 'enabled': 'true', 'temp_extent': 'YYYY-MM-DD/YYYY-MM-DD'}}
[Tue Jan 28 12:31:16.647654 2020] [wsgi:error] [pid 25329] Setting language
[Tue Jan 28 12:31:16.648150 2020] [wsgi:error] [pid 25329] Loading custom repository mappings from /home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py
[Tue Jan 28 12:31:16.648260 2020] [wsgi:error] [pid 25329] Loading outputschemas
[Tue Jan 28 12:31:16.648470 2020] [wsgi:error] [pid 25329] Setting MaxRecordDefault
[Tue Jan 28 12:31:16.649009 2020] [wsgi:error] [pid 25329] Querying repository with ids: 1738228e-99c1-11e9-a5ca-000c29291400
[Tue Jan 28 12:31:16.664714 2020] [wsgi:error] [pid 25329] Request processed
[Tue Jan 28 12:31:16.664772 2020] [wsgi:error] [pid 25329] Writing response.
[Tue Jan 28 12:31:16.737693 2020] [wsgi:error] [pid 25330] Loading user configuration
[Tue Jan 28 12:31:16.738092 2020] [wsgi:error] [pid 25330] running configuration {'server': {'maxrecords': '10', 'domaincounts': 'true', 'language': 'el', 'encoding': 'UTF-8', 'url': 'https://geoportal.ermis-f.eu/catalogue/csw', 'home': '.', 'pretty_print': 'true', 'profiles': 'apiso,ebrim', 'domainquerytype': 'range'}, 'metadata:main': {'identification_fees': 'None', 'provider_url': 'https://geoportal.ermis-f.eu/', 'identification_keywords': 'sdi, catalogue, discovery, metadata, GeoNode', 'contact_address': 'Mailing Address', 'identification_accessconstraints': 'None', 'contact_name': 'Lastname, Firstname', 'contact_stateorprovince': 'Administrative Area', 'contact_country': 'Country', 'contact_url': 'Contact URL', 'provider_name': 'Organization Name', 'contact_phone': '+xx-xxx-xxx-xxxx', 'contact_hours': 'Hours of Service', 'contact_role': 'pointOfContact', 'contact_email': 'Email Address', 'identification_title': 'GeoNode Catalogue', 'contact_postalcode': 'Zip or Postal Code', 'contact_city': 'City', 'identification_keywords_type': 'theme', 'identification_abstract': 'GeoNode is an open source platform that facilitates the creation, sharing, and collaborative use of geospatial data', 'contact_fax': '+xx-xxx-xxx-xxxx', 'contact_instructions': 'During hours of service. Off on weekends.', 'contact_position': 'Position Title'}, 'repository': {'filter': 'is_published = true AND id IN (160, 113, 80, 85, 73, 30, 112, 55, 110, 116, 31, 117, 150, 129, 39, 38, 118, 56, 158, 98, 78, 32, 97, 265, 57, 22, 273, 81, 59, 42, 23, 72, 37, 33, 130, 95, 182, 94, 69, 102, 24, 96, 82, 26, 74, 34, 264, 70, 66, 35, 75, 83, 65, 173, 28, 58, 67, 46, 51, 36, 29, 60, 52, 62, 84, 255, 43, 174, 63, 41, 161, 124, 54, 64, 49, 257, 125, 25, 149, 272, 115, 27, 107, 263, 146, 126, 271, 50, 268, 269, 144, 127, 61, 143, 154, 270, 128, 145, 262, 44, 267, 48, 266, 47) AND alternate IS NOT NULL', 'source': 'geonode.catalogue.backends.pycsw_plugin.GeoNodeRepository', 'mappings': '/home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py'}, 'metadata:inspire': {'conformity_service': 'notEvaluated', 'contact_email': 'Email Address', 'languages_supported': 'eng,gre', 'date': 'YYYY-MM-DD', 'default_language': 'eng', 'contact_name': 'Organization Name', 'gemet_keywords': 'Utility and governmental services', 'enabled': 'true', 'temp_extent': 'YYYY-MM-DD/YYYY-MM-DD'}}
[Tue Jan 28 12:31:16.738176 2020] [wsgi:error] [pid 25330] Setting language
[Tue Jan 28 12:31:16.738596 2020] [wsgi:error] [pid 25330] Loading custom repository mappings from /home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py
[Tue Jan 28 12:31:16.738705 2020] [wsgi:error] [pid 25330] Loading outputschemas
[Tue Jan 28 12:31:16.738901 2020] [wsgi:error] [pid 25330] Setting MaxRecordDefault
[Tue Jan 28 12:31:16.739737 2020] [wsgi:error] [pid 25330] Querying repository with ids: 1738228e-99c1-11e9-a5ca-000c29291400
[Tue Jan 28 12:31:16.756758 2020] [wsgi:error] [pid 25330] Request processed
[Tue Jan 28 12:31:16.756812 2020] [wsgi:error] [pid 25330] Writing response.
[Tue Jan 28 12:31:16.825926 2020] [wsgi:error] [pid 25329] Loading user configuration
[Tue Jan 28 12:31:16.826329 2020] [wsgi:error] [pid 25329] running configuration {'server': {'maxrecords': '10', 'domaincounts': 'true', 'language': 'el', 'encoding': 'UTF-8', 'url': 'https://geoportal.ermis-f.eu/catalogue/csw', 'home': '.', 'pretty_print': 'true', 'profiles': 'apiso,ebrim', 'domainquerytype': 'range'}, 'metadata:main': {'identification_fees': 'None', 'provider_url': 'https://geoportal.ermis-f.eu/', 'identification_keywords': 'sdi, catalogue, discovery, metadata, GeoNode', 'contact_address': 'Mailing Address', 'identification_accessconstraints': 'None', 'contact_name': 'Lastname, Firstname', 'contact_stateorprovince': 'Administrative Area', 'contact_country': 'Country', 'contact_url': 'Contact URL', 'provider_name': 'Organization Name', 'contact_phone': '+xx-xxx-xxx-xxxx', 'contact_hours': 'Hours of Service', 'contact_role': 'pointOfContact', 'contact_email': 'Email Address', 'identification_title': 'GeoNode Catalogue', 'contact_postalcode': 'Zip or Postal Code', 'contact_city': 'City', 'identification_keywords_type': 'theme', 'identification_abstract': 'GeoNode is an open source platform that facilitates the creation, sharing, and collaborative use of geospatial data', 'contact_fax': '+xx-xxx-xxx-xxxx', 'contact_instructions': 'During hours of service. Off on weekends.', 'contact_position': 'Position Title'}, 'repository': {'filter': 'is_published = true AND id IN (160, 113, 80, 85, 73, 30, 112, 55, 110, 116, 31, 117, 150, 129, 39, 38, 118, 56, 158, 98, 78, 32, 97, 265, 57, 22, 273, 81, 59, 42, 23, 72, 37, 33, 130, 95, 182, 94, 69, 102, 24, 96, 82, 26, 74, 34, 264, 70, 66, 35, 75, 83, 65, 173, 28, 58, 67, 46, 51, 36, 29, 60, 52, 62, 84, 255, 43, 174, 63, 41, 161, 124, 54, 64, 49, 257, 125, 25, 149, 272, 115, 27, 107, 263, 146, 126, 271, 50, 268, 269, 144, 127, 61, 143, 154, 270, 128, 145, 262, 44, 267, 48, 266, 47) AND alternate IS NOT NULL', 'source': 'geonode.catalogue.backends.pycsw_plugin.GeoNodeRepository', 'mappings': '/home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py'}, 'metadata:inspire': {'conformity_service': 'notEvaluated', 'contact_email': 'Email Address', 'languages_supported': 'eng,gre', 'date': 'YYYY-MM-DD', 'default_language': 'eng', 'contact_name': 'Organization Name', 'gemet_keywords': 'Utility and governmental services', 'enabled': 'true', 'temp_extent': 'YYYY-MM-DD/YYYY-MM-DD'}}
[Tue Jan 28 12:31:16.826413 2020] [wsgi:error] [pid 25329] Setting language
[Tue Jan 28 12:31:16.826833 2020] [wsgi:error] [pid 25329] Loading custom repository mappings from /home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py
[Tue Jan 28 12:31:16.826939 2020] [wsgi:error] [pid 25329] Loading outputschemas
[Tue Jan 28 12:31:16.827134 2020] [wsgi:error] [pid 25329] Setting MaxRecordDefault
[Tue Jan 28 12:31:16.827626 2020] [wsgi:error] [pid 25329] Querying repository with ids: 1738228e-99c1-11e9-a5ca-000c29291400
[Tue Jan 28 12:31:16.835077 2020] [wsgi:error] [pid 25329] Request processed
[Tue Jan 28 12:31:16.835132 2020] [wsgi:error] [pid 25329] Writing response.
[Tue Jan 28 12:31:16.903344 2020] [wsgi:error] [pid 25330] Loading user configuration
[Tue Jan 28 12:31:16.903737 2020] [wsgi:error] [pid 25330] running configuration {'server': {'maxrecords': '10', 'domaincounts': 'true', 'language': 'el', 'encoding': 'UTF-8', 'url': 'https://geoportal.ermis-f.eu/catalogue/csw', 'home': '.', 'pretty_print': 'true', 'profiles': 'apiso,ebrim', 'domainquerytype': 'range'}, 'metadata:main': {'identification_fees': 'None', 'provider_url': 'https://geoportal.ermis-f.eu/', 'identification_keywords': 'sdi, catalogue, discovery, metadata, GeoNode', 'contact_address': 'Mailing Address', 'identification_accessconstraints': 'None', 'contact_name': 'Lastname, Firstname', 'contact_stateorprovince': 'Administrative Area', 'contact_country': 'Country', 'contact_url': 'Contact URL', 'provider_name': 'Organization Name', 'contact_phone': '+xx-xxx-xxx-xxxx', 'contact_hours': 'Hours of Service', 'contact_role': 'pointOfContact', 'contact_email': 'Email Address', 'identification_title': 'GeoNode Catalogue', 'contact_postalcode': 'Zip or Postal Code', 'contact_city': 'City', 'identification_keywords_type': 'theme', 'identification_abstract': 'GeoNode is an open source platform that facilitates the creation, sharing, and collaborative use of geospatial data', 'contact_fax': '+xx-xxx-xxx-xxxx', 'contact_instructions': 'During hours of service. Off on weekends.', 'contact_position': 'Position Title'}, 'repository': {'filter': 'is_published = true AND id IN (160, 113, 80, 85, 73, 30, 112, 55, 110, 116, 31, 117, 150, 129, 39, 38, 118, 56, 158, 98, 78, 32, 97, 265, 57, 22, 273, 81, 59, 42, 23, 72, 37, 33, 130, 95, 182, 94, 69, 102, 24, 96, 82, 26, 74, 34, 264, 70, 66, 35, 75, 83, 65, 173, 28, 58, 67, 46, 51, 36, 29, 60, 52, 62, 84, 255, 43, 174, 63, 41, 161, 124, 54, 64, 49, 257, 125, 25, 149, 272, 115, 27, 107, 263, 146, 126, 271, 50, 268, 269, 144, 127, 61, 143, 154, 270, 128, 145, 262, 44, 267, 48, 266, 47) AND alternate IS NOT NULL', 'source': 'geonode.catalogue.backends.pycsw_plugin.GeoNodeRepository', 'mappings': '/home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py'}, 'metadata:inspire': {'conformity_service': 'notEvaluated', 'contact_email': 'Email Address', 'languages_supported': 'eng,gre', 'date': 'YYYY-MM-DD', 'default_language': 'eng', 'contact_name': 'Organization Name', 'gemet_keywords': 'Utility and governmental services', 'enabled': 'true', 'temp_extent': 'YYYY-MM-DD/YYYY-MM-DD'}}
[Tue Jan 28 12:31:16.903832 2020] [wsgi:error] [pid 25330] Setting language
[Tue Jan 28 12:31:16.904252 2020] [wsgi:error] [pid 25330] Loading custom repository mappings from /home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py
[Tue Jan 28 12:31:16.904356 2020] [wsgi:error] [pid 25330] Loading outputschemas
[Tue Jan 28 12:31:16.904549 2020] [wsgi:error] [pid 25330] Setting MaxRecordDefault
[Tue Jan 28 12:31:16.905356 2020] [wsgi:error] [pid 25330] Querying repository with ids: 1738228e-99c1-11e9-a5ca-000c29291400
[Tue Jan 28 12:31:16.919837 2020] [wsgi:error] [pid 25330] Request processed
[Tue Jan 28 12:31:16.919891 2020] [wsgi:error] [pid 25330] Writing response.
[Tue Jan 28 12:31:16.990730 2020] [wsgi:error] [pid 25329] Loading user configuration
[Tue Jan 28 12:31:16.991124 2020] [wsgi:error] [pid 25329] running configuration {'server': {'maxrecords': '10', 'domaincounts': 'true', 'language': 'el', 'encoding': 'UTF-8', 'url': 'https://geoportal.ermis-f.eu/catalogue/csw', 'home': '.', 'pretty_print': 'true', 'profiles': 'apiso,ebrim', 'domainquerytype': 'range'}, 'metadata:main': {'identification_fees': 'None', 'provider_url': 'https://geoportal.ermis-f.eu/', 'identification_keywords': 'sdi, catalogue, discovery, metadata, GeoNode', 'contact_address': 'Mailing Address', 'identification_accessconstraints': 'None', 'contact_name': 'Lastname, Firstname', 'contact_stateorprovince': 'Administrative Area', 'contact_country': 'Country', 'contact_url': 'Contact URL', 'provider_name': 'Organization Name', 'contact_phone': '+xx-xxx-xxx-xxxx', 'contact_hours': 'Hours of Service', 'contact_role': 'pointOfContact', 'contact_email': 'Email Address', 'identification_title': 'GeoNode Catalogue', 'contact_postalcode': 'Zip or Postal Code', 'contact_city': 'City', 'identification_keywords_type': 'theme', 'identification_abstract': 'GeoNode is an open source platform that facilitates the creation, sharing, and collaborative use of geospatial data', 'contact_fax': '+xx-xxx-xxx-xxxx', 'contact_instructions': 'During hours of service. Off on weekends.', 'contact_position': 'Position Title'}, 'repository': {'filter': 'is_published = true AND id IN (160, 113, 80, 85, 73, 30, 112, 55, 110, 116, 31, 117, 150, 129, 39, 38, 118, 56, 158, 98, 78, 32, 97, 265, 57, 22, 273, 81, 59, 42, 23, 72, 37, 33, 130, 95, 182, 94, 69, 102, 24, 96, 82, 26, 74, 34, 264, 70, 66, 35, 75, 83, 65, 173, 28, 58, 67, 46, 51, 36, 29, 60, 52, 62, 84, 255, 43, 174, 63, 41, 161, 124, 54, 64, 49, 257, 125, 25, 149, 272, 115, 27, 107, 263, 146, 126, 271, 50, 268, 269, 144, 127, 61, 143, 154, 270, 128, 145, 262, 44, 267, 48, 266, 47) AND alternate IS NOT NULL', 'source': 'geonode.catalogue.backends.pycsw_plugin.GeoNodeRepository', 'mappings': '/home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py'}, 'metadata:inspire': {'conformity_service': 'notEvaluated', 'contact_email': 'Email Address', 'languages_supported': 'eng,gre', 'date': 'YYYY-MM-DD', 'default_language': 'eng', 'contact_name': 'Organization Name', 'gemet_keywords': 'Utility and governmental services', 'enabled': 'true', 'temp_extent': 'YYYY-MM-DD/YYYY-MM-DD'}}
[Tue Jan 28 12:31:16.991219 2020] [wsgi:error] [pid 25329] Setting language
[Tue Jan 28 12:31:16.991638 2020] [wsgi:error] [pid 25329] Loading custom repository mappings from /home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py
[Tue Jan 28 12:31:16.991743 2020] [wsgi:error] [pid 25329] Loading outputschemas
[Tue Jan 28 12:31:16.991935 2020] [wsgi:error] [pid 25329] Setting MaxRecordDefault
[Tue Jan 28 12:31:16.992433 2020] [wsgi:error] [pid 25329] Querying repository with ids: 1738228e-99c1-11e9-a5ca-000c29291400
[Tue Jan 28 12:31:16.997828 2020] [wsgi:error] [pid 25329] Request processed
[Tue Jan 28 12:31:16.997883 2020] [wsgi:error] [pid 25329] Writing response.
[Tue Jan 28 12:31:17.024102 2020] [wsgi:error] [pid 25330] Loading user configuration
[Tue Jan 28 12:31:17.024670 2020] [wsgi:error] [pid 25330] running configuration <ConfigParser.SafeConfigParser instance at 0x7fd81ddd6440>
[Tue Jan 28 12:31:17.024765 2020] [wsgi:error] [pid 25330] Setting language
[Tue Jan 28 12:31:17.025191 2020] [wsgi:error] [pid 25330] Loading custom repository mappings from /home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py
[Tue Jan 28 12:31:17.025301 2020] [wsgi:error] [pid 25330] Loading outputschemas
[Tue Jan 28 12:31:17.025398 2020] [wsgi:error] [pid 25330] Setting MaxRecordDefault
[Tue Jan 28 12:31:17.025909 2020] [wsgi:error] [pid 25330] Querying repository with ids: 1738228e-99c1-11e9-a5ca-000c29291400
[Tue Jan 28 12:31:17.040054 2020] [wsgi:error] [pid 25330] Request processed
[Tue Jan 28 12:31:17.040113 2020] [wsgi:error] [pid 25330] Writing response.
[Tue Jan 28 12:31:17.042660 2020] [wsgi:error] [pid 25330] /home/geo/Envs/geonode/lib/python2.7/site-packages/owslib/iso.py:117: FutureWarning: the .identification and .serviceidentification properties will merge into .identification being a list of properties.  This is currently implemented in .identificationinfo.  Please see https://github.com/geopython/OWSLib/issues/38 for more information
[Tue Jan 28 12:31:17.042671 2020] [wsgi:error] [pid 25330]   FutureWarning)
[Tue Jan 28 12:31:17.043377 2020] [wsgi:error] [pid 25330] /home/geo/Envs/geonode/lib/python2.7/site-packages/owslib/iso.py:482: FutureWarning: The .keywords and .keywords2 properties will merge into the .keywords property in the future, with .keywords becoming a list of MD_Keywords instances. This is currently implemented in .keywords2. Please see https://github.com/geopython/OWSLib/issues/301 for more information
[Tue Jan 28 12:31:17.043383 2020] [wsgi:error] [pid 25330]   FutureWarning)
[Tue Jan 28 12:31:17.496088 2020] [wsgi:error] [pid 25329] Loading user configuration
[Tue Jan 28 12:31:17.496480 2020] [wsgi:error] [pid 25329] running configuration {'server': {'maxrecords': '10', 'domaincounts': 'true', 'language': 'el', 'encoding': 'UTF-8', 'url': 'https://geoportal.ermis-f.eu/catalogue/csw', 'home': '.', 'pretty_print': 'true', 'profiles': 'apiso,ebrim', 'domainquerytype': 'range'}, 'metadata:main': {'identification_fees': 'None', 'provider_url': 'https://geoportal.ermis-f.eu/', 'identification_keywords': 'sdi, catalogue, discovery, metadata, GeoNode', 'contact_address': 'Mailing Address', 'identification_accessconstraints': 'None', 'contact_name': 'Lastname, Firstname', 'contact_stateorprovince': 'Administrative Area', 'contact_country': 'Country', 'contact_url': 'Contact URL', 'provider_name': 'Organization Name', 'contact_phone': '+xx-xxx-xxx-xxxx', 'contact_hours': 'Hours of Service', 'contact_role': 'pointOfContact', 'contact_email': 'Email Address', 'identification_title': 'GeoNode Catalogue', 'contact_postalcode': 'Zip or Postal Code', 'contact_city': 'City', 'identification_keywords_type': 'theme', 'identification_abstract': 'GeoNode is an open source platform that facilitates the creation, sharing, and collaborative use of geospatial data', 'contact_fax': '+xx-xxx-xxx-xxxx', 'contact_instructions': 'During hours of service. Off on weekends.', 'contact_position': 'Position Title'}, 'repository': {'filter': 'is_published = true AND id IN (160, 113, 80, 85, 73, 30, 112, 55, 110, 116, 31, 117, 150, 129, 39, 38, 118, 56, 158, 98, 78, 32, 97, 265, 57, 22, 273, 81, 59, 42, 23, 72, 37, 33, 130, 95, 182, 94, 69, 102, 24, 96, 82, 26, 74, 34, 264, 70, 66, 35, 75, 83, 65, 173, 28, 58, 67, 46, 51, 36, 29, 60, 52, 62, 84, 255, 43, 174, 63, 41, 161, 124, 54, 64, 49, 257, 125, 25, 149, 272, 115, 27, 107, 263, 146, 126, 271, 50, 268, 269, 144, 127, 61, 143, 154, 270, 128, 145, 262, 44, 267, 48, 266, 47) AND alternate IS NOT NULL', 'source': 'geonode.catalogue.backends.pycsw_plugin.GeoNodeRepository', 'mappings': '/home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py'}, 'metadata:inspire': {'conformity_service': 'notEvaluated', 'contact_email': 'Email Address', 'languages_supported': 'eng,gre', 'date': 'YYYY-MM-DD', 'default_language': 'eng', 'contact_name': 'Organization Name', 'gemet_keywords': 'Utility and governmental services', 'enabled': 'true', 'temp_extent': 'YYYY-MM-DD/YYYY-MM-DD'}}
[Tue Jan 28 12:31:17.496586 2020] [wsgi:error] [pid 25329] Setting language
[Tue Jan 28 12:31:17.497014 2020] [wsgi:error] [pid 25329] Loading custom repository mappings from /home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py
[Tue Jan 28 12:31:17.497122 2020] [wsgi:error] [pid 25329] Loading outputschemas
[Tue Jan 28 12:31:17.497315 2020] [wsgi:error] [pid 25329] Setting MaxRecordDefault
[Tue Jan 28 12:31:17.497842 2020] [wsgi:error] [pid 25329] Querying repository with ids: 1738228e-99c1-11e9-a5ca-000c29291400
[Tue Jan 28 12:31:17.510867 2020] [wsgi:error] [pid 25329] Request processed
[Tue Jan 28 12:31:17.510923 2020] [wsgi:error] [pid 25329] Writing response.
[Tue Jan 28 12:31:17.591908 2020] [wsgi:error] [pid 25330] Loading user configuration
[Tue Jan 28 12:31:17.592314 2020] [wsgi:error] [pid 25330] running configuration {'server': {'maxrecords': '10', 'domaincounts': 'true', 'language': 'el', 'encoding': 'UTF-8', 'url': 'https://geoportal.ermis-f.eu/catalogue/csw', 'home': '.', 'pretty_print': 'true', 'profiles': 'apiso,ebrim', 'domainquerytype': 'range'}, 'metadata:main': {'identification_fees': 'None', 'provider_url': 'https://geoportal.ermis-f.eu/', 'identification_keywords': 'sdi, catalogue, discovery, metadata, GeoNode', 'contact_address': 'Mailing Address', 'identification_accessconstraints': 'None', 'contact_name': 'Lastname, Firstname', 'contact_stateorprovince': 'Administrative Area', 'contact_country': 'Country', 'contact_url': 'Contact URL', 'provider_name': 'Organization Name', 'contact_phone': '+xx-xxx-xxx-xxxx', 'contact_hours': 'Hours of Service', 'contact_role': 'pointOfContact', 'contact_email': 'Email Address', 'identification_title': 'GeoNode Catalogue', 'contact_postalcode': 'Zip or Postal Code', 'contact_city': 'City', 'identification_keywords_type': 'theme', 'identification_abstract': 'GeoNode is an open source platform that facilitates the creation, sharing, and collaborative use of geospatial data', 'contact_fax': '+xx-xxx-xxx-xxxx', 'contact_instructions': 'During hours of service. Off on weekends.', 'contact_position': 'Position Title'}, 'repository': {'filter': 'is_published = true AND id IN (160, 113, 80, 85, 73, 30, 112, 55, 110, 116, 31, 117, 150, 129, 39, 38, 118, 56, 158, 98, 78, 32, 97, 265, 57, 22, 273, 81, 59, 42, 23, 72, 37, 33, 130, 95, 182, 94, 69, 102, 24, 96, 82, 26, 74, 34, 264, 70, 66, 35, 75, 83, 65, 173, 28, 58, 67, 46, 51, 36, 29, 60, 52, 62, 84, 255, 43, 174, 63, 41, 161, 124, 54, 64, 49, 257, 125, 25, 149, 272, 115, 27, 107, 263, 146, 126, 271, 50, 268, 269, 144, 127, 61, 143, 154, 270, 128, 145, 262, 44, 267, 48, 266, 47) AND alternate IS NOT NULL', 'source': 'geonode.catalogue.backends.pycsw_plugin.GeoNodeRepository', 'mappings': '/home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py'}, 'metadata:inspire': {'conformity_service': 'notEvaluated', 'contact_email': 'Email Address', 'languages_supported': 'eng,gre', 'date': 'YYYY-MM-DD', 'default_language': 'eng', 'contact_name': 'Organization Name', 'gemet_keywords': 'Utility and governmental services', 'enabled': 'true', 'temp_extent': 'YYYY-MM-DD/YYYY-MM-DD'}}
[Tue Jan 28 12:31:17.592410 2020] [wsgi:error] [pid 25330] Setting language
[Tue Jan 28 12:31:17.592843 2020] [wsgi:error] [pid 25330] Loading custom repository mappings from /home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py
[Tue Jan 28 12:31:17.592949 2020] [wsgi:error] [pid 25330] Loading outputschemas
[Tue Jan 28 12:31:17.593143 2020] [wsgi:error] [pid 25330] Setting MaxRecordDefault
[Tue Jan 28 12:31:17.593985 2020] [wsgi:error] [pid 25330] Querying repository with ids: 1738228e-99c1-11e9-a5ca-000c29291400
[Tue Jan 28 12:31:17.608692 2020] [wsgi:error] [pid 25330] Request processed
[Tue Jan 28 12:31:17.608745 2020] [wsgi:error] [pid 25330] Writing response.
[Tue Jan 28 12:31:17.677283 2020] [wsgi:error] [pid 25329] Loading user configuration
[Tue Jan 28 12:31:17.677688 2020] [wsgi:error] [pid 25329] running configuration {'server': {'maxrecords': '10', 'domaincounts': 'true', 'language': 'el', 'encoding': 'UTF-8', 'url': 'https://geoportal.ermis-f.eu/catalogue/csw', 'home': '.', 'pretty_print': 'true', 'profiles': 'apiso,ebrim', 'domainquerytype': 'range'}, 'metadata:main': {'identification_fees': 'None', 'provider_url': 'https://geoportal.ermis-f.eu/', 'identification_keywords': 'sdi, catalogue, discovery, metadata, GeoNode', 'contact_address': 'Mailing Address', 'identification_accessconstraints': 'None', 'contact_name': 'Lastname, Firstname', 'contact_stateorprovince': 'Administrative Area', 'contact_country': 'Country', 'contact_url': 'Contact URL', 'provider_name': 'Organization Name', 'contact_phone': '+xx-xxx-xxx-xxxx', 'contact_hours': 'Hours of Service', 'contact_role': 'pointOfContact', 'contact_email': 'Email Address', 'identification_title': 'GeoNode Catalogue', 'contact_postalcode': 'Zip or Postal Code', 'contact_city': 'City', 'identification_keywords_type': 'theme', 'identification_abstract': 'GeoNode is an open source platform that facilitates the creation, sharing, and collaborative use of geospatial data', 'contact_fax': '+xx-xxx-xxx-xxxx', 'contact_instructions': 'During hours of service. Off on weekends.', 'contact_position': 'Position Title'}, 'repository': {'filter': 'is_published = true AND id IN (160, 113, 80, 85, 73, 30, 112, 55, 110, 116, 31, 117, 150, 129, 39, 38, 118, 56, 158, 98, 78, 32, 97, 265, 57, 22, 273, 81, 59, 42, 23, 72, 37, 33, 130, 95, 182, 94, 69, 102, 24, 96, 82, 26, 74, 34, 264, 70, 66, 35, 75, 83, 65, 173, 28, 58, 67, 46, 51, 36, 29, 60, 52, 62, 84, 255, 43, 174, 63, 41, 161, 124, 54, 64, 49, 257, 125, 25, 149, 272, 115, 27, 107, 263, 146, 126, 271, 50, 268, 269, 144, 127, 61, 143, 154, 270, 128, 145, 262, 44, 267, 48, 266, 47) AND alternate IS NOT NULL', 'source': 'geonode.catalogue.backends.pycsw_plugin.GeoNodeRepository', 'mappings': '/home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py'}, 'metadata:inspire': {'conformity_service': 'notEvaluated', 'contact_email': 'Email Address', 'languages_supported': 'eng,gre', 'date': 'YYYY-MM-DD', 'default_language': 'eng', 'contact_name': 'Organization Name', 'gemet_keywords': 'Utility and governmental services', 'enabled': 'true', 'temp_extent': 'YYYY-MM-DD/YYYY-MM-DD'}}
[Tue Jan 28 12:31:17.677789 2020] [wsgi:error] [pid 25329] Setting language
[Tue Jan 28 12:31:17.678206 2020] [wsgi:error] [pid 25329] Loading custom repository mappings from /home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py
[Tue Jan 28 12:31:17.678313 2020] [wsgi:error] [pid 25329] Loading outputschemas
[Tue Jan 28 12:31:17.678508 2020] [wsgi:error] [pid 25329] Setting MaxRecordDefault
[Tue Jan 28 12:31:17.679009 2020] [wsgi:error] [pid 25329] Querying repository with ids: 1738228e-99c1-11e9-a5ca-000c29291400
[Tue Jan 28 12:31:17.695495 2020] [wsgi:error] [pid 25329] Request processed
[Tue Jan 28 12:31:17.695552 2020] [wsgi:error] [pid 25329] Writing response.
[Tue Jan 28 12:31:17.764032 2020] [wsgi:error] [pid 25330] Loading user configuration
[Tue Jan 28 12:31:17.764420 2020] [wsgi:error] [pid 25330] running configuration {'server': {'maxrecords': '10', 'domaincounts': 'true', 'language': 'el', 'encoding': 'UTF-8', 'url': 'https://geoportal.ermis-f.eu/catalogue/csw', 'home': '.', 'pretty_print': 'true', 'profiles': 'apiso,ebrim', 'domainquerytype': 'range'}, 'metadata:main': {'identification_fees': 'None', 'provider_url': 'https://geoportal.ermis-f.eu/', 'identification_keywords': 'sdi, catalogue, discovery, metadata, GeoNode', 'contact_address': 'Mailing Address', 'identification_accessconstraints': 'None', 'contact_name': 'Lastname, Firstname', 'contact_stateorprovince': 'Administrative Area', 'contact_country': 'Country', 'contact_url': 'Contact URL', 'provider_name': 'Organization Name', 'contact_phone': '+xx-xxx-xxx-xxxx', 'contact_hours': 'Hours of Service', 'contact_role': 'pointOfContact', 'contact_email': 'Email Address', 'identification_title': 'GeoNode Catalogue', 'contact_postalcode': 'Zip or Postal Code', 'contact_city': 'City', 'identification_keywords_type': 'theme', 'identification_abstract': 'GeoNode is an open source platform that facilitates the creation, sharing, and collaborative use of geospatial data', 'contact_fax': '+xx-xxx-xxx-xxxx', 'contact_instructions': 'During hours of service. Off on weekends.', 'contact_position': 'Position Title'}, 'repository': {'filter': 'is_published = true AND id IN (160, 113, 80, 85, 73, 30, 112, 55, 110, 116, 31, 117, 150, 129, 39, 38, 118, 56, 158, 98, 78, 32, 97, 265, 57, 22, 273, 81, 59, 42, 23, 72, 37, 33, 130, 95, 182, 94, 69, 102, 24, 96, 82, 26, 74, 34, 264, 70, 66, 35, 75, 83, 65, 173, 28, 58, 67, 46, 51, 36, 29, 60, 52, 62, 84, 255, 43, 174, 63, 41, 161, 124, 54, 64, 49, 257, 125, 25, 149, 272, 115, 27, 107, 263, 146, 126, 271, 50, 268, 269, 144, 127, 61, 143, 154, 270, 128, 145, 262, 44, 267, 48, 266, 47) AND alternate IS NOT NULL', 'source': 'geonode.catalogue.backends.pycsw_plugin.GeoNodeRepository', 'mappings': '/home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py'}, 'metadata:inspire': {'conformity_service': 'notEvaluated', 'contact_email': 'Email Address', 'languages_supported': 'eng,gre', 'date': 'YYYY-MM-DD', 'default_language': 'eng', 'contact_name': 'Organization Name', 'gemet_keywords': 'Utility and governmental services', 'enabled': 'true', 'temp_extent': 'YYYY-MM-DD/YYYY-MM-DD'}}
[Tue Jan 28 12:31:17.764505 2020] [wsgi:error] [pid 25330] Setting language
[Tue Jan 28 12:31:17.764929 2020] [wsgi:error] [pid 25330] Loading custom repository mappings from /home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py
[Tue Jan 28 12:31:17.765038 2020] [wsgi:error] [pid 25330] Loading outputschemas
[Tue Jan 28 12:31:17.765235 2020] [wsgi:error] [pid 25330] Setting MaxRecordDefault
[Tue Jan 28 12:31:17.766096 2020] [wsgi:error] [pid 25330] Querying repository with ids: 1738228e-99c1-11e9-a5ca-000c29291400
[Tue Jan 28 12:31:17.772579 2020] [wsgi:error] [pid 25330] Request processed
[Tue Jan 28 12:31:17.772629 2020] [wsgi:error] [pid 25330] Writing response.
[Tue Jan 28 12:31:17.838706 2020] [wsgi:error] [pid 25329] Loading user configuration
[Tue Jan 28 12:31:17.839094 2020] [wsgi:error] [pid 25329] running configuration {'server': {'maxrecords': '10', 'domaincounts': 'true', 'language': 'el', 'encoding': 'UTF-8', 'url': 'https://geoportal.ermis-f.eu/catalogue/csw', 'home': '.', 'pretty_print': 'true', 'profiles': 'apiso,ebrim', 'domainquerytype': 'range'}, 'metadata:main': {'identification_fees': 'None', 'provider_url': 'https://geoportal.ermis-f.eu/', 'identification_keywords': 'sdi, catalogue, discovery, metadata, GeoNode', 'contact_address': 'Mailing Address', 'identification_accessconstraints': 'None', 'contact_name': 'Lastname, Firstname', 'contact_stateorprovince': 'Administrative Area', 'contact_country': 'Country', 'contact_url': 'Contact URL', 'provider_name': 'Organization Name', 'contact_phone': '+xx-xxx-xxx-xxxx', 'contact_hours': 'Hours of Service', 'contact_role': 'pointOfContact', 'contact_email': 'Email Address', 'identification_title': 'GeoNode Catalogue', 'contact_postalcode': 'Zip or Postal Code', 'contact_city': 'City', 'identification_keywords_type': 'theme', 'identification_abstract': 'GeoNode is an open source platform that facilitates the creation, sharing, and collaborative use of geospatial data', 'contact_fax': '+xx-xxx-xxx-xxxx', 'contact_instructions': 'During hours of service. Off on weekends.', 'contact_position': 'Position Title'}, 'repository': {'filter': 'is_published = true AND id IN (160, 113, 80, 85, 73, 30, 112, 55, 110, 116, 31, 117, 150, 129, 39, 38, 118, 56, 158, 98, 78, 32, 97, 265, 57, 22, 273, 81, 59, 42, 23, 72, 37, 33, 130, 95, 182, 94, 69, 102, 24, 96, 82, 26, 74, 34, 264, 70, 66, 35, 75, 83, 65, 173, 28, 58, 67, 46, 51, 36, 29, 60, 52, 62, 84, 255, 43, 174, 63, 41, 161, 124, 54, 64, 49, 257, 125, 25, 149, 272, 115, 27, 107, 263, 146, 126, 271, 50, 268, 269, 144, 127, 61, 143, 154, 270, 128, 145, 262, 44, 267, 48, 266, 47) AND alternate IS NOT NULL', 'source': 'geonode.catalogue.backends.pycsw_plugin.GeoNodeRepository', 'mappings': '/home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py'}, 'metadata:inspire': {'conformity_service': 'notEvaluated', 'contact_email': 'Email Address', 'languages_supported': 'eng,gre', 'date': 'YYYY-MM-DD', 'default_language': 'eng', 'contact_name': 'Organization Name', 'gemet_keywords': 'Utility and governmental services', 'enabled': 'true', 'temp_extent': 'YYYY-MM-DD/YYYY-MM-DD'}}
[Tue Jan 28 12:31:17.839189 2020] [wsgi:error] [pid 25329] Setting language
[Tue Jan 28 12:31:17.839603 2020] [wsgi:error] [pid 25329] Loading custom repository mappings from /home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py
[Tue Jan 28 12:31:17.839711 2020] [wsgi:error] [pid 25329] Loading outputschemas
[Tue Jan 28 12:31:17.839901 2020] [wsgi:error] [pid 25329] Setting MaxRecordDefault
[Tue Jan 28 12:31:17.840464 2020] [wsgi:error] [pid 25329] Querying repository with ids: 1738228e-99c1-11e9-a5ca-000c29291400
[Tue Jan 28 12:31:17.855291 2020] [wsgi:error] [pid 25329] Request processed
[Tue Jan 28 12:31:17.855347 2020] [wsgi:error] [pid 25329] Writing response.
[Tue Jan 28 12:31:17.921657 2020] [wsgi:error] [pid 25330] Loading user configuration
[Tue Jan 28 12:31:17.922067 2020] [wsgi:error] [pid 25330] running configuration {'server': {'maxrecords': '10', 'domaincounts': 'true', 'language': 'el', 'encoding': 'UTF-8', 'url': 'https://geoportal.ermis-f.eu/catalogue/csw', 'home': '.', 'pretty_print': 'true', 'profiles': 'apiso,ebrim', 'domainquerytype': 'range'}, 'metadata:main': {'identification_fees': 'None', 'provider_url': 'https://geoportal.ermis-f.eu/', 'identification_keywords': 'sdi, catalogue, discovery, metadata, GeoNode', 'contact_address': 'Mailing Address', 'identification_accessconstraints': 'None', 'contact_name': 'Lastname, Firstname', 'contact_stateorprovince': 'Administrative Area', 'contact_country': 'Country', 'contact_url': 'Contact URL', 'provider_name': 'Organization Name', 'contact_phone': '+xx-xxx-xxx-xxxx', 'contact_hours': 'Hours of Service', 'contact_role': 'pointOfContact', 'contact_email': 'Email Address', 'identification_title': 'GeoNode Catalogue', 'contact_postalcode': 'Zip or Postal Code', 'contact_city': 'City', 'identification_keywords_type': 'theme', 'identification_abstract': 'GeoNode is an open source platform that facilitates the creation, sharing, and collaborative use of geospatial data', 'contact_fax': '+xx-xxx-xxx-xxxx', 'contact_instructions': 'During hours of service. Off on weekends.', 'contact_position': 'Position Title'}, 'repository': {'filter': 'is_published = true AND id IN (160, 113, 80, 85, 73, 30, 112, 55, 110, 116, 31, 117, 150, 129, 39, 38, 118, 56, 158, 98, 78, 32, 97, 265, 57, 22, 273, 81, 59, 42, 23, 72, 37, 33, 130, 95, 182, 94, 69, 102, 24, 96, 82, 26, 74, 34, 264, 70, 66, 35, 75, 83, 65, 173, 28, 58, 67, 46, 51, 36, 29, 60, 52, 62, 84, 255, 43, 174, 63, 41, 161, 124, 54, 64, 49, 257, 125, 25, 149, 272, 115, 27, 107, 263, 146, 126, 271, 50, 268, 269, 144, 127, 61, 143, 154, 270, 128, 145, 262, 44, 267, 48, 266, 47) AND alternate IS NOT NULL', 'source': 'geonode.catalogue.backends.pycsw_plugin.GeoNodeRepository', 'mappings': '/home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py'}, 'metadata:inspire': {'conformity_service': 'notEvaluated', 'contact_email': 'Email Address', 'languages_supported': 'eng,gre', 'date': 'YYYY-MM-DD', 'default_language': 'eng', 'contact_name': 'Organization Name', 'gemet_keywords': 'Utility and governmental services', 'enabled': 'true', 'temp_extent': 'YYYY-MM-DD/YYYY-MM-DD'}}
[Tue Jan 28 12:31:17.922165 2020] [wsgi:error] [pid 25330] Setting language
[Tue Jan 28 12:31:17.922584 2020] [wsgi:error] [pid 25330] Loading custom repository mappings from /home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py
[Tue Jan 28 12:31:17.922690 2020] [wsgi:error] [pid 25330] Loading outputschemas
[Tue Jan 28 12:31:17.922883 2020] [wsgi:error] [pid 25330] Setting MaxRecordDefault
[Tue Jan 28 12:31:17.923683 2020] [wsgi:error] [pid 25330] Querying repository with ids: 1738228e-99c1-11e9-a5ca-000c29291400
[Tue Jan 28 12:31:17.928517 2020] [wsgi:error] [pid 25330] Request processed
[Tue Jan 28 12:31:17.928570 2020] [wsgi:error] [pid 25330] Writing response.
[Tue Jan 28 12:31:17.952932 2020] [wsgi:error] [pid 25329] Loading user configuration
[Tue Jan 28 12:31:17.953424 2020] [wsgi:error] [pid 25329] running configuration <ConfigParser.SafeConfigParser instance at 0x7fd81db37128>
[Tue Jan 28 12:31:17.953511 2020] [wsgi:error] [pid 25329] Setting language
[Tue Jan 28 12:31:17.953973 2020] [wsgi:error] [pid 25329] Loading custom repository mappings from /home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py
[Tue Jan 28 12:31:17.954087 2020] [wsgi:error] [pid 25329] Loading outputschemas
[Tue Jan 28 12:31:17.954185 2020] [wsgi:error] [pid 25329] Setting MaxRecordDefault
[Tue Jan 28 12:31:17.954675 2020] [wsgi:error] [pid 25329] Querying repository with ids: 1738228e-99c1-11e9-a5ca-000c29291400
[Tue Jan 28 12:31:17.968743 2020] [wsgi:error] [pid 25329] Request processed
[Tue Jan 28 12:31:17.968801 2020] [wsgi:error] [pid 25329] Writing response.
[Tue Jan 28 12:31:53.174397 2020] [wsgi:error] [pid 25329] Loading user configuration
[Tue Jan 28 12:31:53.174806 2020] [wsgi:error] [pid 25329] running configuration {'server': {'maxrecords': '10', 'domaincounts': 'true', 'language': 'el', 'encoding': 'UTF-8', 'url': 'https://geoportal.ermis-f.eu/catalogue/csw', 'home': '.', 'pretty_print': 'true', 'profiles': 'apiso,ebrim', 'domainquerytype': 'range'}, 'metadata:main': {'identification_fees': 'None', 'provider_url': 'https://geoportal.ermis-f.eu/', 'identification_keywords': 'sdi, catalogue, discovery, metadata, GeoNode', 'contact_address': 'Mailing Address', 'identification_accessconstraints': 'None', 'contact_name': 'Lastname, Firstname', 'contact_stateorprovince': 'Administrative Area', 'contact_country': 'Country', 'contact_url': 'Contact URL', 'provider_name': 'Organization Name', 'contact_phone': '+xx-xxx-xxx-xxxx', 'contact_hours': 'Hours of Service', 'contact_role': 'pointOfContact', 'contact_email': 'Email Address', 'identification_title': 'GeoNode Catalogue', 'contact_postalcode': 'Zip or Postal Code', 'contact_city': 'City', 'identification_keywords_type': 'theme', 'identification_abstract': 'GeoNode is an open source platform that facilitates the creation, sharing, and collaborative use of geospatial data', 'contact_fax': '+xx-xxx-xxx-xxxx', 'contact_instructions': 'During hours of service. Off on weekends.', 'contact_position': 'Position Title'}, 'repository': {'filter': 'is_published = true AND id IN (160, 113, 80, 85, 73, 30, 112, 55, 110, 116, 31, 117, 150, 129, 39, 38, 118, 56, 158, 98, 78, 32, 97, 265, 57, 22, 273, 81, 59, 42, 23, 72, 37, 33, 130, 95, 182, 94, 69, 102, 24, 96, 82, 26, 74, 34, 264, 70, 66, 35, 75, 83, 65, 173, 28, 58, 67, 46, 51, 36, 29, 60, 52, 62, 84, 255, 43, 174, 63, 41, 161, 124, 54, 64, 49, 257, 125, 25, 149, 272, 115, 27, 107, 263, 146, 126, 271, 50, 268, 269, 144, 127, 61, 143, 154, 270, 128, 145, 262, 44, 267, 48, 266, 47) AND alternate IS NOT NULL', 'source': 'geonode.catalogue.backends.pycsw_plugin.GeoNodeRepository', 'mappings': '/home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py'}, 'metadata:inspire': {'conformity_service': 'notEvaluated', 'contact_email': 'Email Address', 'languages_supported': 'eng,gre', 'date': 'YYYY-MM-DD', 'default_language': 'eng', 'contact_name': 'Organization Name', 'gemet_keywords': 'Utility and governmental services', 'enabled': 'true', 'temp_extent': 'YYYY-MM-DD/YYYY-MM-DD'}}
[Tue Jan 28 12:31:53.174903 2020] [wsgi:error] [pid 25329] Setting language
[Tue Jan 28 12:31:53.175356 2020] [wsgi:error] [pid 25329] Loading custom repository mappings from /home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py
[Tue Jan 28 12:31:53.175466 2020] [wsgi:error] [pid 25329] Loading outputschemas
[Tue Jan 28 12:31:53.175663 2020] [wsgi:error] [pid 25329] Setting MaxRecordDefault
[Tue Jan 28 12:31:53.176181 2020] [wsgi:error] [pid 25329] Querying repository with ids: a5061fde-b9ca-11e9-a5ca-000c29291400
[Tue Jan 28 12:31:53.180958 2020] [wsgi:error] [pid 25329] Request processed
[Tue Jan 28 12:31:53.181013 2020] [wsgi:error] [pid 25329] Writing response.
[Tue Jan 28 12:42:04.828487 2020] [wsgi:error] [pid 25329] Loading user configuration
[Tue Jan 28 12:42:04.829151 2020] [wsgi:error] [pid 25329] running configuration {'server': {'maxrecords': '10', 'domaincounts': 'true', 'language': 'el', 'encoding': 'UTF-8', 'url': 'https://geoportal.ermis-f.eu/catalogue/csw', 'home': '.', 'pretty_print': 'true', 'profiles': 'apiso,ebrim', 'domainquerytype': 'range'}, 'metadata:main': {'identification_fees': 'None', 'provider_url': 'https://geoportal.ermis-f.eu/', 'identification_keywords': 'sdi, catalogue, discovery, metadata, GeoNode', 'contact_address': 'Mailing Address', 'identification_accessconstraints': 'None', 'contact_name': 'Lastname, Firstname', 'contact_stateorprovince': 'Administrative Area', 'contact_country': 'Country', 'contact_url': 'Contact URL', 'provider_name': 'Organization Name', 'contact_phone': '+xx-xxx-xxx-xxxx', 'contact_hours': 'Hours of Service', 'contact_role': 'pointOfContact', 'contact_email': 'Email Address', 'identification_title': 'GeoNode Catalogue', 'contact_postalcode': 'Zip or Postal Code', 'contact_city': 'City', 'identification_keywords_type': 'theme', 'identification_abstract': 'GeoNode is an open source platform that facilitates the creation, sharing, and collaborative use of geospatial data', 'contact_fax': '+xx-xxx-xxx-xxxx', 'contact_instructions': 'During hours of service. Off on weekends.', 'contact_position': 'Position Title'}, 'repository': {'filter': 'is_published = true AND id IN (160, 113, 80, 85, 73, 30, 112, 55, 110, 116, 31, 117, 150, 129, 39, 38, 118, 56, 158, 98, 78, 32, 97, 265, 57, 22, 273, 81, 59, 42, 23, 72, 37, 33, 130, 95, 182, 94, 69, 102, 24, 96, 82, 26, 74, 34, 264, 70, 66, 35, 75, 83, 65, 173, 28, 58, 67, 46, 51, 36, 29, 60, 52, 62, 84, 255, 43, 174, 63, 41, 161, 124, 54, 64, 49, 257, 125, 25, 149, 272, 115, 27, 107, 263, 146, 126, 271, 50, 268, 269, 144, 127, 61, 143, 154, 270, 128, 145, 262, 44, 267, 48, 266, 47) AND alternate IS NOT NULL', 'source': 'geonode.catalogue.backends.pycsw_plugin.GeoNodeRepository', 'mappings': '/home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py'}, 'metadata:inspire': {'conformity_service': 'notEvaluated', 'contact_email': 'Email Address', 'languages_supported': 'eng,gre', 'date': 'YYYY-MM-DD', 'default_language': 'eng', 'contact_name': 'Organization Name', 'gemet_keywords': 'Utility and governmental services', 'enabled': 'true', 'temp_extent': 'YYYY-MM-DD/YYYY-MM-DD'}}
[Tue Jan 28 12:42:04.829297 2020] [wsgi:error] [pid 25329] Setting language
[Tue Jan 28 12:42:04.829991 2020] [wsgi:error] [pid 25329] Loading custom repository mappings from /home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py
[Tue Jan 28 12:42:04.830168 2020] [wsgi:error] [pid 25329] Loading outputschemas
[Tue Jan 28 12:42:04.830473 2020] [wsgi:error] [pid 25329] Setting MaxRecordDefault
[Tue Jan 28 12:42:04.831287 2020] [wsgi:error] [pid 25329] Querying repository with ids: 3110a1ec-f8ba-11e9-a5ca-000c29291400
[Tue Jan 28 12:42:04.839926 2020] [wsgi:error] [pid 25329] Request processed
[Tue Jan 28 12:42:04.839998 2020] [wsgi:error] [pid 25329] Writing response.
[Tue Jan 28 12:56:51.683771 2020] [wsgi:error] [pid 25330] Traceback (most recent call last):
[Tue Jan 28 12:56:51.683811 2020] [wsgi:error] [pid 25330]   File "/home/geo/Envs/geonode/src/geonode/geonode/proxy/views.py", line 266, in download
[Tue Jan 28 12:56:51.683939 2020] [wsgi:error] [pid 25330]     sld_file.write(s.sld_body.strip())
[Tue Jan 28 12:56:51.683964 2020] [wsgi:error] [pid 25330] UnicodeEncodeError: 'ascii' codec can't encode characters in position 523-527: ordinal not in range(128)
[Tue Jan 28 12:56:51.845390 2020] [wsgi:error] [pid 25329] Loading user configuration
[Tue Jan 28 12:56:51.845819 2020] [wsgi:error] [pid 25329] running configuration {'server': {'maxrecords': '10', 'domaincounts': 'true', 'language': 'el', 'encoding': 'UTF-8', 'url': 'https://geoportal.ermis-f.eu/catalogue/csw', 'home': '.', 'pretty_print': 'true', 'profiles': 'apiso,ebrim', 'domainquerytype': 'range'}, 'metadata:main': {'identification_fees': 'None', 'provider_url': 'https://geoportal.ermis-f.eu/', 'identification_keywords': 'sdi, catalogue, discovery, metadata, GeoNode', 'contact_address': 'Mailing Address', 'identification_accessconstraints': 'None', 'contact_name': 'Lastname, Firstname', 'contact_stateorprovince': 'Administrative Area', 'contact_country': 'Country', 'contact_url': 'Contact URL', 'provider_name': 'Organization Name', 'contact_phone': '+xx-xxx-xxx-xxxx', 'contact_hours': 'Hours of Service', 'contact_role': 'pointOfContact', 'contact_email': 'Email Address', 'identification_title': 'GeoNode Catalogue', 'contact_postalcode': 'Zip or Postal Code', 'contact_city': 'City', 'identification_keywords_type': 'theme', 'identification_abstract': 'GeoNode is an open source platform that facilitates the creation, sharing, and collaborative use of geospatial data', 'contact_fax': '+xx-xxx-xxx-xxxx', 'contact_instructions': 'During hours of service. Off on weekends.', 'contact_position': 'Position Title'}, 'repository': {'filter': 'is_published = true AND id IN (160, 113, 80, 85, 73, 30, 112, 55, 110, 116, 31, 117, 150, 129, 39, 38, 118, 56, 158, 98, 78, 32, 97, 265, 57, 22, 273, 81, 59, 42, 23, 72, 37, 33, 130, 95, 182, 94, 69, 102, 24, 96, 82, 26, 74, 34, 264, 70, 66, 35, 75, 83, 65, 173, 28, 58, 67, 46, 51, 36, 29, 60, 52, 62, 84, 255, 43, 174, 63, 41, 161, 124, 54, 64, 49, 257, 125, 25, 149, 272, 115, 27, 107, 263, 146, 126, 271, 50, 268, 269, 144, 127, 61, 143, 154, 270, 128, 145, 262, 44, 267, 48, 266, 47) AND alternate IS NOT NULL', 'source': 'geonode.catalogue.backends.pycsw_plugin.GeoNodeRepository', 'mappings': '/home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py'}, 'metadata:inspire': {'conformity_service': 'notEvaluated', 'contact_email': 'Email Address', 'languages_supported': 'eng,gre', 'date': 'YYYY-MM-DD', 'default_language': 'eng', 'contact_name': 'Organization Name', 'gemet_keywords': 'Utility and governmental services', 'enabled': 'true', 'temp_extent': 'YYYY-MM-DD/YYYY-MM-DD'}}
[Tue Jan 28 12:56:51.845920 2020] [wsgi:error] [pid 25329] Setting language
[Tue Jan 28 12:56:51.846400 2020] [wsgi:error] [pid 25329] Loading custom repository mappings from /home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py
[Tue Jan 28 12:56:51.846510 2020] [wsgi:error] [pid 25329] Loading outputschemas
[Tue Jan 28 12:56:51.846709 2020] [wsgi:error] [pid 25329] Setting MaxRecordDefault
[Tue Jan 28 12:56:51.847220 2020] [wsgi:error] [pid 25329] Querying repository with ids: 275ae2b4-99b7-11e9-a5ca-000c29291400
[Tue Jan 28 12:56:51.861840 2020] [wsgi:error] [pid 25329] Request processed
[Tue Jan 28 12:56:51.861896 2020] [wsgi:error] [pid 25329] Writing response.
[Tue Jan 28 12:56:51.947947 2020] [wsgi:error] [pid 25330] Loading user configuration
[Tue Jan 28 12:56:51.948590 2020] [wsgi:error] [pid 25330] running configuration {'server': {'maxrecords': '10', 'domaincounts': 'true', 'language': 'el', 'encoding': 'UTF-8', 'url': 'https://geoportal.ermis-f.eu/catalogue/csw', 'home': '.', 'pretty_print': 'true', 'profiles': 'apiso,ebrim', 'domainquerytype': 'range'}, 'metadata:main': {'identification_fees': 'None', 'provider_url': 'https://geoportal.ermis-f.eu/', 'identification_keywords': 'sdi, catalogue, discovery, metadata, GeoNode', 'contact_address': 'Mailing Address', 'identification_accessconstraints': 'None', 'contact_name': 'Lastname, Firstname', 'contact_stateorprovince': 'Administrative Area', 'contact_country': 'Country', 'contact_url': 'Contact URL', 'provider_name': 'Organization Name', 'contact_phone': '+xx-xxx-xxx-xxxx', 'contact_hours': 'Hours of Service', 'contact_role': 'pointOfContact', 'contact_email': 'Email Address', 'identification_title': 'GeoNode Catalogue', 'contact_postalcode': 'Zip or Postal Code', 'contact_city': 'City', 'identification_keywords_type': 'theme', 'identification_abstract': 'GeoNode is an open source platform that facilitates the creation, sharing, and collaborative use of geospatial data', 'contact_fax': '+xx-xxx-xxx-xxxx', 'contact_instructions': 'During hours of service. Off on weekends.', 'contact_position': 'Position Title'}, 'repository': {'filter': 'is_published = true AND id IN (160, 113, 80, 85, 73, 30, 112, 55, 110, 116, 31, 117, 150, 129, 39, 38, 118, 56, 158, 98, 78, 32, 97, 265, 57, 22, 273, 81, 59, 42, 23, 72, 37, 33, 130, 95, 182, 94, 69, 102, 24, 96, 82, 26, 74, 34, 264, 70, 66, 35, 75, 83, 65, 173, 28, 58, 67, 46, 51, 36, 29, 60, 52, 62, 84, 255, 43, 174, 63, 41, 161, 124, 54, 64, 49, 257, 125, 25, 149, 272, 115, 27, 107, 263, 146, 126, 271, 50, 268, 269, 144, 127, 61, 143, 154, 270, 128, 145, 262, 44, 267, 48, 266, 47) AND alternate IS NOT NULL', 'source': 'geonode.catalogue.backends.pycsw_plugin.GeoNodeRepository', 'mappings': '/home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py'}, 'metadata:inspire': {'conformity_service': 'notEvaluated', 'contact_email': 'Email Address', 'languages_supported': 'eng,gre', 'date': 'YYYY-MM-DD', 'default_language': 'eng', 'contact_name': 'Organization Name', 'gemet_keywords': 'Utility and governmental services', 'enabled': 'true', 'temp_extent': 'YYYY-MM-DD/YYYY-MM-DD'}}
[Tue Jan 28 12:56:51.948725 2020] [wsgi:error] [pid 25330] Setting language
[Tue Jan 28 12:56:51.949362 2020] [wsgi:error] [pid 25330] Loading custom repository mappings from /home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py
[Tue Jan 28 12:56:51.949533 2020] [wsgi:error] [pid 25330] Loading outputschemas
[Tue Jan 28 12:56:51.949847 2020] [wsgi:error] [pid 25330] Setting MaxRecordDefault
[Tue Jan 28 12:56:51.951062 2020] [wsgi:error] [pid 25330] Querying repository with ids: 275ae2b4-99b7-11e9-a5ca-000c29291400
[Tue Jan 28 12:56:51.972318 2020] [wsgi:error] [pid 25330] Request processed
[Tue Jan 28 12:56:51.972392 2020] [wsgi:error] [pid 25330] Writing response.
[Tue Jan 28 12:56:52.042800 2020] [wsgi:error] [pid 25329] Loading user configuration
[Tue Jan 28 12:56:52.043191 2020] [wsgi:error] [pid 25329] running configuration {'server': {'maxrecords': '10', 'domaincounts': 'true', 'language': 'el', 'encoding': 'UTF-8', 'url': 'https://geoportal.ermis-f.eu/catalogue/csw', 'home': '.', 'pretty_print': 'true', 'profiles': 'apiso,ebrim', 'domainquerytype': 'range'}, 'metadata:main': {'identification_fees': 'None', 'provider_url': 'https://geoportal.ermis-f.eu/', 'identification_keywords': 'sdi, catalogue, discovery, metadata, GeoNode', 'contact_address': 'Mailing Address', 'identification_accessconstraints': 'None', 'contact_name': 'Lastname, Firstname', 'contact_stateorprovince': 'Administrative Area', 'contact_country': 'Country', 'contact_url': 'Contact URL', 'provider_name': 'Organization Name', 'contact_phone': '+xx-xxx-xxx-xxxx', 'contact_hours': 'Hours of Service', 'contact_role': 'pointOfContact', 'contact_email': 'Email Address', 'identification_title': 'GeoNode Catalogue', 'contact_postalcode': 'Zip or Postal Code', 'contact_city': 'City', 'identification_keywords_type': 'theme', 'identification_abstract': 'GeoNode is an open source platform that facilitates the creation, sharing, and collaborative use of geospatial data', 'contact_fax': '+xx-xxx-xxx-xxxx', 'contact_instructions': 'During hours of service. Off on weekends.', 'contact_position': 'Position Title'}, 'repository': {'filter': 'is_published = true AND id IN (160, 113, 80, 85, 73, 30, 112, 55, 110, 116, 31, 117, 150, 129, 39, 38, 118, 56, 158, 98, 78, 32, 97, 265, 57, 22, 273, 81, 59, 42, 23, 72, 37, 33, 130, 95, 182, 94, 69, 102, 24, 96, 82, 26, 74, 34, 264, 70, 66, 35, 75, 83, 65, 173, 28, 58, 67, 46, 51, 36, 29, 60, 52, 62, 84, 255, 43, 174, 63, 41, 161, 124, 54, 64, 49, 257, 125, 25, 149, 272, 115, 27, 107, 263, 146, 126, 271, 50, 268, 269, 144, 127, 61, 143, 154, 270, 128, 145, 262, 44, 267, 48, 266, 47) AND alternate IS NOT NULL', 'source': 'geonode.catalogue.backends.pycsw_plugin.GeoNodeRepository', 'mappings': '/home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py'}, 'metadata:inspire': {'conformity_service': 'notEvaluated', 'contact_email': 'Email Address', 'languages_supported': 'eng,gre', 'date': 'YYYY-MM-DD', 'default_language': 'eng', 'contact_name': 'Organization Name', 'gemet_keywords': 'Utility and governmental services', 'enabled': 'true', 'temp_extent': 'YYYY-MM-DD/YYYY-MM-DD'}}
[Tue Jan 28 12:56:52.043286 2020] [wsgi:error] [pid 25329] Setting language
[Tue Jan 28 12:56:52.044204 2020] [wsgi:error] [pid 25329] Loading custom repository mappings from /home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py
[Tue Jan 28 12:56:52.044325 2020] [wsgi:error] [pid 25329] Loading outputschemas
[Tue Jan 28 12:56:52.044524 2020] [wsgi:error] [pid 25329] Setting MaxRecordDefault
[Tue Jan 28 12:56:52.045357 2020] [wsgi:error] [pid 25329] Querying repository with ids: 275ae2b4-99b7-11e9-a5ca-000c29291400
[Tue Jan 28 12:56:52.062629 2020] [wsgi:error] [pid 25329] Request processed
[Tue Jan 28 12:56:52.062687 2020] [wsgi:error] [pid 25329] Writing response.
[Tue Jan 28 12:56:52.132825 2020] [wsgi:error] [pid 25330] Loading user configuration
[Tue Jan 28 12:56:52.133218 2020] [wsgi:error] [pid 25330] running configuration {'server': {'maxrecords': '10', 'domaincounts': 'true', 'language': 'el', 'encoding': 'UTF-8', 'url': 'https://geoportal.ermis-f.eu/catalogue/csw', 'home': '.', 'pretty_print': 'true', 'profiles': 'apiso,ebrim', 'domainquerytype': 'range'}, 'metadata:main': {'identification_fees': 'None', 'provider_url': 'https://geoportal.ermis-f.eu/', 'identification_keywords': 'sdi, catalogue, discovery, metadata, GeoNode', 'contact_address': 'Mailing Address', 'identification_accessconstraints': 'None', 'contact_name': 'Lastname, Firstname', 'contact_stateorprovince': 'Administrative Area', 'contact_country': 'Country', 'contact_url': 'Contact URL', 'provider_name': 'Organization Name', 'contact_phone': '+xx-xxx-xxx-xxxx', 'contact_hours': 'Hours of Service', 'contact_role': 'pointOfContact', 'contact_email': 'Email Address', 'identification_title': 'GeoNode Catalogue', 'contact_postalcode': 'Zip or Postal Code', 'contact_city': 'City', 'identification_keywords_type': 'theme', 'identification_abstract': 'GeoNode is an open source platform that facilitates the creation, sharing, and collaborative use of geospatial data', 'contact_fax': '+xx-xxx-xxx-xxxx', 'contact_instructions': 'During hours of service. Off on weekends.', 'contact_position': 'Position Title'}, 'repository': {'filter': 'is_published = true AND id IN (160, 113, 80, 85, 73, 30, 112, 55, 110, 116, 31, 117, 150, 129, 39, 38, 118, 56, 158, 98, 78, 32, 97, 265, 57, 22, 273, 81, 59, 42, 23, 72, 37, 33, 130, 95, 182, 94, 69, 102, 24, 96, 82, 26, 74, 34, 264, 70, 66, 35, 75, 83, 65, 173, 28, 58, 67, 46, 51, 36, 29, 60, 52, 62, 84, 255, 43, 174, 63, 41, 161, 124, 54, 64, 49, 257, 125, 25, 149, 272, 115, 27, 107, 263, 146, 126, 271, 50, 268, 269, 144, 127, 61, 143, 154, 270, 128, 145, 262, 44, 267, 48, 266, 47) AND alternate IS NOT NULL', 'source': 'geonode.catalogue.backends.pycsw_plugin.GeoNodeRepository', 'mappings': '/home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py'}, 'metadata:inspire': {'conformity_service': 'notEvaluated', 'contact_email': 'Email Address', 'languages_supported': 'eng,gre', 'date': 'YYYY-MM-DD', 'default_language': 'eng', 'contact_name': 'Organization Name', 'gemet_keywords': 'Utility and governmental services', 'enabled': 'true', 'temp_extent': 'YYYY-MM-DD/YYYY-MM-DD'}}
[Tue Jan 28 12:56:52.133316 2020] [wsgi:error] [pid 25330] Setting language
[Tue Jan 28 12:56:52.133760 2020] [wsgi:error] [pid 25330] Loading custom repository mappings from /home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py
[Tue Jan 28 12:56:52.133869 2020] [wsgi:error] [pid 25330] Loading outputschemas
[Tue Jan 28 12:56:52.134065 2020] [wsgi:error] [pid 25330] Setting MaxRecordDefault
[Tue Jan 28 12:56:52.134564 2020] [wsgi:error] [pid 25330] Querying repository with ids: 275ae2b4-99b7-11e9-a5ca-000c29291400
[Tue Jan 28 12:56:52.141441 2020] [wsgi:error] [pid 25330] Request processed
[Tue Jan 28 12:56:52.141496 2020] [wsgi:error] [pid 25330] Writing response.
[Tue Jan 28 12:56:52.209178 2020] [wsgi:error] [pid 25330] Loading user configuration
[Tue Jan 28 12:56:52.209567 2020] [wsgi:error] [pid 25330] running configuration {'server': {'maxrecords': '10', 'domaincounts': 'true', 'language': 'el', 'encoding': 'UTF-8', 'url': 'https://geoportal.ermis-f.eu/catalogue/csw', 'home': '.', 'pretty_print': 'true', 'profiles': 'apiso,ebrim', 'domainquerytype': 'range'}, 'metadata:main': {'identification_fees': 'None', 'provider_url': 'https://geoportal.ermis-f.eu/', 'identification_keywords': 'sdi, catalogue, discovery, metadata, GeoNode', 'contact_address': 'Mailing Address', 'identification_accessconstraints': 'None', 'contact_name': 'Lastname, Firstname', 'contact_stateorprovince': 'Administrative Area', 'contact_country': 'Country', 'contact_url': 'Contact URL', 'provider_name': 'Organization Name', 'contact_phone': '+xx-xxx-xxx-xxxx', 'contact_hours': 'Hours of Service', 'contact_role': 'pointOfContact', 'contact_email': 'Email Address', 'identification_title': 'GeoNode Catalogue', 'contact_postalcode': 'Zip or Postal Code', 'contact_city': 'City', 'identification_keywords_type': 'theme', 'identification_abstract': 'GeoNode is an open source platform that facilitates the creation, sharing, and collaborative use of geospatial data', 'contact_fax': '+xx-xxx-xxx-xxxx', 'contact_instructions': 'During hours of service. Off on weekends.', 'contact_position': 'Position Title'}, 'repository': {'filter': 'is_published = true AND id IN (160, 113, 80, 85, 73, 30, 112, 55, 110, 116, 31, 117, 150, 129, 39, 38, 118, 56, 158, 98, 78, 32, 97, 265, 57, 22, 273, 81, 59, 42, 23, 72, 37, 33, 130, 95, 182, 94, 69, 102, 24, 96, 82, 26, 74, 34, 264, 70, 66, 35, 75, 83, 65, 173, 28, 58, 67, 46, 51, 36, 29, 60, 52, 62, 84, 255, 43, 174, 63, 41, 161, 124, 54, 64, 49, 257, 125, 25, 149, 272, 115, 27, 107, 263, 146, 126, 271, 50, 268, 269, 144, 127, 61, 143, 154, 270, 128, 145, 262, 44, 267, 48, 266, 47) AND alternate IS NOT NULL', 'source': 'geonode.catalogue.backends.pycsw_plugin.GeoNodeRepository', 'mappings': '/home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py'}, 'metadata:inspire': {'conformity_service': 'notEvaluated', 'contact_email': 'Email Address', 'languages_supported': 'eng,gre', 'date': 'YYYY-MM-DD', 'default_language': 'eng', 'contact_name': 'Organization Name', 'gemet_keywords': 'Utility and governmental services', 'enabled': 'true', 'temp_extent': 'YYYY-MM-DD/YYYY-MM-DD'}}
[Tue Jan 28 12:56:52.209663 2020] [wsgi:error] [pid 25330] Setting language
[Tue Jan 28 12:56:52.210102 2020] [wsgi:error] [pid 25330] Loading custom repository mappings from /home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py
[Tue Jan 28 12:56:52.210210 2020] [wsgi:error] [pid 25330] Loading outputschemas
[Tue Jan 28 12:56:52.210404 2020] [wsgi:error] [pid 25330] Setting MaxRecordDefault
[Tue Jan 28 12:56:52.210894 2020] [wsgi:error] [pid 25330] Querying repository with ids: 275ae2b4-99b7-11e9-a5ca-000c29291400
[Tue Jan 28 12:56:52.226886 2020] [wsgi:error] [pid 25330] Request processed
[Tue Jan 28 12:56:52.226943 2020] [wsgi:error] [pid 25330] Writing response.
[Tue Jan 28 12:56:52.294702 2020] [wsgi:error] [pid 25329] Loading user configuration
[Tue Jan 28 12:56:52.295104 2020] [wsgi:error] [pid 25329] running configuration {'server': {'maxrecords': '10', 'domaincounts': 'true', 'language': 'el', 'encoding': 'UTF-8', 'url': 'https://geoportal.ermis-f.eu/catalogue/csw', 'home': '.', 'pretty_print': 'true', 'profiles': 'apiso,ebrim', 'domainquerytype': 'range'}, 'metadata:main': {'identification_fees': 'None', 'provider_url': 'https://geoportal.ermis-f.eu/', 'identification_keywords': 'sdi, catalogue, discovery, metadata, GeoNode', 'contact_address': 'Mailing Address', 'identification_accessconstraints': 'None', 'contact_name': 'Lastname, Firstname', 'contact_stateorprovince': 'Administrative Area', 'contact_country': 'Country', 'contact_url': 'Contact URL', 'provider_name': 'Organization Name', 'contact_phone': '+xx-xxx-xxx-xxxx', 'contact_hours': 'Hours of Service', 'contact_role': 'pointOfContact', 'contact_email': 'Email Address', 'identification_title': 'GeoNode Catalogue', 'contact_postalcode': 'Zip or Postal Code', 'contact_city': 'City', 'identification_keywords_type': 'theme', 'identification_abstract': 'GeoNode is an open source platform that facilitates the creation, sharing, and collaborative use of geospatial data', 'contact_fax': '+xx-xxx-xxx-xxxx', 'contact_instructions': 'During hours of service. Off on weekends.', 'contact_position': 'Position Title'}, 'repository': {'filter': 'is_published = true AND id IN (160, 113, 80, 85, 73, 30, 112, 55, 110, 116, 31, 117, 150, 129, 39, 38, 118, 56, 158, 98, 78, 32, 97, 265, 57, 22, 273, 81, 59, 42, 23, 72, 37, 33, 130, 95, 182, 94, 69, 102, 24, 96, 82, 26, 74, 34, 264, 70, 66, 35, 75, 83, 65, 173, 28, 58, 67, 46, 51, 36, 29, 60, 52, 62, 84, 255, 43, 174, 63, 41, 161, 124, 54, 64, 49, 257, 125, 25, 149, 272, 115, 27, 107, 263, 146, 126, 271, 50, 268, 269, 144, 127, 61, 143, 154, 270, 128, 145, 262, 44, 267, 48, 266, 47) AND alternate IS NOT NULL', 'source': 'geonode.catalogue.backends.pycsw_plugin.GeoNodeRepository', 'mappings': '/home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py'}, 'metadata:inspire': {'conformity_service': 'notEvaluated', 'contact_email': 'Email Address', 'languages_supported': 'eng,gre', 'date': 'YYYY-MM-DD', 'default_language': 'eng', 'contact_name': 'Organization Name', 'gemet_keywords': 'Utility and governmental services', 'enabled': 'true', 'temp_extent': 'YYYY-MM-DD/YYYY-MM-DD'}}
[Tue Jan 28 12:56:52.295191 2020] [wsgi:error] [pid 25329] Setting language
[Tue Jan 28 12:56:52.295655 2020] [wsgi:error] [pid 25329] Loading custom repository mappings from /home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py
[Tue Jan 28 12:56:52.295763 2020] [wsgi:error] [pid 25329] Loading outputschemas
[Tue Jan 28 12:56:52.295955 2020] [wsgi:error] [pid 25329] Setting MaxRecordDefault
[Tue Jan 28 12:56:52.296476 2020] [wsgi:error] [pid 25329] Querying repository with ids: 275ae2b4-99b7-11e9-a5ca-000c29291400
[Tue Jan 28 12:56:52.301726 2020] [wsgi:error] [pid 25329] Request processed
[Tue Jan 28 12:56:52.301781 2020] [wsgi:error] [pid 25329] Writing response.
[Tue Jan 28 12:56:52.328098 2020] [wsgi:error] [pid 25330] Loading user configuration
[Tue Jan 28 12:56:52.328212 2020] [wsgi:error] [pid 25330] running configuration <ConfigParser.SafeConfigParser instance at 0x7fd81dd92bd8>
[Tue Jan 28 12:56:52.328289 2020] [wsgi:error] [pid 25330] Setting language
[Tue Jan 28 12:56:52.328708 2020] [wsgi:error] [pid 25330] Loading custom repository mappings from /home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py
[Tue Jan 28 12:56:52.328816 2020] [wsgi:error] [pid 25330] Loading outputschemas
[Tue Jan 28 12:56:52.328913 2020] [wsgi:error] [pid 25330] Setting MaxRecordDefault
[Tue Jan 28 12:56:52.329399 2020] [wsgi:error] [pid 25330] Querying repository with ids: 275ae2b4-99b7-11e9-a5ca-000c29291400
[Tue Jan 28 12:56:52.343672 2020] [wsgi:error] [pid 25330] Request processed
[Tue Jan 28 12:56:52.343730 2020] [wsgi:error] [pid 25330] Writing response.
[Tue Jan 28 12:56:53.223884 2020] [wsgi:error] [pid 25329] Loading user configuration
[Tue Jan 28 12:56:53.224277 2020] [wsgi:error] [pid 25329] running configuration {'server': {'maxrecords': '10', 'domaincounts': 'true', 'language': 'el', 'encoding': 'UTF-8', 'url': 'https://geoportal.ermis-f.eu/catalogue/csw', 'home': '.', 'pretty_print': 'true', 'profiles': 'apiso,ebrim', 'domainquerytype': 'range'}, 'metadata:main': {'identification_fees': 'None', 'provider_url': 'https://geoportal.ermis-f.eu/', 'identification_keywords': 'sdi, catalogue, discovery, metadata, GeoNode', 'contact_address': 'Mailing Address', 'identification_accessconstraints': 'None', 'contact_name': 'Lastname, Firstname', 'contact_stateorprovince': 'Administrative Area', 'contact_country': 'Country', 'contact_url': 'Contact URL', 'provider_name': 'Organization Name', 'contact_phone': '+xx-xxx-xxx-xxxx', 'contact_hours': 'Hours of Service', 'contact_role': 'pointOfContact', 'contact_email': 'Email Address', 'identification_title': 'GeoNode Catalogue', 'contact_postalcode': 'Zip or Postal Code', 'contact_city': 'City', 'identification_keywords_type': 'theme', 'identification_abstract': 'GeoNode is an open source platform that facilitates the creation, sharing, and collaborative use of geospatial data', 'contact_fax': '+xx-xxx-xxx-xxxx', 'contact_instructions': 'During hours of service. Off on weekends.', 'contact_position': 'Position Title'}, 'repository': {'filter': 'is_published = true AND id IN (160, 113, 80, 85, 73, 30, 112, 55, 110, 116, 31, 117, 150, 129, 39, 38, 118, 56, 158, 98, 78, 32, 97, 265, 57, 22, 273, 81, 59, 42, 23, 72, 37, 33, 130, 95, 182, 94, 69, 102, 24, 96, 82, 26, 74, 34, 264, 70, 66, 35, 75, 83, 65, 173, 28, 58, 67, 46, 51, 36, 29, 60, 52, 62, 84, 255, 43, 174, 63, 41, 161, 124, 54, 64, 49, 257, 125, 25, 149, 272, 115, 27, 107, 263, 146, 126, 271, 50, 268, 269, 144, 127, 61, 143, 154, 270, 128, 145, 262, 44, 267, 48, 266, 47) AND alternate IS NOT NULL', 'source': 'geonode.catalogue.backends.pycsw_plugin.GeoNodeRepository', 'mappings': '/home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py'}, 'metadata:inspire': {'conformity_service': 'notEvaluated', 'contact_email': 'Email Address', 'languages_supported': 'eng,gre', 'date': 'YYYY-MM-DD', 'default_language': 'eng', 'contact_name': 'Organization Name', 'gemet_keywords': 'Utility and governmental services', 'enabled': 'true', 'temp_extent': 'YYYY-MM-DD/YYYY-MM-DD'}}
[Tue Jan 28 12:56:53.224362 2020] [wsgi:error] [pid 25329] Setting language
[Tue Jan 28 12:56:53.224779 2020] [wsgi:error] [pid 25329] Loading custom repository mappings from /home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py
[Tue Jan 28 12:56:53.224888 2020] [wsgi:error] [pid 25329] Loading outputschemas
[Tue Jan 28 12:56:53.225091 2020] [wsgi:error] [pid 25329] Setting MaxRecordDefault
[Tue Jan 28 12:56:53.225603 2020] [wsgi:error] [pid 25329] Querying repository with ids: 275ae2b4-99b7-11e9-a5ca-000c29291400
[Tue Jan 28 12:56:53.238735 2020] [wsgi:error] [pid 25329] Request processed
[Tue Jan 28 12:56:53.238795 2020] [wsgi:error] [pid 25329] Writing response.
[Tue Jan 28 12:56:53.306653 2020] [wsgi:error] [pid 25330] Loading user configuration
[Tue Jan 28 12:56:53.307050 2020] [wsgi:error] [pid 25330] running configuration {'server': {'maxrecords': '10', 'domaincounts': 'true', 'language': 'el', 'encoding': 'UTF-8', 'url': 'https://geoportal.ermis-f.eu/catalogue/csw', 'home': '.', 'pretty_print': 'true', 'profiles': 'apiso,ebrim', 'domainquerytype': 'range'}, 'metadata:main': {'identification_fees': 'None', 'provider_url': 'https://geoportal.ermis-f.eu/', 'identification_keywords': 'sdi, catalogue, discovery, metadata, GeoNode', 'contact_address': 'Mailing Address', 'identification_accessconstraints': 'None', 'contact_name': 'Lastname, Firstname', 'contact_stateorprovince': 'Administrative Area', 'contact_country': 'Country', 'contact_url': 'Contact URL', 'provider_name': 'Organization Name', 'contact_phone': '+xx-xxx-xxx-xxxx', 'contact_hours': 'Hours of Service', 'contact_role': 'pointOfContact', 'contact_email': 'Email Address', 'identification_title': 'GeoNode Catalogue', 'contact_postalcode': 'Zip or Postal Code', 'contact_city': 'City', 'identification_keywords_type': 'theme', 'identification_abstract': 'GeoNode is an open source platform that facilitates the creation, sharing, and collaborative use of geospatial data', 'contact_fax': '+xx-xxx-xxx-xxxx', 'contact_instructions': 'During hours of service. Off on weekends.', 'contact_position': 'Position Title'}, 'repository': {'filter': 'is_published = true AND id IN (160, 113, 80, 85, 73, 30, 112, 55, 110, 116, 31, 117, 150, 129, 39, 38, 118, 56, 158, 98, 78, 32, 97, 265, 57, 22, 273, 81, 59, 42, 23, 72, 37, 33, 130, 95, 182, 94, 69, 102, 24, 96, 82, 26, 74, 34, 264, 70, 66, 35, 75, 83, 65, 173, 28, 58, 67, 46, 51, 36, 29, 60, 52, 62, 84, 255, 43, 174, 63, 41, 161, 124, 54, 64, 49, 257, 125, 25, 149, 272, 115, 27, 107, 263, 146, 126, 271, 50, 268, 269, 144, 127, 61, 143, 154, 270, 128, 145, 262, 44, 267, 48, 266, 47) AND alternate IS NOT NULL', 'source': 'geonode.catalogue.backends.pycsw_plugin.GeoNodeRepository', 'mappings': '/home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py'}, 'metadata:inspire': {'conformity_service': 'notEvaluated', 'contact_email': 'Email Address', 'languages_supported': 'eng,gre', 'date': 'YYYY-MM-DD', 'default_language': 'eng', 'contact_name': 'Organization Name', 'gemet_keywords': 'Utility and governmental services', 'enabled': 'true', 'temp_extent': 'YYYY-MM-DD/YYYY-MM-DD'}}
[Tue Jan 28 12:56:53.307136 2020] [wsgi:error] [pid 25330] Setting language
[Tue Jan 28 12:56:53.307554 2020] [wsgi:error] [pid 25330] Loading custom repository mappings from /home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py
[Tue Jan 28 12:56:53.307659 2020] [wsgi:error] [pid 25330] Loading outputschemas
[Tue Jan 28 12:56:53.307853 2020] [wsgi:error] [pid 25330] Setting MaxRecordDefault
[Tue Jan 28 12:56:53.308347 2020] [wsgi:error] [pid 25330] Querying repository with ids: 275ae2b4-99b7-11e9-a5ca-000c29291400
[Tue Jan 28 12:56:53.324053 2020] [wsgi:error] [pid 25330] Request processed
[Tue Jan 28 12:56:53.324113 2020] [wsgi:error] [pid 25330] Writing response.
[Tue Jan 28 12:56:53.391225 2020] [wsgi:error] [pid 25330] Loading user configuration
[Tue Jan 28 12:56:53.391615 2020] [wsgi:error] [pid 25330] running configuration {'server': {'maxrecords': '10', 'domaincounts': 'true', 'language': 'el', 'encoding': 'UTF-8', 'url': 'https://geoportal.ermis-f.eu/catalogue/csw', 'home': '.', 'pretty_print': 'true', 'profiles': 'apiso,ebrim', 'domainquerytype': 'range'}, 'metadata:main': {'identification_fees': 'None', 'provider_url': 'https://geoportal.ermis-f.eu/', 'identification_keywords': 'sdi, catalogue, discovery, metadata, GeoNode', 'contact_address': 'Mailing Address', 'identification_accessconstraints': 'None', 'contact_name': 'Lastname, Firstname', 'contact_stateorprovince': 'Administrative Area', 'contact_country': 'Country', 'contact_url': 'Contact URL', 'provider_name': 'Organization Name', 'contact_phone': '+xx-xxx-xxx-xxxx', 'contact_hours': 'Hours of Service', 'contact_role': 'pointOfContact', 'contact_email': 'Email Address', 'identification_title': 'GeoNode Catalogue', 'contact_postalcode': 'Zip or Postal Code', 'contact_city': 'City', 'identification_keywords_type': 'theme', 'identification_abstract': 'GeoNode is an open source platform that facilitates the creation, sharing, and collaborative use of geospatial data', 'contact_fax': '+xx-xxx-xxx-xxxx', 'contact_instructions': 'During hours of service. Off on weekends.', 'contact_position': 'Position Title'}, 'repository': {'filter': 'is_published = true AND id IN (160, 113, 80, 85, 73, 30, 112, 55, 110, 116, 31, 117, 150, 129, 39, 38, 118, 56, 158, 98, 78, 32, 97, 265, 57, 22, 273, 81, 59, 42, 23, 72, 37, 33, 130, 95, 182, 94, 69, 102, 24, 96, 82, 26, 74, 34, 264, 70, 66, 35, 75, 83, 65, 173, 28, 58, 67, 46, 51, 36, 29, 60, 52, 62, 84, 255, 43, 174, 63, 41, 161, 124, 54, 64, 49, 257, 125, 25, 149, 272, 115, 27, 107, 263, 146, 126, 271, 50, 268, 269, 144, 127, 61, 143, 154, 270, 128, 145, 262, 44, 267, 48, 266, 47) AND alternate IS NOT NULL', 'source': 'geonode.catalogue.backends.pycsw_plugin.GeoNodeRepository', 'mappings': '/home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py'}, 'metadata:inspire': {'conformity_service': 'notEvaluated', 'contact_email': 'Email Address', 'languages_supported': 'eng,gre', 'date': 'YYYY-MM-DD', 'default_language': 'eng', 'contact_name': 'Organization Name', 'gemet_keywords': 'Utility and governmental services', 'enabled': 'true', 'temp_extent': 'YYYY-MM-DD/YYYY-MM-DD'}}
[Tue Jan 28 12:56:53.391709 2020] [wsgi:error] [pid 25330] Setting language
[Tue Jan 28 12:56:53.392140 2020] [wsgi:error] [pid 25330] Loading custom repository mappings from /home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py
[Tue Jan 28 12:56:53.392251 2020] [wsgi:error] [pid 25330] Loading outputschemas
[Tue Jan 28 12:56:53.392444 2020] [wsgi:error] [pid 25330] Setting MaxRecordDefault
[Tue Jan 28 12:56:53.392945 2020] [wsgi:error] [pid 25330] Querying repository with ids: 275ae2b4-99b7-11e9-a5ca-000c29291400
[Tue Jan 28 12:56:53.410319 2020] [wsgi:error] [pid 25330] Request processed
[Tue Jan 28 12:56:53.410381 2020] [wsgi:error] [pid 25330] Writing response.
[Tue Jan 28 12:56:53.478292 2020] [wsgi:error] [pid 25330] Loading user configuration
[Tue Jan 28 12:56:53.478687 2020] [wsgi:error] [pid 25330] running configuration {'server': {'maxrecords': '10', 'domaincounts': 'true', 'language': 'el', 'encoding': 'UTF-8', 'url': 'https://geoportal.ermis-f.eu/catalogue/csw', 'home': '.', 'pretty_print': 'true', 'profiles': 'apiso,ebrim', 'domainquerytype': 'range'}, 'metadata:main': {'identification_fees': 'None', 'provider_url': 'https://geoportal.ermis-f.eu/', 'identification_keywords': 'sdi, catalogue, discovery, metadata, GeoNode', 'contact_address': 'Mailing Address', 'identification_accessconstraints': 'None', 'contact_name': 'Lastname, Firstname', 'contact_stateorprovince': 'Administrative Area', 'contact_country': 'Country', 'contact_url': 'Contact URL', 'provider_name': 'Organization Name', 'contact_phone': '+xx-xxx-xxx-xxxx', 'contact_hours': 'Hours of Service', 'contact_role': 'pointOfContact', 'contact_email': 'Email Address', 'identification_title': 'GeoNode Catalogue', 'contact_postalcode': 'Zip or Postal Code', 'contact_city': 'City', 'identification_keywords_type': 'theme', 'identification_abstract': 'GeoNode is an open source platform that facilitates the creation, sharing, and collaborative use of geospatial data', 'contact_fax': '+xx-xxx-xxx-xxxx', 'contact_instructions': 'During hours of service. Off on weekends.', 'contact_position': 'Position Title'}, 'repository': {'filter': 'is_published = true AND id IN (160, 113, 80, 85, 73, 30, 112, 55, 110, 116, 31, 117, 150, 129, 39, 38, 118, 56, 158, 98, 78, 32, 97, 265, 57, 22, 273, 81, 59, 42, 23, 72, 37, 33, 130, 95, 182, 94, 69, 102, 24, 96, 82, 26, 74, 34, 264, 70, 66, 35, 75, 83, 65, 173, 28, 58, 67, 46, 51, 36, 29, 60, 52, 62, 84, 255, 43, 174, 63, 41, 161, 124, 54, 64, 49, 257, 125, 25, 149, 272, 115, 27, 107, 263, 146, 126, 271, 50, 268, 269, 144, 127, 61, 143, 154, 270, 128, 145, 262, 44, 267, 48, 266, 47) AND alternate IS NOT NULL', 'source': 'geonode.catalogue.backends.pycsw_plugin.GeoNodeRepository', 'mappings': '/home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py'}, 'metadata:inspire': {'conformity_service': 'notEvaluated', 'contact_email': 'Email Address', 'languages_supported': 'eng,gre', 'date': 'YYYY-MM-DD', 'default_language': 'eng', 'contact_name': 'Organization Name', 'gemet_keywords': 'Utility and governmental services', 'enabled': 'true', 'temp_extent': 'YYYY-MM-DD/YYYY-MM-DD'}}
[Tue Jan 28 12:56:53.478785 2020] [wsgi:error] [pid 25330] Setting language
[Tue Jan 28 12:56:53.479213 2020] [wsgi:error] [pid 25330] Loading custom repository mappings from /home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py
[Tue Jan 28 12:56:53.479322 2020] [wsgi:error] [pid 25330] Loading outputschemas
[Tue Jan 28 12:56:53.479516 2020] [wsgi:error] [pid 25330] Setting MaxRecordDefault
[Tue Jan 28 12:56:53.480014 2020] [wsgi:error] [pid 25330] Querying repository with ids: 275ae2b4-99b7-11e9-a5ca-000c29291400
[Tue Jan 28 12:56:53.486485 2020] [wsgi:error] [pid 25330] Request processed
[Tue Jan 28 12:56:53.486540 2020] [wsgi:error] [pid 25330] Writing response.
[Tue Jan 28 12:56:53.555019 2020] [wsgi:error] [pid 25329] Loading user configuration
[Tue Jan 28 12:56:53.555409 2020] [wsgi:error] [pid 25329] running configuration {'server': {'maxrecords': '10', 'domaincounts': 'true', 'language': 'el', 'encoding': 'UTF-8', 'url': 'https://geoportal.ermis-f.eu/catalogue/csw', 'home': '.', 'pretty_print': 'true', 'profiles': 'apiso,ebrim', 'domainquerytype': 'range'}, 'metadata:main': {'identification_fees': 'None', 'provider_url': 'https://geoportal.ermis-f.eu/', 'identification_keywords': 'sdi, catalogue, discovery, metadata, GeoNode', 'contact_address': 'Mailing Address', 'identification_accessconstraints': 'None', 'contact_name': 'Lastname, Firstname', 'contact_stateorprovince': 'Administrative Area', 'contact_country': 'Country', 'contact_url': 'Contact URL', 'provider_name': 'Organization Name', 'contact_phone': '+xx-xxx-xxx-xxxx', 'contact_hours': 'Hours of Service', 'contact_role': 'pointOfContact', 'contact_email': 'Email Address', 'identification_title': 'GeoNode Catalogue', 'contact_postalcode': 'Zip or Postal Code', 'contact_city': 'City', 'identification_keywords_type': 'theme', 'identification_abstract': 'GeoNode is an open source platform that facilitates the creation, sharing, and collaborative use of geospatial data', 'contact_fax': '+xx-xxx-xxx-xxxx', 'contact_instructions': 'During hours of service. Off on weekends.', 'contact_position': 'Position Title'}, 'repository': {'filter': 'is_published = true AND id IN (160, 113, 80, 85, 73, 30, 112, 55, 110, 116, 31, 117, 150, 129, 39, 38, 118, 56, 158, 98, 78, 32, 97, 265, 57, 22, 273, 81, 59, 42, 23, 72, 37, 33, 130, 95, 182, 94, 69, 102, 24, 96, 82, 26, 74, 34, 264, 70, 66, 35, 75, 83, 65, 173, 28, 58, 67, 46, 51, 36, 29, 60, 52, 62, 84, 255, 43, 174, 63, 41, 161, 124, 54, 64, 49, 257, 125, 25, 149, 272, 115, 27, 107, 263, 146, 126, 271, 50, 268, 269, 144, 127, 61, 143, 154, 270, 128, 145, 262, 44, 267, 48, 266, 47) AND alternate IS NOT NULL', 'source': 'geonode.catalogue.backends.pycsw_plugin.GeoNodeRepository', 'mappings': '/home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py'}, 'metadata:inspire': {'conformity_service': 'notEvaluated', 'contact_email': 'Email Address', 'languages_supported': 'eng,gre', 'date': 'YYYY-MM-DD', 'default_language': 'eng', 'contact_name': 'Organization Name', 'gemet_keywords': 'Utility and governmental services', 'enabled': 'true', 'temp_extent': 'YYYY-MM-DD/YYYY-MM-DD'}}
[Tue Jan 28 12:56:53.555505 2020] [wsgi:error] [pid 25329] Setting language
[Tue Jan 28 12:56:53.555915 2020] [wsgi:error] [pid 25329] Loading custom repository mappings from /home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py
[Tue Jan 28 12:56:53.556022 2020] [wsgi:error] [pid 25329] Loading outputschemas
[Tue Jan 28 12:56:53.556230 2020] [wsgi:error] [pid 25329] Setting MaxRecordDefault
[Tue Jan 28 12:56:53.556723 2020] [wsgi:error] [pid 25329] Querying repository with ids: 275ae2b4-99b7-11e9-a5ca-000c29291400
[Tue Jan 28 12:56:53.572729 2020] [wsgi:error] [pid 25329] Request processed
[Tue Jan 28 12:56:53.572788 2020] [wsgi:error] [pid 25329] Writing response.
[Tue Jan 28 12:56:53.643613 2020] [wsgi:error] [pid 25330] Loading user configuration
[Tue Jan 28 12:56:53.644007 2020] [wsgi:error] [pid 25330] running configuration {'server': {'maxrecords': '10', 'domaincounts': 'true', 'language': 'el', 'encoding': 'UTF-8', 'url': 'https://geoportal.ermis-f.eu/catalogue/csw', 'home': '.', 'pretty_print': 'true', 'profiles': 'apiso,ebrim', 'domainquerytype': 'range'}, 'metadata:main': {'identification_fees': 'None', 'provider_url': 'https://geoportal.ermis-f.eu/', 'identification_keywords': 'sdi, catalogue, discovery, metadata, GeoNode', 'contact_address': 'Mailing Address', 'identification_accessconstraints': 'None', 'contact_name': 'Lastname, Firstname', 'contact_stateorprovince': 'Administrative Area', 'contact_country': 'Country', 'contact_url': 'Contact URL', 'provider_name': 'Organization Name', 'contact_phone': '+xx-xxx-xxx-xxxx', 'contact_hours': 'Hours of Service', 'contact_role': 'pointOfContact', 'contact_email': 'Email Address', 'identification_title': 'GeoNode Catalogue', 'contact_postalcode': 'Zip or Postal Code', 'contact_city': 'City', 'identification_keywords_type': 'theme', 'identification_abstract': 'GeoNode is an open source platform that facilitates the creation, sharing, and collaborative use of geospatial data', 'contact_fax': '+xx-xxx-xxx-xxxx', 'contact_instructions': 'During hours of service. Off on weekends.', 'contact_position': 'Position Title'}, 'repository': {'filter': 'is_published = true AND id IN (160, 113, 80, 85, 73, 30, 112, 55, 110, 116, 31, 117, 150, 129, 39, 38, 118, 56, 158, 98, 78, 32, 97, 265, 57, 22, 273, 81, 59, 42, 23, 72, 37, 33, 130, 95, 182, 94, 69, 102, 24, 96, 82, 26, 74, 34, 264, 70, 66, 35, 75, 83, 65, 173, 28, 58, 67, 46, 51, 36, 29, 60, 52, 62, 84, 255, 43, 174, 63, 41, 161, 124, 54, 64, 49, 257, 125, 25, 149, 272, 115, 27, 107, 263, 146, 126, 271, 50, 268, 269, 144, 127, 61, 143, 154, 270, 128, 145, 262, 44, 267, 48, 266, 47) AND alternate IS NOT NULL', 'source': 'geonode.catalogue.backends.pycsw_plugin.GeoNodeRepository', 'mappings': '/home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py'}, 'metadata:inspire': {'conformity_service': 'notEvaluated', 'contact_email': 'Email Address', 'languages_supported': 'eng,gre', 'date': 'YYYY-MM-DD', 'default_language': 'eng', 'contact_name': 'Organization Name', 'gemet_keywords': 'Utility and governmental services', 'enabled': 'true', 'temp_extent': 'YYYY-MM-DD/YYYY-MM-DD'}}
[Tue Jan 28 12:56:53.644093 2020] [wsgi:error] [pid 25330] Setting language
[Tue Jan 28 12:56:53.644517 2020] [wsgi:error] [pid 25330] Loading custom repository mappings from /home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py
[Tue Jan 28 12:56:53.644624 2020] [wsgi:error] [pid 25330] Loading outputschemas
[Tue Jan 28 12:56:53.644814 2020] [wsgi:error] [pid 25330] Setting MaxRecordDefault
[Tue Jan 28 12:56:53.645312 2020] [wsgi:error] [pid 25330] Querying repository with ids: 275ae2b4-99b7-11e9-a5ca-000c29291400
[Tue Jan 28 12:56:53.650269 2020] [wsgi:error] [pid 25330] Request processed
[Tue Jan 28 12:56:53.650323 2020] [wsgi:error] [pid 25330] Writing response.
[Tue Jan 28 12:56:53.678906 2020] [wsgi:error] [pid 25329] Loading user configuration
[Tue Jan 28 12:56:53.679025 2020] [wsgi:error] [pid 25329] running configuration <ConfigParser.SafeConfigParser instance at 0x7fd81db45128>
[Tue Jan 28 12:56:53.679122 2020] [wsgi:error] [pid 25329] Setting language
[Tue Jan 28 12:56:53.679549 2020] [wsgi:error] [pid 25329] Loading custom repository mappings from /home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py
[Tue Jan 28 12:56:53.679661 2020] [wsgi:error] [pid 25329] Loading outputschemas
[Tue Jan 28 12:56:53.679757 2020] [wsgi:error] [pid 25329] Setting MaxRecordDefault
[Tue Jan 28 12:56:53.680240 2020] [wsgi:error] [pid 25329] Querying repository with ids: 275ae2b4-99b7-11e9-a5ca-000c29291400
[Tue Jan 28 12:56:53.696180 2020] [wsgi:error] [pid 25329] Request processed
[Tue Jan 28 12:56:53.696241 2020] [wsgi:error] [pid 25329] Writing response.
[Tue Jan 28 12:56:55.312582 2020] [wsgi:error] [pid 25330] [remote 46.229.168.140:27248] mod_wsgi (pid=25330): Exception occurred processing WSGI script '/home/geonode/ermis/ermis/wsgi.py'.
[Tue Jan 28 12:56:55.312646 2020] [wsgi:error] [pid 25330] [remote 46.229.168.140:27248] IOError: failed to write data
[Tue Jan 28 13:08:31.777845 2020] [wsgi:error] [pid 25330] Loading user configuration
[Tue Jan 28 13:08:31.778259 2020] [wsgi:error] [pid 25330] running configuration {'server': {'maxrecords': '10', 'domaincounts': 'true', 'language': 'el', 'encoding': 'UTF-8', 'url': 'https://geoportal.ermis-f.eu/catalogue/csw', 'home': '.', 'pretty_print': 'true', 'profiles': 'apiso,ebrim', 'domainquerytype': 'range'}, 'metadata:main': {'identification_fees': 'None', 'provider_url': 'https://geoportal.ermis-f.eu/', 'identification_keywords': 'sdi, catalogue, discovery, metadata, GeoNode', 'contact_address': 'Mailing Address', 'identification_accessconstraints': 'None', 'contact_name': 'Lastname, Firstname', 'contact_stateorprovince': 'Administrative Area', 'contact_country': 'Country', 'contact_url': 'Contact URL', 'provider_name': 'Organization Name', 'contact_phone': '+xx-xxx-xxx-xxxx', 'contact_hours': 'Hours of Service', 'contact_role': 'pointOfContact', 'contact_email': 'Email Address', 'identification_title': 'GeoNode Catalogue', 'contact_postalcode': 'Zip or Postal Code', 'contact_city': 'City', 'identification_keywords_type': 'theme', 'identification_abstract': 'GeoNode is an open source platform that facilitates the creation, sharing, and collaborative use of geospatial data', 'contact_fax': '+xx-xxx-xxx-xxxx', 'contact_instructions': 'During hours of service. Off on weekends.', 'contact_position': 'Position Title'}, 'repository': {'filter': 'is_published = true AND id IN (160, 113, 80, 85, 73, 30, 112, 55, 110, 116, 31, 117, 150, 129, 39, 38, 118, 56, 158, 98, 78, 32, 97, 265, 57, 22, 273, 81, 59, 42, 23, 72, 37, 33, 130, 95, 182, 94, 69, 102, 24, 96, 82, 26, 74, 34, 264, 70, 66, 35, 75, 83, 65, 173, 28, 58, 67, 46, 51, 36, 29, 60, 52, 62, 84, 255, 43, 174, 63, 41, 161, 124, 54, 64, 49, 257, 125, 25, 149, 272, 115, 27, 107, 263, 146, 126, 271, 50, 268, 269, 144, 127, 61, 143, 154, 270, 128, 145, 262, 44, 267, 48, 266, 47) AND alternate IS NOT NULL', 'source': 'geonode.catalogue.backends.pycsw_plugin.GeoNodeRepository', 'mappings': '/home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py'}, 'metadata:inspire': {'conformity_service': 'notEvaluated', 'contact_email': 'Email Address', 'languages_supported': 'eng,gre', 'date': 'YYYY-MM-DD', 'default_language': 'eng', 'contact_name': 'Organization Name', 'gemet_keywords': 'Utility and governmental services', 'enabled': 'true', 'temp_extent': 'YYYY-MM-DD/YYYY-MM-DD'}}
[Tue Jan 28 13:08:31.778344 2020] [wsgi:error] [pid 25330] Setting language
[Tue Jan 28 13:08:31.778801 2020] [wsgi:error] [pid 25330] Loading custom repository mappings from /home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py
[Tue Jan 28 13:08:31.778913 2020] [wsgi:error] [pid 25330] Loading outputschemas
[Tue Jan 28 13:08:31.779128 2020] [wsgi:error] [pid 25330] Setting MaxRecordDefault
[Tue Jan 28 13:08:31.779715 2020] [wsgi:error] [pid 25330] Querying repository with ids: 911e02b2-99b7-11e9-a5ca-000c29291400
[Tue Jan 28 13:08:31.795803 2020] [wsgi:error] [pid 25330] Request processed
[Tue Jan 28 13:08:31.795858 2020] [wsgi:error] [pid 25330] Writing response.
[Tue Jan 28 13:19:26.191434 2020] [wsgi:error] [pid 25329] Loading user configuration
[Tue Jan 28 13:19:26.191860 2020] [wsgi:error] [pid 25329] running configuration {'server': {'maxrecords': '10', 'domaincounts': 'true', 'language': 'el', 'encoding': 'UTF-8', 'url': 'https://geoportal.ermis-f.eu/catalogue/csw', 'home': '.', 'pretty_print': 'true', 'profiles': 'apiso,ebrim', 'domainquerytype': 'range'}, 'metadata:main': {'identification_fees': 'None', 'provider_url': 'https://geoportal.ermis-f.eu/', 'identification_keywords': 'sdi, catalogue, discovery, metadata, GeoNode', 'contact_address': 'Mailing Address', 'identification_accessconstraints': 'None', 'contact_name': 'Lastname, Firstname', 'contact_stateorprovince': 'Administrative Area', 'contact_country': 'Country', 'contact_url': 'Contact URL', 'provider_name': 'Organization Name', 'contact_phone': '+xx-xxx-xxx-xxxx', 'contact_hours': 'Hours of Service', 'contact_role': 'pointOfContact', 'contact_email': 'Email Address', 'identification_title': 'GeoNode Catalogue', 'contact_postalcode': 'Zip or Postal Code', 'contact_city': 'City', 'identification_keywords_type': 'theme', 'identification_abstract': 'GeoNode is an open source platform that facilitates the creation, sharing, and collaborative use of geospatial data', 'contact_fax': '+xx-xxx-xxx-xxxx', 'contact_instructions': 'During hours of service. Off on weekends.', 'contact_position': 'Position Title'}, 'repository': {'filter': 'is_published = true AND id IN (160, 113, 80, 85, 73, 30, 112, 55, 110, 116, 31, 117, 150, 129, 39, 38, 118, 56, 158, 98, 78, 32, 97, 265, 57, 22, 273, 81, 59, 42, 23, 72, 37, 33, 130, 95, 182, 94, 69, 102, 24, 96, 82, 26, 74, 34, 264, 70, 66, 35, 75, 83, 65, 173, 28, 58, 67, 46, 51, 36, 29, 60, 52, 62, 84, 255, 43, 174, 63, 41, 161, 124, 54, 64, 49, 257, 125, 25, 149, 272, 115, 27, 107, 263, 146, 126, 271, 50, 268, 269, 144, 127, 61, 143, 154, 270, 128, 145, 262, 44, 267, 48, 266, 47) AND alternate IS NOT NULL', 'source': 'geonode.catalogue.backends.pycsw_plugin.GeoNodeRepository', 'mappings': '/home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py'}, 'metadata:inspire': {'conformity_service': 'notEvaluated', 'contact_email': 'Email Address', 'languages_supported': 'eng,gre', 'date': 'YYYY-MM-DD', 'default_language': 'eng', 'contact_name': 'Organization Name', 'gemet_keywords': 'Utility and governmental services', 'enabled': 'true', 'temp_extent': 'YYYY-MM-DD/YYYY-MM-DD'}}
[Tue Jan 28 13:19:26.191948 2020] [wsgi:error] [pid 25329] Setting language
[Tue Jan 28 13:19:26.192408 2020] [wsgi:error] [pid 25329] Loading custom repository mappings from /home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py
[Tue Jan 28 13:19:26.192516 2020] [wsgi:error] [pid 25329] Loading outputschemas
[Tue Jan 28 13:19:26.192721 2020] [wsgi:error] [pid 25329] Setting MaxRecordDefault
[Tue Jan 28 13:19:26.193321 2020] [wsgi:error] [pid 25329] Querying repository with ids: 8b68c64e-99b8-11e9-a5ca-000c29291400
[Tue Jan 28 13:19:26.210694 2020] [wsgi:error] [pid 25329] Request processed
[Tue Jan 28 13:19:26.210762 2020] [wsgi:error] [pid 25329] Writing response.
[Tue Jan 28 13:22:19.684558 2020] [mpm_prefork:notice] [pid 11115] AH00169: caught SIGTERM, shutting down
[Tue Jan 28 13:22:20.795373 2020] [wsgi:warn] [pid 28083] mod_wsgi: Compiled for Python/2.7.11.
[Tue Jan 28 13:22:20.795410 2020] [wsgi:warn] [pid 28083] mod_wsgi: Runtime using Python/2.7.12.
[Tue Jan 28 13:22:20.797269 2020] [mpm_prefork:notice] [pid 28083] AH00163: Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g mod_wsgi/4.3.0 Python/2.7.12 configured -- resuming normal operations
[Tue Jan 28 13:22:20.797294 2020] [core:notice] [pid 28083] AH00094: Command line: '/usr/sbin/apache2'
[Tue Jan 28 13:24:46.225801 2020] [mpm_prefork:notice] [pid 28083] AH00169: caught SIGTERM, shutting down
[Tue Jan 28 13:24:47.319593 2020] [wsgi:warn] [pid 28496] mod_wsgi: Compiled for Python/2.7.11.
[Tue Jan 28 13:24:47.319630 2020] [wsgi:warn] [pid 28496] mod_wsgi: Runtime using Python/2.7.12.
[Tue Jan 28 13:24:47.321105 2020] [mpm_prefork:notice] [pid 28496] AH00163: Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g mod_wsgi/4.3.0 Python/2.7.12 configured -- resuming normal operations
[Tue Jan 28 13:24:47.321125 2020] [core:notice] [pid 28496] AH00094: Command line: '/usr/sbin/apache2'
[Tue Jan 28 13:25:31.485813 2020] [wsgi:error] [pid 28500] Loading user configuration
[Tue Jan 28 13:25:31.488661 2020] [wsgi:error] [pid 28500] running configuration <ConfigParser.SafeConfigParser instance at 0x7fc218522248>
[Tue Jan 28 13:25:31.488843 2020] [wsgi:error] [pid 28500] Setting language
[Tue Jan 28 13:25:31.489564 2020] [wsgi:error] [pid 28500] Loading custom repository mappings from /home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py
[Tue Jan 28 13:25:31.489688 2020] [wsgi:error] [pid 28500] Loading outputschemas
[Tue Jan 28 13:25:31.490161 2020] [wsgi:error] [pid 28500] Setting MaxRecordDefault
[Tue Jan 28 13:25:31.577342 2020] [wsgi:error] [pid 28500] Querying repository with ids: 9fb32564-3dbd-11ea-a5ca-000c29291400
[Tue Jan 28 13:25:31.598735 2020] [wsgi:error] [pid 28500] Request processed
[Tue Jan 28 13:25:31.598896 2020] [wsgi:error] [pid 28500] Writing response.
[Tue Jan 28 13:25:31.606136 2020] [wsgi:error] [pid 28500] /home/geo/Envs/geonode/lib/python2.7/site-packages/owslib/iso.py:117: FutureWarning: the .identification and .serviceidentification properties will merge into .identification being a list of properties.  This is currently implemented in .identificationinfo.  Please see https://github.com/geopython/OWSLib/issues/38 for more information
[Tue Jan 28 13:25:31.608863 2020] [wsgi:error] [pid 28500]   FutureWarning)
[Tue Jan 28 13:25:31.609774 2020] [wsgi:error] [pid 28500] /home/geo/Envs/geonode/lib/python2.7/site-packages/owslib/iso.py:482: FutureWarning: The .keywords and .keywords2 properties will merge into the .keywords property in the future, with .keywords becoming a list of MD_Keywords instances. This is currently implemented in .keywords2. Please see https://github.com/geopython/OWSLib/issues/301 for more information
[Tue Jan 28 13:25:31.610604 2020] [wsgi:error] [pid 28500]   FutureWarning)
[Tue Jan 28 13:35:50.187297 2020] [mpm_prefork:notice] [pid 28496] AH00169: caught SIGTERM, shutting down
[Tue Jan 28 13:35:51.226959 2020] [wsgi:warn] [pid 29836] mod_wsgi: Compiled for Python/2.7.11.
[Tue Jan 28 13:35:51.226995 2020] [wsgi:warn] [pid 29836] mod_wsgi: Runtime using Python/2.7.12.
[Tue Jan 28 13:35:51.229139 2020] [mpm_prefork:notice] [pid 29836] AH00163: Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g mod_wsgi/4.3.0 Python/2.7.12 configured -- resuming normal operations
[Tue Jan 28 13:35:51.229168 2020] [core:notice] [pid 29836] AH00094: Command line: '/usr/sbin/apache2'
[Tue Jan 28 13:36:44.451421 2020] [wsgi:error] [pid 29839] uploaded_files: [<InMemoryUploadedFile: SBLA_Raingauges.kmz (application/vnd.google-earth.kmz)>]
[Tue Jan 28 13:36:44.452539 2020] [wsgi:error] [pid 29839] upload error: [u'Could not find any kml files inside the uploaded kmz']
[Tue Jan 28 13:36:44.452614 2020] [wsgi:error] [pid 29839] None
[Tue Jan 28 13:36:44.452618 2020] [wsgi:error] [pid 29839] 
[Tue Jan 28 13:42:45.219301 2020] [mpm_prefork:notice] [pid 29836] AH00169: caught SIGTERM, shutting down
[Tue Jan 28 13:42:46.247865 2020] [wsgi:warn] [pid 30546] mod_wsgi: Compiled for Python/2.7.11.
[Tue Jan 28 13:42:46.247900 2020] [wsgi:warn] [pid 30546] mod_wsgi: Runtime using Python/2.7.12.
[Tue Jan 28 13:42:46.249400 2020] [mpm_prefork:notice] [pid 30546] AH00163: Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g mod_wsgi/4.3.0 Python/2.7.12 configured -- resuming normal operations
[Tue Jan 28 13:42:46.249425 2020] [core:notice] [pid 30546] AH00094: Command line: '/usr/sbin/apache2'
[Tue Jan 28 13:50:42.498226 2020] [wsgi:error] [pid 30550] [remote 10.128.86.140:56937] mod_wsgi (pid=30550): Exception occurred processing WSGI script '/home/geonode/ermis/ermis/wsgi.py'.
[Tue Jan 28 13:50:42.499817 2020] [wsgi:error] [pid 30550] [remote 10.128.86.140:56937] IOError: failed to write data
[Tue Jan 28 13:50:42.505624 2020] [wsgi:error] [pid 30549] Internal Server Error: /api/o/v4/tokeninfo/
[Tue Jan 28 13:50:42.505649 2020] [wsgi:error] [pid 30549] Traceback (most recent call last):
[Tue Jan 28 13:50:42.505652 2020] [wsgi:error] [pid 30549]   File "/home/geo/Envs/geonode/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
[Tue Jan 28 13:50:42.505654 2020] [wsgi:error] [pid 30549]     response = get_response(request)
[Tue Jan 28 13:50:42.505656 2020] [wsgi:error] [pid 30549]   File "/home/geo/Envs/geonode/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
[Tue Jan 28 13:50:42.505659 2020] [wsgi:error] [pid 30549]     response = self._get_response(request)
[Tue Jan 28 13:50:42.505661 2020] [wsgi:error] [pid 30549]   File "/home/geo/Envs/geonode/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
[Tue Jan 28 13:50:42.505663 2020] [wsgi:error] [pid 30549]     response = self.process_exception_by_middleware(e, request)
[Tue Jan 28 13:50:42.505666 2020] [wsgi:error] [pid 30549]   File "/home/geo/Envs/geonode/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
[Tue Jan 28 13:50:42.505668 2020] [wsgi:error] [pid 30549]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Tue Jan 28 13:50:42.505670 2020] [wsgi:error] [pid 30549]   File "/home/geo/Envs/geonode/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
[Tue Jan 28 13:50:42.505688 2020] [wsgi:error] [pid 30549]     return view_func(*args, **kwargs)
[Tue Jan 28 13:50:42.505690 2020] [wsgi:error] [pid 30549]   File "/home/geo/Envs/geonode/src/geonode/geonode/api/views.py", line 140, in verify_token
[Tue Jan 28 13:50:42.505693 2020] [wsgi:error] [pid 30549]     if (request.POST and 'token' in request.POST):
[Tue Jan 28 13:50:42.505695 2020] [wsgi:error] [pid 30549]   File "/home/geo/Envs/geonode/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 126, in _get_post
[Tue Jan 28 13:50:42.505697 2020] [wsgi:error] [pid 30549]     self._load_post_and_files()
[Tue Jan 28 13:50:42.505699 2020] [wsgi:error] [pid 30549]   File "/home/geo/Envs/geonode/lib/python2.7/site-packages/django/http/request.py", line 311, in _load_post_and_files
[Tue Jan 28 13:50:42.505701 2020] [wsgi:error] [pid 30549]     self._post, self._files = QueryDict(self.body, encoding=self._encoding), MultiValueDict()
[Tue Jan 28 13:50:42.505704 2020] [wsgi:error] [pid 30549]   File "/home/geo/Envs/geonode/lib/python2.7/site-packages/django/http/request.py", line 274, in body
[Tue Jan 28 13:50:42.505706 2020] [wsgi:error] [pid 30549]     six.reraise(UnreadablePostError, UnreadablePostError(*e.args), sys.exc_info()[2])
[Tue Jan 28 13:50:42.505708 2020] [wsgi:error] [pid 30549]   File "/home/geo/Envs/geonode/lib/python2.7/site-packages/django/http/request.py", line 272, in body
[Tue Jan 28 13:50:42.505710 2020] [wsgi:error] [pid 30549]     self._body = self.read()
[Tue Jan 28 13:50:42.505712 2020] [wsgi:error] [pid 30549]   File "/home/geo/Envs/geonode/lib/python2.7/site-packages/django/http/request.py", line 333, in read
[Tue Jan 28 13:50:42.505715 2020] [wsgi:error] [pid 30549]     six.reraise(UnreadablePostError, UnreadablePostError(*e.args), sys.exc_info()[2])
[Tue Jan 28 13:50:42.505717 2020] [wsgi:error] [pid 30549]   File "/home/geo/Envs/geonode/lib/python2.7/site-packages/django/http/request.py", line 331, in read
[Tue Jan 28 13:50:42.505719 2020] [wsgi:error] [pid 30549]     return self._stream.read(*args, **kwargs)
[Tue Jan 28 13:50:42.505721 2020] [wsgi:error] [pid 30549]   File "/home/geo/Envs/geonode/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 47, in read
[Tue Jan 28 13:50:42.505724 2020] [wsgi:error] [pid 30549]     result = self.buffer + self._read_limited()
[Tue Jan 28 13:50:42.505726 2020] [wsgi:error] [pid 30549]   File "/home/geo/Envs/geonode/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 41, in _read_limited
[Tue Jan 28 13:50:42.505734 2020] [wsgi:error] [pid 30549]     result = self.stream.read(size)
[Tue Jan 28 13:50:42.505736 2020] [wsgi:error] [pid 30549] UnreadablePostError: request data read error
[Tue Jan 28 13:50:42.572401 2020] [mpm_prefork:notice] [pid 30546] AH00169: caught SIGTERM, shutting down
[Tue Jan 28 13:50:42.608571 2020] [wsgi:error] [pid 30549] [remote 10.128.86.140:56937] mod_wsgi (pid=30549): Exception occurred processing WSGI script '/home/geonode/ermis/ermis/wsgi.py'.
[Tue Jan 28 13:50:42.608619 2020] [wsgi:error] [pid 30549] [remote 10.128.86.140:56937] IOError: failed to write data
[Tue Jan 28 13:50:43.618124 2020] [wsgi:warn] [pid 575] mod_wsgi: Compiled for Python/2.7.11.
[Tue Jan 28 13:50:43.618162 2020] [wsgi:warn] [pid 575] mod_wsgi: Runtime using Python/2.7.12.
[Tue Jan 28 13:50:43.619680 2020] [mpm_prefork:notice] [pid 575] AH00163: Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g mod_wsgi/4.3.0 Python/2.7.12 configured -- resuming normal operations
[Tue Jan 28 13:50:43.619698 2020] [core:notice] [pid 575] AH00094: Command line: '/usr/sbin/apache2'
[Tue Jan 28 13:51:02.612137 2020] [wsgi:error] [pid 581] Loading user configuration
[Tue Jan 28 13:51:02.612647 2020] [wsgi:error] [pid 581] running configuration <ConfigParser.SafeConfigParser instance at 0x7fa01e7ecdd0>
[Tue Jan 28 13:51:02.612740 2020] [wsgi:error] [pid 581] Setting language
[Tue Jan 28 13:51:02.613465 2020] [wsgi:error] [pid 581] Loading custom repository mappings from /home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py
[Tue Jan 28 13:51:02.613582 2020] [wsgi:error] [pid 581] Loading outputschemas
[Tue Jan 28 13:51:02.614097 2020] [wsgi:error] [pid 581] Setting MaxRecordDefault
[Tue Jan 28 13:51:02.778411 2020] [wsgi:error] [pid 581] Querying repository with ids: b9d1dbec-99bd-11e9-a5ca-000c29291400
[Tue Jan 28 13:51:02.801889 2020] [wsgi:error] [pid 581] Request processed
[Tue Jan 28 13:51:02.802000 2020] [wsgi:error] [pid 581] Writing response.
[Tue Jan 28 13:51:02.804328 2020] [wsgi:error] [pid 581] /home/geo/Envs/geonode/lib/python2.7/site-packages/owslib/iso.py:117: FutureWarning: the .identification and .serviceidentification properties will merge into .identification being a list of properties.  This is currently implemented in .identificationinfo.  Please see https://github.com/geopython/OWSLib/issues/38 for more information
[Tue Jan 28 13:51:02.804340 2020] [wsgi:error] [pid 581]   FutureWarning)
[Tue Jan 28 13:51:02.805080 2020] [wsgi:error] [pid 581] /home/geo/Envs/geonode/lib/python2.7/site-packages/owslib/iso.py:482: FutureWarning: The .keywords and .keywords2 properties will merge into the .keywords property in the future, with .keywords becoming a list of MD_Keywords instances. This is currently implemented in .keywords2. Please see https://github.com/geopython/OWSLib/issues/301 for more information
[Tue Jan 28 13:51:02.805085 2020] [wsgi:error] [pid 581]   FutureWarning)
[Tue Jan 28 13:51:40.840465 2020] [wsgi:error] [pid 581] Loading user configuration
[Tue Jan 28 13:51:40.840980 2020] [wsgi:error] [pid 581] running configuration <ConfigParser.SafeConfigParser instance at 0x7fa01da61c20>
[Tue Jan 28 13:51:40.841072 2020] [wsgi:error] [pid 581] Setting language
[Tue Jan 28 13:51:40.842966 2020] [wsgi:error] [pid 581] Loading custom repository mappings from /home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py
[Tue Jan 28 13:51:40.843095 2020] [wsgi:error] [pid 581] Loading outputschemas
[Tue Jan 28 13:51:40.843195 2020] [wsgi:error] [pid 581] Setting MaxRecordDefault
[Tue Jan 28 13:51:40.843715 2020] [wsgi:error] [pid 581] Querying repository with ids: 9fb32564-3dbd-11ea-a5ca-000c29291400
[Tue Jan 28 13:51:40.856088 2020] [wsgi:error] [pid 581] Request processed
[Tue Jan 28 13:51:40.856141 2020] [wsgi:error] [pid 581] Writing response.
[Tue Jan 28 13:53:33.808728 2020] [wsgi:error] [pid 586] Loading user configuration
[Tue Jan 28 13:53:33.809259 2020] [wsgi:error] [pid 586] running configuration <ConfigParser.SafeConfigParser instance at 0x7fa01e6893f8>
[Tue Jan 28 13:53:33.809349 2020] [wsgi:error] [pid 586] Setting language
[Tue Jan 28 13:53:33.810132 2020] [wsgi:error] [pid 586] Loading custom repository mappings from /home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py
[Tue Jan 28 13:53:33.810255 2020] [wsgi:error] [pid 586] Loading outputschemas
[Tue Jan 28 13:53:33.810773 2020] [wsgi:error] [pid 586] Setting MaxRecordDefault
[Tue Jan 28 13:53:33.896501 2020] [wsgi:error] [pid 586] Querying repository with ids: b9d1dbec-99bd-11e9-a5ca-000c29291400
[Tue Jan 28 13:53:33.917141 2020] [wsgi:error] [pid 586] Request processed
[Tue Jan 28 13:53:33.917205 2020] [wsgi:error] [pid 586] Writing response.
[Tue Jan 28 13:53:33.919524 2020] [wsgi:error] [pid 586] /home/geo/Envs/geonode/lib/python2.7/site-packages/owslib/iso.py:117: FutureWarning: the .identification and .serviceidentification properties will merge into .identification being a list of properties.  This is currently implemented in .identificationinfo.  Please see https://github.com/geopython/OWSLib/issues/38 for more information
[Tue Jan 28 13:53:33.919536 2020] [wsgi:error] [pid 586]   FutureWarning)
[Tue Jan 28 13:53:33.920287 2020] [wsgi:error] [pid 586] /home/geo/Envs/geonode/lib/python2.7/site-packages/owslib/iso.py:482: FutureWarning: The .keywords and .keywords2 properties will merge into the .keywords property in the future, with .keywords becoming a list of MD_Keywords instances. This is currently implemented in .keywords2. Please see https://github.com/geopython/OWSLib/issues/301 for more information
[Tue Jan 28 13:53:33.920294 2020] [wsgi:error] [pid 586]   FutureWarning)
[Tue Jan 28 13:53:42.037722 2020] [wsgi:error] [pid 581] Loading user configuration
[Tue Jan 28 13:53:42.037848 2020] [wsgi:error] [pid 581] running configuration <ConfigParser.SafeConfigParser instance at 0x7fa01d6b1680>
[Tue Jan 28 13:53:42.037924 2020] [wsgi:error] [pid 581] Setting language
[Tue Jan 28 13:53:42.038344 2020] [wsgi:error] [pid 581] Loading custom repository mappings from /home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py
[Tue Jan 28 13:53:42.038451 2020] [wsgi:error] [pid 581] Loading outputschemas
[Tue Jan 28 13:53:42.038546 2020] [wsgi:error] [pid 581] Setting MaxRecordDefault
[Tue Jan 28 13:53:42.039019 2020] [wsgi:error] [pid 581] Querying repository with ids: b9d1dbec-99bd-11e9-a5ca-000c29291400
[Tue Jan 28 13:53:42.050617 2020] [wsgi:error] [pid 581] Request processed
[Tue Jan 28 13:53:42.050672 2020] [wsgi:error] [pid 581] Writing response.
[Tue Jan 28 13:53:42.728885 2020] [wsgi:error] [pid 581] There is already a style named HistoricFlood110912_14
[Tue Jan 28 13:53:42.728901 2020] [wsgi:error] [pid 581] Traceback (most recent call last):
[Tue Jan 28 13:53:42.728905 2020] [wsgi:error] [pid 581]   File "/home/geo/Envs/geonode/src/geonode/geonode/geoserver/helpers.py", line 343, in set_layer_style
[Tue Jan 28 13:53:42.728909 2020] [wsgi:error] [pid 581]     cat.create_style(saved_layer.name, sld, raw=True, workspace=settings.DEFAULT_WORKSPACE)
[Tue Jan 28 13:53:42.728913 2020] [wsgi:error] [pid 581]   File "/home/geo/Envs/geonode/lib/python2.7/site-packages/geoserver/catalog.py", line 962, in create_style
[Tue Jan 28 13:53:42.728916 2020] [wsgi:error] [pid 581]     raise ConflictingDataError("There is already a style named %s" % name)
[Tue Jan 28 13:53:42.728920 2020] [wsgi:error] [pid 581] ConflictingDataError: There is already a style named HistoricFlood110912_14
[Tue Jan 28 13:53:42.941389 2020] [wsgi:error] [pid 581] ... Creating Thumbnail for Layer [geonode:HistoricFlood110912_14]
[Tue Jan 28 13:53:43.104427 2020] [wsgi:error] [pid 581] Loading user configuration
[Tue Jan 28 13:53:43.104545 2020] [wsgi:error] [pid 581] running configuration <ConfigParser.SafeConfigParser instance at 0x7fa01d9514d0>
[Tue Jan 28 13:53:43.104621 2020] [wsgi:error] [pid 581] Setting language
[Tue Jan 28 13:53:43.105043 2020] [wsgi:error] [pid 581] Loading custom repository mappings from /home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py
[Tue Jan 28 13:53:43.105156 2020] [wsgi:error] [pid 581] Loading outputschemas
[Tue Jan 28 13:53:43.105250 2020] [wsgi:error] [pid 581] Setting MaxRecordDefault
[Tue Jan 28 13:53:43.105773 2020] [wsgi:error] [pid 581] Querying repository with ids: b9d1dbec-99bd-11e9-a5ca-000c29291400
[Tue Jan 28 13:53:43.117263 2020] [wsgi:error] [pid 581] Request processed
[Tue Jan 28 13:53:43.117321 2020] [wsgi:error] [pid 581] Writing response.
[Tue Jan 28 13:53:43.226886 2020] [wsgi:error] [pid 586] Loading user configuration
[Tue Jan 28 13:53:43.227389 2020] [wsgi:error] [pid 586] running configuration <ConfigParser.SafeConfigParser instance at 0x7fa01da845f0>
[Tue Jan 28 13:53:43.227478 2020] [wsgi:error] [pid 586] Setting language
[Tue Jan 28 13:53:43.228156 2020] [wsgi:error] [pid 586] Loading custom repository mappings from /home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py
[Tue Jan 28 13:53:43.228266 2020] [wsgi:error] [pid 586] Loading outputschemas
[Tue Jan 28 13:53:43.228363 2020] [wsgi:error] [pid 586] Setting MaxRecordDefault
[Tue Jan 28 13:53:43.228847 2020] [wsgi:error] [pid 586] Querying repository with ids: b9d1dbec-99bd-11e9-a5ca-000c29291400
[Tue Jan 28 13:53:43.242385 2020] [wsgi:error] [pid 586] Request processed
[Tue Jan 28 13:53:43.242438 2020] [wsgi:error] [pid 586] Writing response.
[Tue Jan 28 13:55:13.203805 2020] [wsgi:error] [pid 586] Loading user configuration
[Tue Jan 28 13:55:13.203935 2020] [wsgi:error] [pid 586] running configuration <ConfigParser.SafeConfigParser instance at 0x7fa01e7672d8>
[Tue Jan 28 13:55:13.204013 2020] [wsgi:error] [pid 586] Setting language
[Tue Jan 28 13:55:13.204423 2020] [wsgi:error] [pid 586] Loading custom repository mappings from /home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py
[Tue Jan 28 13:55:13.204530 2020] [wsgi:error] [pid 586] Loading outputschemas
[Tue Jan 28 13:55:13.204626 2020] [wsgi:error] [pid 586] Setting MaxRecordDefault
[Tue Jan 28 13:55:13.205133 2020] [wsgi:error] [pid 586] Querying repository with ids: 9fb32564-3dbd-11ea-a5ca-000c29291400
[Tue Jan 28 13:55:13.217956 2020] [wsgi:error] [pid 586] Request processed
[Tue Jan 28 13:55:13.218009 2020] [wsgi:error] [pid 586] Writing response.
[Tue Jan 28 14:01:25.265453 2020] [mpm_prefork:notice] [pid 575] AH00169: caught SIGTERM, shutting down
[Tue Jan 28 14:01:26.305668 2020] [wsgi:warn] [pid 3666] mod_wsgi: Compiled for Python/2.7.11.
[Tue Jan 28 14:01:26.305729 2020] [wsgi:warn] [pid 3666] mod_wsgi: Runtime using Python/2.7.12.
[Tue Jan 28 14:01:26.308050 2020] [mpm_prefork:notice] [pid 3666] AH00163: Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g mod_wsgi/4.3.0 Python/2.7.12 configured -- resuming normal operations
[Tue Jan 28 14:01:26.308077 2020] [core:notice] [pid 3666] AH00094: Command line: '/usr/sbin/apache2'
[Tue Jan 28 14:12:07.888097 2020] [mpm_prefork:notice] [pid 3666] AH00169: caught SIGTERM, shutting down
[Tue Jan 28 14:12:09.005828 2020] [wsgi:warn] [pid 4626] mod_wsgi: Compiled for Python/2.7.11.
[Tue Jan 28 14:12:09.005867 2020] [wsgi:warn] [pid 4626] mod_wsgi: Runtime using Python/2.7.12.
[Tue Jan 28 14:12:09.007408 2020] [mpm_prefork:notice] [pid 4626] AH00163: Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g mod_wsgi/4.3.0 Python/2.7.12 configured -- resuming normal operations
[Tue Jan 28 14:12:09.007431 2020] [core:notice] [pid 4626] AH00094: Command line: '/usr/sbin/apache2'
[Tue Jan 28 14:15:03.485809 2020] [wsgi:error] [pid 4629] Loading user configuration
[Tue Jan 28 14:15:03.486502 2020] [wsgi:error] [pid 4629] running configuration <ConfigParser.SafeConfigParser instance at 0x7f6d0d1cb560>
[Tue Jan 28 14:15:03.486603 2020] [wsgi:error] [pid 4629] Setting language
[Tue Jan 28 14:15:03.487351 2020] [wsgi:error] [pid 4629] Loading custom repository mappings from /home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py
[Tue Jan 28 14:15:03.487459 2020] [wsgi:error] [pid 4629] Loading outputschemas
[Tue Jan 28 14:15:03.487915 2020] [wsgi:error] [pid 4629] Setting MaxRecordDefault
[Tue Jan 28 14:15:03.571721 2020] [wsgi:error] [pid 4629] Querying repository with ids: 9fb32564-3dbd-11ea-a5ca-000c29291400
[Tue Jan 28 14:15:03.591966 2020] [wsgi:error] [pid 4629] Request processed
[Tue Jan 28 14:15:03.592030 2020] [wsgi:error] [pid 4629] Writing response.
[Tue Jan 28 14:15:03.594309 2020] [wsgi:error] [pid 4629] /home/geo/Envs/geonode/lib/python2.7/site-packages/owslib/iso.py:117: FutureWarning: the .identification and .serviceidentification properties will merge into .identification being a list of properties.  This is currently implemented in .identificationinfo.  Please see https://github.com/geopython/OWSLib/issues/38 for more information
[Tue Jan 28 14:15:03.594322 2020] [wsgi:error] [pid 4629]   FutureWarning)
[Tue Jan 28 14:15:03.595135 2020] [wsgi:error] [pid 4629] /home/geo/Envs/geonode/lib/python2.7/site-packages/owslib/iso.py:482: FutureWarning: The .keywords and .keywords2 properties will merge into the .keywords property in the future, with .keywords becoming a list of MD_Keywords instances. This is currently implemented in .keywords2. Please see https://github.com/geopython/OWSLib/issues/301 for more information
[Tue Jan 28 14:15:03.595142 2020] [wsgi:error] [pid 4629]   FutureWarning)
[Tue Jan 28 14:22:25.307371 2020] [wsgi:error] [pid 4629] Loading user configuration
[Tue Jan 28 14:22:25.307933 2020] [wsgi:error] [pid 4629] running configuration <ConfigParser.SafeConfigParser instance at 0x7f6d0c4d9ea8>
[Tue Jan 28 14:22:25.308030 2020] [wsgi:error] [pid 4629] Setting language
[Tue Jan 28 14:22:25.308704 2020] [wsgi:error] [pid 4629] Loading custom repository mappings from /home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py
[Tue Jan 28 14:22:25.308816 2020] [wsgi:error] [pid 4629] Loading outputschemas
[Tue Jan 28 14:22:25.308929 2020] [wsgi:error] [pid 4629] Setting MaxRecordDefault
[Tue Jan 28 14:22:25.309468 2020] [wsgi:error] [pid 4629] Querying repository with ids: 9fb32564-3dbd-11ea-a5ca-000c29291400
[Tue Jan 28 14:22:25.322193 2020] [wsgi:error] [pid 4629] Request processed
[Tue Jan 28 14:22:25.322253 2020] [wsgi:error] [pid 4629] Writing response.
[Tue Jan 28 14:23:52.817150 2020] [wsgi:error] [pid 4629] Loading user configuration
[Tue Jan 28 14:23:52.817279 2020] [wsgi:error] [pid 4629] running configuration <ConfigParser.SafeConfigParser instance at 0x7f6d0c477ef0>
[Tue Jan 28 14:23:52.817356 2020] [wsgi:error] [pid 4629] Setting language
[Tue Jan 28 14:23:52.817842 2020] [wsgi:error] [pid 4629] Loading custom repository mappings from /home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py
[Tue Jan 28 14:23:52.817961 2020] [wsgi:error] [pid 4629] Loading outputschemas
[Tue Jan 28 14:23:52.818060 2020] [wsgi:error] [pid 4629] Setting MaxRecordDefault
[Tue Jan 28 14:23:52.818574 2020] [wsgi:error] [pid 4629] Querying repository with ids: 9fb32564-3dbd-11ea-a5ca-000c29291400
[Tue Jan 28 14:23:52.831158 2020] [wsgi:error] [pid 4629] Request processed
[Tue Jan 28 14:23:52.831215 2020] [wsgi:error] [pid 4629] Writing response.
[Tue Jan 28 14:23:58.813711 2020] [wsgi:error] [pid 4629] Loading user configuration
[Tue Jan 28 14:23:58.813858 2020] [wsgi:error] [pid 4629] running configuration <ConfigParser.SafeConfigParser instance at 0x7f6d0c2a5dd0>
[Tue Jan 28 14:23:58.813935 2020] [wsgi:error] [pid 4629] Setting language
[Tue Jan 28 14:23:58.814373 2020] [wsgi:error] [pid 4629] Loading custom repository mappings from /home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py
[Tue Jan 28 14:23:58.814481 2020] [wsgi:error] [pid 4629] Loading outputschemas
[Tue Jan 28 14:23:58.814578 2020] [wsgi:error] [pid 4629] Setting MaxRecordDefault
[Tue Jan 28 14:23:58.815268 2020] [wsgi:error] [pid 4629] Querying repository with ids: 9fb32564-3dbd-11ea-a5ca-000c29291400
[Tue Jan 28 14:23:58.827376 2020] [wsgi:error] [pid 4629] Request processed
[Tue Jan 28 14:23:58.827436 2020] [wsgi:error] [pid 4629] Writing response.
[Tue Jan 28 14:24:10.642772 2020] [wsgi:error] [pid 4630] Loading user configuration
[Tue Jan 28 14:24:10.643272 2020] [wsgi:error] [pid 4630] running configuration <ConfigParser.SafeConfigParser instance at 0x7f6d0cfc7950>
[Tue Jan 28 14:24:10.643365 2020] [wsgi:error] [pid 4630] Setting language
[Tue Jan 28 14:24:10.644134 2020] [wsgi:error] [pid 4630] Loading custom repository mappings from /home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py
[Tue Jan 28 14:24:10.644255 2020] [wsgi:error] [pid 4630] Loading outputschemas
[Tue Jan 28 14:24:10.644753 2020] [wsgi:error] [pid 4630] Setting MaxRecordDefault
[Tue Jan 28 14:24:10.726215 2020] [wsgi:error] [pid 4630] Querying repository with ids: 9fb32564-3dbd-11ea-a5ca-000c29291400
[Tue Jan 28 14:24:10.742065 2020] [wsgi:error] [pid 4630] Request processed
[Tue Jan 28 14:24:10.742126 2020] [wsgi:error] [pid 4630] Writing response.
[Tue Jan 28 14:24:10.743873 2020] [wsgi:error] [pid 4630] /home/geo/Envs/geonode/lib/python2.7/site-packages/owslib/iso.py:117: FutureWarning: the .identification and .serviceidentification properties will merge into .identification being a list of properties.  This is currently implemented in .identificationinfo.  Please see https://github.com/geopython/OWSLib/issues/38 for more information
[Tue Jan 28 14:24:10.743885 2020] [wsgi:error] [pid 4630]   FutureWarning)
[Tue Jan 28 14:24:10.744620 2020] [wsgi:error] [pid 4630] /home/geo/Envs/geonode/lib/python2.7/site-packages/owslib/iso.py:482: FutureWarning: The .keywords and .keywords2 properties will merge into the .keywords property in the future, with .keywords becoming a list of MD_Keywords instances. This is currently implemented in .keywords2. Please see https://github.com/geopython/OWSLib/issues/301 for more information
[Tue Jan 28 14:24:10.744625 2020] [wsgi:error] [pid 4630]   FutureWarning)
[Tue Jan 28 14:31:14.648776 2020] [wsgi:error] [pid 4629] Loading user configuration
[Tue Jan 28 14:31:14.648904 2020] [wsgi:error] [pid 4629] running configuration <ConfigParser.SafeConfigParser instance at 0x7f6d0c60d7e8>
[Tue Jan 28 14:31:14.648982 2020] [wsgi:error] [pid 4629] Setting language
[Tue Jan 28 14:31:14.649447 2020] [wsgi:error] [pid 4629] Loading custom repository mappings from /home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py
[Tue Jan 28 14:31:14.649555 2020] [wsgi:error] [pid 4629] Loading outputschemas
[Tue Jan 28 14:31:14.649651 2020] [wsgi:error] [pid 4629] Setting MaxRecordDefault
[Tue Jan 28 14:31:14.650183 2020] [wsgi:error] [pid 4629] Querying repository with ids: 9fb32564-3dbd-11ea-a5ca-000c29291400
[Tue Jan 28 14:31:14.662402 2020] [wsgi:error] [pid 4629] Request processed
[Tue Jan 28 14:31:14.662457 2020] [wsgi:error] [pid 4629] Writing response.
[Tue Jan 28 14:31:45.516678 2020] [wsgi:error] [pid 4630] Loading user configuration
[Tue Jan 28 14:31:45.517242 2020] [wsgi:error] [pid 4630] running configuration <ConfigParser.SafeConfigParser instance at 0x7f6d07e5f3b0>
[Tue Jan 28 14:31:45.517338 2020] [wsgi:error] [pid 4630] Setting language
[Tue Jan 28 14:31:45.518106 2020] [wsgi:error] [pid 4630] Loading custom repository mappings from /home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py
[Tue Jan 28 14:31:45.518225 2020] [wsgi:error] [pid 4630] Loading outputschemas
[Tue Jan 28 14:31:45.518333 2020] [wsgi:error] [pid 4630] Setting MaxRecordDefault
[Tue Jan 28 14:31:45.518923 2020] [wsgi:error] [pid 4630] Querying repository with ids: 9fb32564-3dbd-11ea-a5ca-000c29291400
[Tue Jan 28 14:31:45.531380 2020] [wsgi:error] [pid 4630] Request processed
[Tue Jan 28 14:31:45.531434 2020] [wsgi:error] [pid 4630] Writing response.
[Tue Jan 28 14:50:11.571866 2020] [mpm_prefork:notice] [pid 4626] AH00169: caught SIGTERM, shutting down
[Tue Jan 28 14:50:12.613968 2020] [wsgi:warn] [pid 7706] mod_wsgi: Compiled for Python/2.7.11.
[Tue Jan 28 14:50:12.614013 2020] [wsgi:warn] [pid 7706] mod_wsgi: Runtime using Python/2.7.12.
[Tue Jan 28 14:50:12.616152 2020] [mpm_prefork:notice] [pid 7706] AH00163: Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g mod_wsgi/4.3.0 Python/2.7.12 configured -- resuming normal operations
[Tue Jan 28 14:50:12.616191 2020] [core:notice] [pid 7706] AH00094: Command line: '/usr/sbin/apache2'
[Tue Jan 28 14:51:29.796154 2020] [wsgi:error] [pid 7710] Loading user configuration
[Tue Jan 28 14:51:29.796904 2020] [wsgi:error] [pid 7710] running configuration <ConfigParser.SafeConfigParser instance at 0x7f77260fa7a0>
[Tue Jan 28 14:51:29.797042 2020] [wsgi:error] [pid 7710] Setting language
[Tue Jan 28 14:51:29.798210 2020] [wsgi:error] [pid 7710] Loading custom repository mappings from /home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py
[Tue Jan 28 14:51:29.798385 2020] [wsgi:error] [pid 7710] Loading outputschemas
[Tue Jan 28 14:51:29.799048 2020] [wsgi:error] [pid 7710] Setting MaxRecordDefault
[Tue Jan 28 14:51:30.032024 2020] [wsgi:error] [pid 7710] Querying repository with ids: 9fb32564-3dbd-11ea-a5ca-000c29291400
[Tue Jan 28 14:51:30.051351 2020] [wsgi:error] [pid 7710] Request processed
[Tue Jan 28 14:51:30.051436 2020] [wsgi:error] [pid 7710] Writing response.
[Tue Jan 28 14:51:30.055295 2020] [wsgi:error] [pid 7710] /home/geo/Envs/geonode/lib/python2.7/site-packages/owslib/iso.py:117: FutureWarning: the .identification and .serviceidentification properties will merge into .identification being a list of properties.  This is currently implemented in .identificationinfo.  Please see https://github.com/geopython/OWSLib/issues/38 for more information
[Tue Jan 28 14:51:30.055310 2020] [wsgi:error] [pid 7710]   FutureWarning)
[Tue Jan 28 14:51:30.056664 2020] [wsgi:error] [pid 7710] /home/geo/Envs/geonode/lib/python2.7/site-packages/owslib/iso.py:482: FutureWarning: The .keywords and .keywords2 properties will merge into the .keywords property in the future, with .keywords becoming a list of MD_Keywords instances. This is currently implemented in .keywords2. Please see https://github.com/geopython/OWSLib/issues/301 for more information
[Tue Jan 28 14:51:30.056674 2020] [wsgi:error] [pid 7710]   FutureWarning)
[Tue Jan 28 14:51:30.689415 2020] [wsgi:error] [pid 7710] There is already a style named Mean_temp_aegean1
[Tue Jan 28 14:51:30.689432 2020] [wsgi:error] [pid 7710] Traceback (most recent call last):
[Tue Jan 28 14:51:30.689435 2020] [wsgi:error] [pid 7710]   File "/home/geo/Envs/geonode/src/geonode/geonode/geoserver/helpers.py", line 343, in set_layer_style
[Tue Jan 28 14:51:30.689437 2020] [wsgi:error] [pid 7710]     cat.create_style(saved_layer.name, sld, raw=True, workspace=settings.DEFAULT_WORKSPACE)
[Tue Jan 28 14:51:30.689440 2020] [wsgi:error] [pid 7710]   File "/home/geo/Envs/geonode/lib/python2.7/site-packages/geoserver/catalog.py", line 962, in create_style
[Tue Jan 28 14:51:30.689443 2020] [wsgi:error] [pid 7710]     raise ConflictingDataError("There is already a style named %s" % name)
[Tue Jan 28 14:51:30.689445 2020] [wsgi:error] [pid 7710] ConflictingDataError: There is already a style named Mean_temp_aegean1
[Tue Jan 28 14:51:30.822413 2020] [wsgi:error] [pid 7710] ... Creating Thumbnail for Layer [geonode:Mean_temp_aegean1]
[Tue Jan 28 14:51:30.898135 2020] [wsgi:error] [pid 7710] Loading user configuration
[Tue Jan 28 14:51:30.898623 2020] [wsgi:error] [pid 7710] running configuration <ConfigParser.SafeConfigParser instance at 0x7f7725480dd0>
[Tue Jan 28 14:51:30.898710 2020] [wsgi:error] [pid 7710] Setting language
[Tue Jan 28 14:51:30.899376 2020] [wsgi:error] [pid 7710] Loading custom repository mappings from /home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py
[Tue Jan 28 14:51:30.899483 2020] [wsgi:error] [pid 7710] Loading outputschemas
[Tue Jan 28 14:51:30.899580 2020] [wsgi:error] [pid 7710] Setting MaxRecordDefault
[Tue Jan 28 14:51:30.900051 2020] [wsgi:error] [pid 7710] Querying repository with ids: 9fb32564-3dbd-11ea-a5ca-000c29291400
[Tue Jan 28 14:51:30.909713 2020] [wsgi:error] [pid 7710] Request processed
[Tue Jan 28 14:51:30.909768 2020] [wsgi:error] [pid 7710] Writing response.
[Tue Jan 28 14:51:47.083835 2020] [wsgi:error] [pid 7709] Loading user configuration
[Tue Jan 28 14:51:47.084333 2020] [wsgi:error] [pid 7709] running configuration <ConfigParser.SafeConfigParser instance at 0x7f772655fdd0>
[Tue Jan 28 14:51:47.084425 2020] [wsgi:error] [pid 7709] Setting language
[Tue Jan 28 14:51:47.085168 2020] [wsgi:error] [pid 7709] Loading custom repository mappings from /home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py
[Tue Jan 28 14:51:47.085283 2020] [wsgi:error] [pid 7709] Loading outputschemas
[Tue Jan 28 14:51:47.085790 2020] [wsgi:error] [pid 7709] Setting MaxRecordDefault
[Tue Jan 28 14:51:47.254997 2020] [wsgi:error] [pid 7709] Querying repository with ids: 9fb32564-3dbd-11ea-a5ca-000c29291400
[Tue Jan 28 14:51:47.269977 2020] [wsgi:error] [pid 7709] Request processed
[Tue Jan 28 14:51:47.270035 2020] [wsgi:error] [pid 7709] Writing response.
[Tue Jan 28 14:51:47.272220 2020] [wsgi:error] [pid 7709] /home/geo/Envs/geonode/lib/python2.7/site-packages/owslib/iso.py:117: FutureWarning: the .identification and .serviceidentification properties will merge into .identification being a list of properties.  This is currently implemented in .identificationinfo.  Please see https://github.com/geopython/OWSLib/issues/38 for more information
[Tue Jan 28 14:51:47.272231 2020] [wsgi:error] [pid 7709]   FutureWarning)
[Tue Jan 28 14:51:47.273041 2020] [wsgi:error] [pid 7709] /home/geo/Envs/geonode/lib/python2.7/site-packages/owslib/iso.py:482: FutureWarning: The .keywords and .keywords2 properties will merge into the .keywords property in the future, with .keywords becoming a list of MD_Keywords instances. This is currently implemented in .keywords2. Please see https://github.com/geopython/OWSLib/issues/301 for more information
[Tue Jan 28 14:51:47.273048 2020] [wsgi:error] [pid 7709]   FutureWarning)
[Tue Jan 28 14:51:57.163144 2020] [wsgi:error] [pid 7710] Loading user configuration
[Tue Jan 28 14:51:57.163264 2020] [wsgi:error] [pid 7710] running configuration <ConfigParser.SafeConfigParser instance at 0x7f77253ac878>
[Tue Jan 28 14:51:57.163341 2020] [wsgi:error] [pid 7710] Setting language
[Tue Jan 28 14:51:57.163763 2020] [wsgi:error] [pid 7710] Loading custom repository mappings from /home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py
[Tue Jan 28 14:51:57.163867 2020] [wsgi:error] [pid 7710] Loading outputschemas
[Tue Jan 28 14:51:57.163962 2020] [wsgi:error] [pid 7710] Setting MaxRecordDefault
[Tue Jan 28 14:51:57.164441 2020] [wsgi:error] [pid 7710] Querying repository with ids: 9fb32564-3dbd-11ea-a5ca-000c29291400
[Tue Jan 28 14:51:57.174000 2020] [wsgi:error] [pid 7710] Request processed
[Tue Jan 28 14:51:57.174052 2020] [wsgi:error] [pid 7710] Writing response.
[Tue Jan 28 14:51:57.680177 2020] [wsgi:error] [pid 7710] There is already a style named Mean_temp_aegean1
[Tue Jan 28 14:51:57.680196 2020] [wsgi:error] [pid 7710] Traceback (most recent call last):
[Tue Jan 28 14:51:57.680199 2020] [wsgi:error] [pid 7710]   File "/home/geo/Envs/geonode/src/geonode/geonode/geoserver/helpers.py", line 343, in set_layer_style
[Tue Jan 28 14:51:57.680201 2020] [wsgi:error] [pid 7710]     cat.create_style(saved_layer.name, sld, raw=True, workspace=settings.DEFAULT_WORKSPACE)
[Tue Jan 28 14:51:57.680204 2020] [wsgi:error] [pid 7710]   File "/home/geo/Envs/geonode/lib/python2.7/site-packages/geoserver/catalog.py", line 962, in create_style
[Tue Jan 28 14:51:57.680206 2020] [wsgi:error] [pid 7710]     raise ConflictingDataError("There is already a style named %s" % name)
[Tue Jan 28 14:51:57.680208 2020] [wsgi:error] [pid 7710] ConflictingDataError: There is already a style named Mean_temp_aegean1
[Tue Jan 28 14:51:57.801413 2020] [wsgi:error] [pid 7710] ... Creating Thumbnail for Layer [geonode:Mean_temp_aegean1]
[Tue Jan 28 14:51:57.872237 2020] [wsgi:error] [pid 7710] Loading user configuration
[Tue Jan 28 14:51:57.872348 2020] [wsgi:error] [pid 7710] running configuration <ConfigParser.SafeConfigParser instance at 0x7f772520aea8>
[Tue Jan 28 14:51:57.872431 2020] [wsgi:error] [pid 7710] Setting language
[Tue Jan 28 14:51:57.872836 2020] [wsgi:error] [pid 7710] Loading custom repository mappings from /home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py
[Tue Jan 28 14:51:57.872940 2020] [wsgi:error] [pid 7710] Loading outputschemas
[Tue Jan 28 14:51:57.873036 2020] [wsgi:error] [pid 7710] Setting MaxRecordDefault
[Tue Jan 28 14:51:57.873513 2020] [wsgi:error] [pid 7710] Querying repository with ids: 9fb32564-3dbd-11ea-a5ca-000c29291400
[Tue Jan 28 14:51:57.883233 2020] [wsgi:error] [pid 7710] Request processed
[Tue Jan 28 14:51:57.883285 2020] [wsgi:error] [pid 7710] Writing response.
[Tue Jan 28 14:51:58.177516 2020] [wsgi:error] [pid 7710] Loading user configuration
[Tue Jan 28 14:51:58.177654 2020] [wsgi:error] [pid 7710] running configuration <ConfigParser.SafeConfigParser instance at 0x7f7725203638>
[Tue Jan 28 14:51:58.178151 2020] [wsgi:error] [pid 7710] Setting language
[Tue Jan 28 14:51:58.178597 2020] [wsgi:error] [pid 7710] Loading custom repository mappings from /home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py
[Tue Jan 28 14:51:58.178709 2020] [wsgi:error] [pid 7710] Loading outputschemas
[Tue Jan 28 14:51:58.178805 2020] [wsgi:error] [pid 7710] Setting MaxRecordDefault
[Tue Jan 28 14:51:58.179295 2020] [wsgi:error] [pid 7710] Querying repository with ids: 9fb32564-3dbd-11ea-a5ca-000c29291400
[Tue Jan 28 14:51:58.193053 2020] [wsgi:error] [pid 7710] Request processed
[Tue Jan 28 14:51:58.193136 2020] [wsgi:error] [pid 7710] Writing response.
[Tue Jan 28 14:58:12.720275 2020] [wsgi:error] [pid 7709] Loading user configuration
[Tue Jan 28 14:58:12.720689 2020] [wsgi:error] [pid 7709] running configuration {'server': {'maxrecords': '10', 'domaincounts': 'true', 'language': 'el', 'encoding': 'UTF-8', 'url': 'https://geoportal.ermis-f.eu/catalogue/csw', 'home': '.', 'pretty_print': 'true', 'profiles': 'apiso,ebrim', 'domainquerytype': 'range'}, 'metadata:main': {'identification_fees': 'None', 'provider_url': 'https://geoportal.ermis-f.eu/', 'identification_keywords': 'sdi, catalogue, discovery, metadata, GeoNode', 'contact_address': 'Mailing Address', 'identification_accessconstraints': 'None', 'contact_name': 'Lastname, Firstname', 'contact_stateorprovince': 'Administrative Area', 'contact_country': 'Country', 'contact_url': 'Contact URL', 'provider_name': 'Organization Name', 'contact_phone': '+xx-xxx-xxx-xxxx', 'contact_hours': 'Hours of Service', 'contact_role': 'pointOfContact', 'contact_email': 'Email Address', 'identification_title': 'GeoNode Catalogue', 'contact_postalcode': 'Zip or Postal Code', 'contact_city': 'City', 'identification_keywords_type': 'theme', 'identification_abstract': 'GeoNode is an open source platform that facilitates the creation, sharing, and collaborative use of geospatial data', 'contact_fax': '+xx-xxx-xxx-xxxx', 'contact_instructions': 'During hours of service. Off on weekends.', 'contact_position': 'Position Title'}, 'repository': {'filter': 'is_published = true AND id IN (160, 113, 80, 85, 73, 30, 112, 55, 110, 116, 31, 117, 150, 129, 39, 38, 118, 56, 158, 98, 78, 32, 97, 265, 57, 22, 273, 81, 59, 23, 72, 37, 33, 42, 130, 95, 182, 94, 69, 102, 24, 96, 82, 26, 74, 34, 264, 70, 66, 35, 75, 83, 65, 173, 28, 58, 67, 46, 51, 36, 29, 60, 52, 62, 84, 255, 43, 174, 63, 41, 161, 124, 54, 64, 49, 257, 125, 25, 272, 149, 115, 27, 107, 263, 146, 126, 271, 50, 268, 269, 144, 127, 61, 143, 154, 270, 128, 145, 262, 44, 267, 48, 266, 47) AND alternate IS NOT NULL', 'source': 'geonode.catalogue.backends.pycsw_plugin.GeoNodeRepository', 'mappings': '/home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py'}, 'metadata:inspire': {'conformity_service': 'notEvaluated', 'contact_email': 'Email Address', 'languages_supported': 'eng,gre', 'date': 'YYYY-MM-DD', 'default_language': 'eng', 'contact_name': 'Organization Name', 'gemet_keywords': 'Utility and governmental services', 'enabled': 'true', 'temp_extent': 'YYYY-MM-DD/YYYY-MM-DD'}}
[Tue Jan 28 14:58:12.720793 2020] [wsgi:error] [pid 7709] Setting language
[Tue Jan 28 14:58:12.721717 2020] [wsgi:error] [pid 7709] Loading custom repository mappings from /home/geo/Envs/geonode/src/geonode/geonode/catalogue/backends/pycsw_local_mappings.py
[Tue Jan 28 14:58:12.721840 2020] [wsgi:error] [pid 7709] Loading outputschemas
[Tue Jan 28 14:58:12.722314 2020] [wsgi:error] [pid 7709] Setting MaxRecordDefault
[Tue Jan 28 14:58:12.722861 2020] [wsgi:error] [pid 7709] Querying repository with ids: 8b68c64e-99b8-11e9-a5ca-000c29291400
[Tue Jan 28 14:58:12.737903 2020] [wsgi:error] [pid 7709] Request processed
[Tue Jan 28 14:58:12.737956 2020] [wsgi:error] [pid 7709] Writing response.
[Tue Jan 28 15:10:25.923626 2020] [wsgi:error] [pid 7709] uploaded_files: [<InMemoryUploadedFile: \xce\x99\xcf\x81\xce\xbb\xce\xb1\xce\xbd\xce\xb4\xce\xb9\xce\xba\xce\xad\xcf\x82 \xce\x94\xce\xb9\xce\xb1\xce\xb2\xce\xac\xcf\x83\xce\xb5\xce\xb9\xcf\x82.shp (application/octet-stream)>, <InMemoryUploadedFile: \xce\x99\xcf\x81\xce\xbb\xce\xb1\xce\xbd\xce\xb4\xce\xb9\xce\xba\xce\xad\xcf\x82 \xce\x94\xce\xb9\xce\xb1\xce\xb2\xce\xac\xcf\x83\xce\xb5\xce\xb9\xcf\x82.sbn (application/octet-stream)>, <InMemoryUploadedFile: \xce\x99\xcf\x81\xce\xbb\xce\xb1\xce\xbd\xce\xb4\xce\xb9\xce\xba\xce\xad\xcf\x82 \xce\x94\xce\xb9\xce\xb1\xce\xb2\xce\xac\xcf\x83\xce\xb5\xce\xb9\xcf\x82.dbf (application/octet-stream)>, <InMemoryUploadedFile: \xce\x99\xcf\x81\xce\xbb\xce\xb1\xce\xbd\xce\xb4\xce\xb9\xce\xba\xce\xad\xcf\x82 \xce\x94\xce\xb9\xce\xb1\xce\xb2\xce\xac\xcf\x83\xce\xb5\xce\xb9\xcf\x82.prj (application/octet-stream)>, <InMemoryUploadedFile: \xce\x99\xcf\x81\xce\xbb\xce\xb1\xce\xbd\xce\xb4\xce\xb9\xce\xba\xce\xad\xcf\x82 \xce\x94\xce\xb9\xce\xb1\xce\xb2\xce\xac\xcf\x83\xce\xb5\xce\xb9\xcf\x82.sbx (application/octet-stream)>, <InMemoryUploadedFile: \xce\x99\xcf\x81\xce\xbb\xce\xb1\xce\xbd\xce\xb4\xce\xb9\xce\xba\xce\xad\xcf\x82 \xce\x94\xce\xb9\xce\xb1\xce\xb2\xce\xac\xcf\x83\xce\xb5\xce\xb9\xcf\x82.shx (application/octet-stream)>, <InMemoryUploadedFile: \xce\x99\xcf\x81\xce\xbb\xce\xb1\xce\xbd\xce\xb4\xce\xb9\xce\xba\xce\xad\xcf\x82 \xce\x94\xce\xb9\xce\xb1\xce\xb2\xce\xac\xcf\x83\xce\xb5\xce\xb9\xcf\x82.cpg (application/octet-stream)>]
[Tue Jan 28 15:10:25.925893 2020] [wsgi:error] [pid 7709] valid_extensions: [u'shp', 'dbf', 'shx', 'prj']
[Tue Jan 28 15:10:25.926939 2020] [wsgi:error] [pid 7709] \xce\x99\xcf\x81\xce\xbb\xce\xb1\xce\xbd\xce\xb4\xce\xb9\xce\xba\xce\xad\xcf\x82 \xce\x94\xce\xb9\xce\xb1\xce\xb2\xce\xac\xcf\x83\xce\xb5\xce\xb9\xcf\x82
[Tue Jan 28 15:10:25.928358 2020] [wsgi:error] [pid 7709] Name for layer: u'_'
[Tue Jan 28 15:10:26.033111 2020] [wsgi:error] [pid 7709] files_to_upload: [u'/tmp/tmpxcFe4w/_.shp', u'/tmp/tmpxcFe4w/_.shx', u'/tmp/tmpxcFe4w/_.dbf', u'/tmp/tmpxcFe4w/_.prj']
[Tue Jan 28 15:10:26.033170 2020] [wsgi:error] [pid 7709] Uploading featureType
[Tue Jan 28 15:10:26.037857 2020] [wsgi:error] [pid 7709] /home/geo/Envs/geonode/lib/python2.7/site-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
[Tue Jan 28 15:10:26.037870 2020] [wsgi:error] [pid 7709]   InsecureRequestWarning)
[Tue Jan 28 15:10:26.055930 2020] [wsgi:error] [pid 7709] /home/geo/Envs/geonode/lib/python2.7/site-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
[Tue Jan 28 15:10:26.055943 2020] [wsgi:error] [pid 7709]   InsecureRequestWarning)
[Tue Jan 28 15:10:26.073973 2020] [wsgi:error] [pid 7709] /home/geo/Envs/geonode/lib/python2.7/site-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
[Tue Jan 28 15:10:26.073993 2020] [wsgi:error] [pid 7709]   InsecureRequestWarning)
[Tue Jan 28 15:10:26.389309 2020] [wsgi:error] [pid 7709] Internal Server Error: /upload/check
[Tue Jan 28 15:10:26.389329 2020] [wsgi:error] [pid 7709] Traceback (most recent call last):
[Tue Jan 28 15:10:26.389332 2020] [wsgi:error] [pid 7709]   File "/home/geo/Envs/geonode/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
[Tue Jan 28 15:10:26.389336 2020] [wsgi:error] [pid 7709]     response = get_response(request)
[Tue Jan 28 15:10:26.389339 2020] [wsgi:error] [pid 7709]   File "/home/geo/Envs/geonode/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
[Tue Jan 28 15:10:26.389343 2020] [wsgi:error] [pid 7709]     response = self._get_response(request)
[Tue Jan 28 15:10:26.389347 2020] [wsgi:error] [pid 7709]   File "/home/geo/Envs/geonode/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
[Tue Jan 28 15:10:26.389350 2020] [wsgi:error] [pid 7709]     response = self.process_exception_by_middleware(e, request)
[Tue Jan 28 15:10:26.389354 2020] [wsgi:error] [pid 7709]   File "/home/geo/Envs/geonode/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
[Tue Jan 28 15:10:26.389357 2020] [wsgi:error] [pid 7709]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Tue Jan 28 15:10:26.389360 2020] [wsgi:error] [pid 7709]   File "/home/geo/Envs/geonode/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
[Tue Jan 28 15:10:26.389364 2020] [wsgi:error] [pid 7709]     return view_func(request, *args, **kwargs)
[Tue Jan 28 15:10:26.389367 2020] [wsgi:error] [pid 7709]   File "/home/geo/Envs/geonode/src/geonode/geonode/upload/views.py", line 639, in view
[Tue Jan 28 15:10:26.389371 2020] [wsgi:error] [pid 7709]     session = upload_obj.get_session()
[Tue Jan 28 15:10:26.389374 2020] [wsgi:error] [pid 7709]   File "/home/geo/Envs/geonode/src/geonode/geonode/upload/models.py", line 91, in get_session
[Tue Jan 28 15:10:26.389378 2020] [wsgi:error] [pid 7709]     return pickle.loads(str(self.session))
[Tue Jan 28 15:10:26.389381 2020] [wsgi:error] [pid 7709] UnicodeEncodeError: 'ascii' codec can't encode characters in position 1053-1057: ordinal not in range(128)
[Tue Jan 28 15:11:08.551967 2020] [wsgi:error] [pid 7709] uploaded_files: [<InMemoryUploadedFile: ir.shp (application/octet-stream)>, <InMemoryUploadedFile: ir.sbn (application/octet-stream)>, <InMemoryUploadedFile: ir.dbf (application/octet-stream)>, <InMemoryUploadedFile: ir.prj (application/octet-stream)>, <InMemoryUploadedFile: ir.sbx (application/octet-stream)>, <InMemoryUploadedFile: ir.shx (application/octet-stream)>, <InMemoryUploadedFile: ir.cpg (application/octet-stream)>]
[Tue Jan 28 15:11:08.552345 2020] [wsgi:error] [pid 7709] valid_extensions: [u'shp', 'dbf', 'shx', 'prj']
[Tue Jan 28 15:11:08.553005 2020] [wsgi:error] [pid 7709] ir
[Tue Jan 28 15:11:08.554386 2020] [wsgi:error] [pid 7709] Name for layer: u'ir'
[Tue Jan 28 15:11:08.657812 2020] [wsgi:error] [pid 7709] files_to_upload: [u'/tmp/tmpeNNyOf/ir.shp', u'/tmp/tmpeNNyOf/ir.dbf', u'/tmp/tmpeNNyOf/ir.shx', u'/tmp/tmpeNNyOf/ir.prj']
[Tue Jan 28 15:11:08.657872 2020] [wsgi:error] [pid 7709] Uploading featureType
[Tue Jan 28 15:11:08.661867 2020] [wsgi:error] [pid 7709] /home/geo/Envs/geonode/lib/python2.7/site-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
[Tue Jan 28 15:11:08.661883 2020] [wsgi:error] [pid 7709]   InsecureRequestWarning)
[Tue Jan 28 15:11:08.679832 2020] [wsgi:error] [pid 7709] /home/geo/Envs/geonode/lib/python2.7/site-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
[Tue Jan 28 15:11:08.679853 2020] [wsgi:error] [pid 7709]   InsecureRequestWarning)
[Tue Jan 28 15:11:08.695765 2020] [wsgi:error] [pid 7709] /home/geo/Envs/geonode/lib/python2.7/site-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
[Tue Jan 28 15:11:08.695776 2020] [wsgi:error] [pid 7709]   InsecureRequestWarning)
[Tue Jan 28 15:11:08.917343 2020] [wsgi:error] [pid 7709] Internal Server Error: /upload/check
[Tue Jan 28 15:11:08.917357 2020] [wsgi:error] [pid 7709] Traceback (most recent call last):
[Tue Jan 28 15:11:08.917360 2020] [wsgi:error] [pid 7709]   File "/home/geo/Envs/geonode/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
[Tue Jan 28 15:11:08.917362 2020] [wsgi:error] [pid 7709]     response = get_response(request)
[Tue Jan 28 15:11:08.917365 2020] [wsgi:error] [pid 7709]   File "/home/geo/Envs/geonode/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
[Tue Jan 28 15:11:08.917367 2020] [wsgi:error] [pid 7709]     response = self._get_response(request)
[Tue Jan 28 15:11:08.917369 2020] [wsgi:error] [pid 7709]   File "/home/geo/Envs/geonode/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
[Tue Jan 28 15:11:08.917372 2020] [wsgi:error] [pid 7709]     response = self.process_exception_by_middleware(e, request)
[Tue Jan 28 15:11:08.917374 2020] [wsgi:error] [pid 7709]   File "/home/geo/Envs/geonode/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
[Tue Jan 28 15:11:08.917376 2020] [wsgi:error] [pid 7709]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Tue Jan 28 15:11:08.917379 2020] [wsgi:error] [pid 7709]   File "/home/geo/Envs/geonode/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
[Tue Jan 28 15:11:08.917381 2020] [wsgi:error] [pid 7709]     return view_func(request, *args, **kwargs)
[Tue Jan 28 15:11:08.917383 2020] [wsgi:error] [pid 7709]   File "/home/geo/Envs/geonode/src/geonode/geonode/upload/views.py", line 639, in view
[Tue Jan 28 15:11:08.917386 2020] [wsgi:error] [pid 7709]     session = upload_obj.get_session()
[Tue Jan 28 15:11:08.917388 2020] [wsgi:error] [pid 7709]   File "/home/geo/Envs/geonode/src/geonode/geonode/upload/models.py", line 91, in get_session
[Tue Jan 28 15:11:08.917390 2020] [wsgi:error] [pid 7709]     return pickle.loads(str(self.session))
[Tue Jan 28 15:11:08.917392 2020] [wsgi:error] [pid 7709] UnicodeEncodeError: 'ascii' codec can't encode characters in position 1058-1062: ordinal not in range(128)
[Tue Jan 28 15:24:56.397946 2020] [wsgi:warn] [pid 10388] mod_wsgi: Compiled for Python/2.7.11.
[Tue Jan 28 15:24:56.397985 2020] [wsgi:warn] [pid 10388] mod_wsgi: Runtime using Python/2.7.12.
[Tue Jan 28 15:24:56.399541 2020] [mpm_prefork:notice] [pid 10388] AH00163: Apache/2.4.18 (Ubuntu) OpenSSL/1.0.2g mod_wsgi/4.3.0 Python/2.7.12 configured -- resuming normal operations
[Tue Jan 28 15:24:56.399566 2020] [core:notice] [pid 10388] AH00094: Command line: '/usr/sbin/apache2'
[Tue Jan 28 15:25:16.804052 2020] [wsgi:error] [pid 10390] uploaded_files: [<InMemoryUploadedFile: ir.shp (application/octet-stream)>, <InMemoryUploadedFile: ir.sbn (application/octet-stream)>, <InMemoryUploadedFile: ir.dbf (application/octet-stream)>, <InMemoryUploadedFile: ir.prj (application/octet-stream)>, <InMemoryUploadedFile: ir.sbx (application/octet-stream)>, <InMemoryUploadedFile: ir.shx (application/octet-stream)>, <InMemoryUploadedFile: ir.cpg (application/octet-stream)>]
[Tue Jan 28 15:25:16.806345 2020] [wsgi:error] [pid 10390] valid_extensions: [u'shp', 'dbf', 'shx', 'prj']
[Tue Jan 28 15:25:16.807299 2020] [wsgi:error] [pid 10390] ir
[Tue Jan 28 15:25:16.808785 2020] [wsgi:error] [pid 10390] Name for layer: u'ir'
[Tue Jan 28 15:25:16.911236 2020] [wsgi:error] [pid 10390] files_to_upload: [u'/tmp/tmp2Hjl8Q/ir.shp', u'/tmp/tmp2Hjl8Q/ir.dbf', u'/tmp/tmp2Hjl8Q/ir.shx', u'/tmp/tmp2Hjl8Q/ir.prj']
[Tue Jan 28 15:25:16.911307 2020] [wsgi:error] [pid 10390] Uploading featureType
[Tue Jan 28 15:25:16.915860 2020] [wsgi:error] [pid 10390] /home/geo/Envs/geonode/lib/python2.7/site-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
[Tue Jan 28 15:25:16.915875 2020] [wsgi:error] [pid 10390]   InsecureRequestWarning)
[Tue Jan 28 15:25:16.934640 2020] [wsgi:error] [pid 10390] /home/geo/Envs/geonode/lib/python2.7/site-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
[Tue Jan 28 15:25:16.934653 2020] [wsgi:error] [pid 10390]   InsecureRequestWarning)
[Tue Jan 28 15:25:16.952682 2020] [wsgi:error] [pid 10390] /home/geo/Envs/geonode/lib/python2.7/site-packages/urllib3/connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
[Tue Jan 28 15:25:16.952694 2020] [wsgi:error] [pid 10390]   InsecureRequestWarning)
[Tue Jan 28 15:25:17.222421 2020] [wsgi:error] [pid 10391] Internal Server Error: /upload/check
[Tue Jan 28 15:25:17.222442 2020] [wsgi:error] [pid 10391] Traceback (most recent call last):
[Tue Jan 28 15:25:17.222445 2020] [wsgi:error] [pid 10391]   File "/home/geo/Envs/geonode/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
[Tue Jan 28 15:25:17.222447 2020] [wsgi:error] [pid 10391]     response = get_response(request)
[Tue Jan 28 15:25:17.222450 2020] [wsgi:error] [pid 10391]   File "/home/geo/Envs/geonode/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
[Tue Jan 28 15:25:17.222452 2020] [wsgi:error] [pid 10391]     response = self._get_response(request)
[Tue Jan 28 15:25:17.222455 2020] [wsgi:error] [pid 10391]   File "/home/geo/Envs/geonode/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
[Tue Jan 28 15:25:17.222457 2020] [wsgi:error] [pid 10391]     response = self.process_exception_by_middleware(e, request)
[Tue Jan 28 15:25:17.222459 2020] [wsgi:error] [pid 10391]   File "/home/geo/Envs/geonode/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
[Tue Jan 28 15:25:17.222462 2020] [wsgi:error] [pid 10391]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Tue Jan 28 15:25:17.222464 2020] [wsgi:error] [pid 10391]   File "/home/geo/Envs/geonode/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
[Tue Jan 28 15:25:17.222467 2020] [wsgi:error] [pid 10391]     return view_func(request, *args, **kwargs)
[Tue Jan 28 15:25:17.222469 2020] [wsgi:error] [pid 10391]   File "/home/geo/Envs/geonode/src/geonode/geonode/upload/views.py", line 639, in view
[Tue Jan 28 15:25:17.222471 2020] [wsgi:error] [pid 10391]     session = upload_obj.get_session()
[Tue Jan 28 15:25:17.222474 2020] [wsgi:error] [pid 10391]   File "/home/geo/Envs/geonode/src/geonode/geonode/upload/models.py", line 92, in get_session
[Tue Jan 28 15:25:17.222476 2020] [wsgi:error] [pid 10391]     return pickle.loads(str(u''.join(self.session.decode('utf-8'))))
[Tue Jan 28 15:25:17.222478 2020] [wsgi:error] [pid 10391]   File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
[Tue Jan 28 15:25:17.222481 2020] [wsgi:error] [pid 10391]     return codecs.utf_8_decode(input, errors, True)
[Tue Jan 28 15:25:17.222483 2020] [wsgi:error] [pid 10391] UnicodeEncodeError: 'ascii' codec can't encode characters in position 1058-1062: ordinal not in range(128)
